### ISSUE TITLE
rtx: improve surface lights culling

### ISSUE THREAD

**Issue by w23** [w23/xash3d-fwgs#100]
- [x] collect by bsp leafs and pvs
  - [x] static surface lights
  - [x] dynamic lights
- [x] bbox culling
  - [x] cull by normal direction
  - ~[ ] cull by pdf/distance/"light intensity"~
    - [x] check that this makes sense (by late culling in shader): IT DOESN'T. light are usually bright enough to affect really distant objects
- [x] late culling in shader:
  - [x] cull by target geometry normal
  - [x] cull by max possible color (emissive * target)
  - [x] cull by brdf attenuated color

**Comment by 0x4E69676874466F78** [comment]
@w23 
1. Там вообще есть point light, добавил эту текстуру в рад для теста когда point light ещё не было реализовано в рендере и благополучно забыл. Короче я выпилю на этой карте в следующем обновлении радов. Однако возможны похожие ситуации где поинтлайтов нет а сами текстуры светятся и qrad это вполне обработает, а вот у нас будут проблемы так что да патчить где-то возможно придётся. 
2. Понял.

**Comment by 0x4E69676874466F78** [comment]
@w23 
> Либо хардкодить конкретно случай для 0 яркости, что для релиза более, чем странно.

Я думал что просто на этапе парсинга если на карте у текстуры яркость 0 то выкидывать вообще эту текстуру будто она и в lights.rad и mapname.rad не существует.

**Comment by w23** [comment]
Fixed in vulkan branch
