### ISSUE TITLE
No info about RAD files inside wiki

### ISSUE THREAD

**Issue by zgdump** [w23/xash3d-fwgs#11]
I installed the engine according to the instructions from the Wiki, but after launching all the light sources are missing. For lighting you need copy RAD files into the valve/rad folder inside the build folder, which is not mentioned in the [wiki](https://github.com/w23/xash3d-fwgs/wiki/64-bit-build-on-Windows). The debug RAD files are located in the source code of the vulkan renderer, in the ref_vk/rad folder. Please add this information

**Comment by w23** [comment]
Btw added this just now

**Comment by 0x4E69676874466F78** [comment]
Сейчас рад файлы автоматически добавляются куда нужно.
Кроме этого теперь есть страницы:
https://github.com/w23/xash3d-fwgs/wiki/How-to-add-support-for-mod-in-ray-tracing
https://github.com/w23/xash3d-fwgs/wiki/Как-добавить-поддержку-мода-в-трассировке-лучей
