### ISSUE TITLE
Attenuation of emissive surfaces is not great

### ISSUE THREAD

**Issue by w23** [w23/xash3d-fwgs#114]
Couple of obvious issues:
- #71 
- geometry "too close" to emitting surfaces is being overlit by `1. / (d^2)` singularity.

**Comment by 0x4E69676874466F78** [comment]
#260?

**Comment by 0x4E69676874466F78** [comment]
Закрыть наверное надо?

**Comment by w23** [comment]
Оно более-менее сделано, да. Только ещё не попало в вулкан-ветку.
