### ISSUE TITLE
implement entity lights

### ISSUE THREAD

**Issue by w23** [w23/xash3d-fwgs#115]
`gEngine.GetEntityLight()` might return entity lights. These are usually attached to a specific entity and only affect it in GL renderer.
We need to figure out how to implement this attachment for vk ray tracing. And also make sure that these lights don't end up being inside model geometry and thus shadowed all the time.

elights usually appear when enemies fire.

**Comment by 0x4E69676874466F78** [comment]
Я думаю надо раскомментировать тот код.
