### ISSUE TITLE
Plot overlay performance trace of the previous frame

### ISSUE THREAD

**Issue by w23** [w23/xash3d-fwgs#123]
It's would be nice to have an overlay that shows performance trace with all scope trees and stuff.

(also plot timing graphs for individual scopes?)

**Comment by 0x4E69676874466F78** [comment]
Сделал же?

**Comment by w23** [comment]
Не, тут более богатая задумка, с графиками, деревьями и прочей статистикой.

**Comment by w23** [comment]
Вот теперь сделано.
(но я уже забыл, что именно имел в виду под деревьями)
