### ISSUE TITLE
Soft shadows for environment lights

### ISSUE THREAD

**Issue by w23** [w23/xash3d-fwgs#126]
Currently we treat env light as infinitely distant point lights.
Make use of stopdot* params to randomize sampling and produce soft shadows.

Will also need to apply this: https://github.com/ValveSoftware/halflife/blob/master/utils/qrad/lightmap.c#L1007

**Comment by 0x4E69676874466F78** [comment]
Связано #151

**Comment by w23** [comment]
Done in the handmade-brdfs branch/PR
