### ISSUE TITLE
Ran out of dynamic model geometry slots

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#132]
`[2021:10:22|21:09:21] ^1Error:^7 Ran out of dynamic model geometry slots for model maps/c4a1.bsp water`

**Comment by w23** [comment]
Оохх. Для этой штуки нужно будет, обзорно:
- [ ] Разбить brush модель на 2+ рендер-модели: одна статичная, другая/ие -- для водички. Водичка часто существует отдельной entity в движке, но с точки зрения кода это не обязательно, должно зависеть от рендермоды.
- [ ] Предаллоцировать модели+геометрию для SURF_DRAWTURB и предрассчитывать один раз при загрузке.
- [ ] Научить лучевые модели быть динамическими и обновляться. Водяные модели будут предрассчитаны при загрузке уровня, но фиксированы в памяти и обновляться геометрией слегка каждый кадр (и не обязательно присутствовать в сцене каждый кадр -- движок отсекает энтити сам)

Всё остальное должно сработать более-менее автоматически. И свечение, и всякое.

**Comment by w23** [comment]
Это тоже сделано в #537
