### ISSUE TITLE
Smoothing groups (auto smooth normals)

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#139]
qrad:
> -smooth <integer>
>    Set the threshold for smoothing groups, in degrees (default: 45).

https://github.com/ValveSoftware/halflife/blob/master/utils/qrad/qrad.c#L1265
https://github.com/ValveSoftware/halflife/blob/master/utils/qrad/qrad.c#L1464
https://github.com/ValveSoftware/halflife/blob/master/utils/qrad/lightmap.c#L82-L99

![](https://developer.valvesoftware.com/w/images/b/bf/Smoothing_groups_smoothing_example.jpg)

**Comment by w23** [comment]
Ладно не в три, но в полтора.

Здесь нужно:
- завести табличеньку на каждый `medge_t`, хранящую:
    - какие `msurface_t` она склеивает
    - сглаженная ли нормаль
    - сглаженная нормаль
- заранее обойти все msurface и заполнить табличку с medge->msurface
    - если обе прямая и обратная поверхности нашлись, сгладить их нормали, если их угол меньше порогового
- при непосредственно загрузке на каждую вершину консультироваться с табличкой. Может быть три варианта сглаживания: нет сглаживания, надо сгладить с одним ребром, надо сгладить с двумя рёбрами. (точно линейно сглаживать? а если найду?)

**Comment by LifeKILLED** [comment]
Мы немного поболтали с Найтфоксом и пришли к вот такому формата файла патчей:

Режим 0: полное отключения сглаженности всех ребер перечисленных плоскостей со всех их сторон и между собой в том числе, перевод на шейдинг без сглаживания:

{
"_xvk_surface_id" "12 88 142"
"_xvk_smooth" "0"
}

Режим 1: Принудительное сглаживание рёбер между всеми этими полигонами, в том числе если не сработал порог 45 градусов (какой-то порог всё равно должен быть, чтобы исключить сглаживание между дублирующимися двухсторонними поверхностями, скажем, в 180 градусов или чуть меньше):

{
"_xvk_surface_id" "14 66 52" // целевые грани через пробел
"_xvk_smooth" "1"
}

2. Точечное добавление острых рёбер между парами плоскостей. В кавычках указываются по два номера плоскостей, между которыми ребра мы не сглаживаем. В данном случае это ребро между 22 и 314, между 22 и 324 и между 23 и 443

{
"_xvk_surface_id" "22 314 22 324 23 443"
"_xvk_smooth" "2"
} 

Это всё касается исключительно удобства создания патчей. 2 режим предложен мной, чтобы можно было вносить точечные изменения.

**Comment by LifeKILLED** [comment]
https://github.com/w23/xash3d-fwgs/pull/348

В моей реализации еще нет возможности патчей. Сглаживания там прикручена в функцию перевода браш-моделей в полигоны при ее загрузке. В главном цикле заполняется вспомогательный массив структур с int-координатами вершин (для скорости), пренадлежностью к плоскостям. Второй цикл "соединяет" эти вертексы, заполняя массив в вспомогательной структуре из максимум 16 uint id соединенных с ним вертексов. Именно во втором цикле мы отбраковываем вертексы по нормалям, туда же можно будет интегрировать и патчи. В третьем цикле, используя эти связи, вычисляются конечные нормали

**Comment by w23** [comment]
Примеры, их много:
> c1a0a трубы
![image](https://github.com/w23/xash3d-fwgs/assets/321361/de62f7bc-38b3-47e2-80cc-b35428390ca4)

**Comment by 0x4E69676874466F78** [comment]
c1a0d загибающиеся коридоры
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/3c0177cc-d46c-488a-a858-d2e9899e9f5d)
с1a0a трубы
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/227485a0-721f-4eac-a2e6-58be892cc3e6)
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/45a79edd-0095-4fbb-8d34-c80e7cc61d01)
c2a5a трубы большие
![image-1](https://github.com/w23/xash3d-fwgs/assets/4449851/cb35e12c-5503-4741-b61d-36dfe6dbf7cc)
c1a0e вентиляция?
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/ce2b7560-560d-412d-bb8f-3cad8dfdb674)
c1a1b бочки и баллоны
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/16b6c899-6e7b-4433-a60a-0d7d03ffaed7)
![image-1](https://github.com/w23/xash3d-fwgs/assets/4449851/03653322-ca6b-4d15-8fe4-4f275717fc72)
c0a0a 
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/87d595a5-8c52-4d84-8f8c-1da0be92718b)
