### ISSUE TITLE
Correct flashlight 

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#148]
- [x] сделать общий (говно)код (поэтому пока нет пуллреквеста)
- [x] преобразовать координатное пространство камеры в пространство точечных источников освещения рендера
- [ ] добавить Lightcookie-текстуру (это просто серая маска перед фонариком которая создаёт нужное очертание света от фонарика), как это сделать? мы можем аллоцировать как-то геометрию с текстурой сейчас? как свет реагирует с полупрозрачкой?
- [x] прилизать код

**Comment by 0x4E69676874466F78** [comment]
@w23

**Comment by w23** [comment]
А в чём сложность с 2? Там же тупо в `dir` лежит вектор направления источника света в мировых координатах. Кладёшь туда `g_camera.vforward` и *дело в шляпе*.

С 3 будет целая песня, давай отложим пока на улучшалки факультативные. Пока можно stopdot'ы подобрать на глазок.

**Comment by 0x4E69676874466F78** [comment]
> А в чём сложность с 2? Там же тупо в dir лежит вектор направления источника света в мировых координатах. Кладёшь туда g_camera.vforward и дело в шляпе.

В том что я это не знаю и понять без серьёзного разбора не могу? Зачем мне на это тратить время если ты это уже знаешь. Спасибо за ответ, попробую g_camera.vforward.

> С 3 будет целая песня, давай отложим пока на улучшалки факультативные. Пока можно stopdot'ы подобрать на глазок.

Хорошо.

**Comment by 0x4E69676874466F78** [comment]
```C
VectorCopy(g_camera.vforward, plight->dir);
```
Не прокатило, он вообще не появляется, если stopdot'ы указаны (если не указаны то есть обычный поинт).
В зеркале без stopdot'ов кстати видно вот что:
![изображение](https://user-images.githubusercontent.com/4449851/147294510-8cf839f4-13ef-4152-a51d-a17fccca61c8.png)
Как будто какая-то стена теневая. Я специально под углом наклонил чтобы её лучше было видно.
![изображение](https://user-images.githubusercontent.com/4449851/147294578-5192f762-577b-4610-9041-a771986f8d47.png)

Мне кажется там что-то другое. 

Эмпирически я могу его зафиксировать в одно направление через 	
```
VectorSet(angles, 0, -90, 0);
VectorCopy(angles, plight->dir);
```
Тогда будет смотреть то ли прямо, то ли в бок, но короче не вниз и не верх, а по середине фиксировано и как будто со смещением от игрока то есть это правда какие-то пространственные координаты хитрые.

**Comment by 0x4E69676874466F78** [comment]
g_camera.vforward это то что надо, спасибо!
Разобрался в чём проблема это оказывается неправильно были stopdot'ы, они тоже в своём пространстве.
Ещё проблема с яркостью, сейчас с ней разберусь и сделаю пуллреквест.

**Comment by MaxG2D** [comment]
@0x4E69676874466F78 just a small pro-tip, make sure to add some side and up offset to the light, rather than shooting it directly from the center of the screen, that makes the shadows more pronounced and interesting looking. Stalker does that and it adds a LOT to the horror atmosphere :)

**Comment by 0x4E69676874466F78** [comment]
@MaxG2D да-да, но технически для меня это сейчас сложно, пока не понимаю как это сделать чтобы он не ломался при поворотах.
