### ISSUE TITLE
Basic file structure for materials 

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#155]
### Общее 
Сделать загрузку так чтобы не сломать уже работающую логику движка с PAK и ZIP!
То есть чтобы можно было паковать pbr_replacements в архивы и удобно распространять.

Файл конфигурации материала (далее конфиг) для удобства имеет название `texname`.mat где `texname` имя текстуры к которому он относится, но может быть произвольным. 
Внутри конфига описывается имя исходной текстуры и имена заменяющих текстур, это для избежания любых конфликтов именований.

### Структура файлов
В описанной ниже структуре `valve` это имя игры/мода и для другого мода будет другим. 
```
valve/pbr_replacements/wadname.wad/
```
Каталог с заменой текстур новыми материалами для одноимённого оригинального `wadname`.wad
В карте для других модов можно использовать текстуры из WAD файлов что лежат в директории valve, иначе говоря если мы загружены не из `valve` то мы должны заглянуть в `valve/pbr_replacements` в поиске недостающих материалов.
```
valve/pbr_replacements/models/modelname/
```
Замена текстурам из конкретной модели `modelname`.mdl
Каждая текстура в модели имеет своё название по нему и заменяем (связь описывается в `texname`.mat)
```
valve/pbr_replacements/sprites/spritename/
```
Замена спрайта `spritename.spr`
Спрайты хранятся как рядовые текстуры (грузятся как _basecolor). В случае с анимацией в конце постфикс _num где num это порядковый номер кадра (spritename_1.dds, spritename_2.dds), сам список файлов для анимации прописывается в `spritename`.mat.
```
valve/pbr_replacements/gfx/env/envname/
```
Замена окружения (неба) `envname`
Внутри `envname`.mat (если нужны какие-то настройки) и файлы для сторон `bk`, `dn`, `ft`, `lf`, `rt`, `up` (с расширением .`dds` или .`ktx2`) как обычные текстуры высокого разрешения.

**Comment by w23** [comment]
мы тут не решили, что по замене скайбоксов ещё

**Comment by w23** [comment]
А что если мы разделим замену скайбоксов на две части:
1. Пусть патчинг (#117) позволяет заменить имя скайбокса карте.
2. Картинки для скайбоксов мы будем перед родными `gfx/env` пытаться загрузить из `pbr/env/<name>{bk,ft,...}.png` (потенциально впоследствии из одного файла `pbr/env/<name>.ktx`

**Comment by 0x4E69676874466F78** [comment]
@w23 под заменой тут подразумевалось просто выставить одноимённую текстуру с более высоким разрешением и глубиной, ну или кубемапу. Кстати, что лучше? 
![изображение](https://user-images.githubusercontent.com/4449851/143764086-f2755005-8532-451d-a3ee-30d28a7f5b78.png)

Моё мнение, что заменять одно небо на какой-то карте на совершенно другое нам не понадобится.

**Comment by w23** [comment]
Вот теперь сделано.

На будущее: ktx+cubemap+rgb16f, наверное.
