### ISSUE TITLE
Figure out how to importance-sample skylight

### ISSUE THREAD

**Issue by w23** [w23/xash3d-fwgs#16]
We tried to just add `SURF_DRAWSKY` surfaces as emissive to light clusters, and that immediately overflows light cluster buffers because there are way too many such surfaces, and most of them affect the entire map essentially.

I don't have any good ideas of how to address this ATM.
Maybe better culling of such surfaces (i.e. using PVS) would help, decreasing their number a bit?

**Comment by w23** [comment]
So one possible approach is:
- hide `SURF_DRAWSKY` surfaces
- parse `light_environment` entity to get primary (sun) light direction and intensity
- use that for explicit light sampling
  - cast shadow rays to infinity, shadow if they hit anything
  - can enable it conditionally based on whether:
    - map has any sky surfaces
    - sky surfaces are visible from given light cluster
- for rays hitting nothing sample skybox

Alternative:
- do not ignore sky surfaces but specialcase them to:
  - sample fully emissive no-albedo skybox on hit
  - be an end target for sun shadow rays (may improve performance. or degrade. who knows :woman_shrugging:)

**Comment by 0x4E69676874466F78** [comment]
For the sky, light_spot can also be used with the key `_sky` = 1 #38

**Comment by 0x4E69676874466F78** [comment]
Выяснились пикантные особенности неба:
1. light_environment может быть не один, вот примерный список (в скобках число на карте): c0a0b (2), c2a3e (4), c2a4 (2), c2a5 (6), c2a5b (5), c2a5c (2), c2a5e (4), c2a5f (4), c2a5w (5), c2a5x (3), c4a1 (5), c4a1b (3), c4a1y (2), c4a1z (2), crossfire (2), de_piranesi (8). Это посчитал в исходниках карт что нашёл.
2. На карте c0a0b где мы наблюдали на стриме отличающуюся тень это похоже именно тот случай когда взялся второй light_environment который там задан в начале где вагончик опускается.
3. У light_environment есть недокументированный параметр _ambient имеющий значения R G B V как у яркости, в коде не нашёл чтобы он использовался, возможно вальв использовала тогда какие-то другие версии компиляторов, в те времена например не было angles (pitch yaw roll) и были только pitch и angle по отдельности, потом angle из редактора выпилили, а pitch забыли. Какую-то инфу по нему можно прочитать тут https://github.com/ValveSoftware/halflife/blob/master/utils/qrad/qrad.txt#L27 так как ключ для амбиента имеется, но он глобальный, а в картах там можно по зонам задать амбиент.
4. light_environment могут быть в разных местах и задавать разный угол падения солнца, типа пролез по трубе а там уже солнце слегка иначе смотрит, но может быть и недалеко друг от друга, к счастью в таком случае там отличается только _ambient и можно взять просто один из каких-то в группе и его приплюсовать к свету.
5. В коде курада сложно понять (ну я щас точно тупой) как определяется какие поверхности скайбокса отвечают за конкретный light_environment выяснить сложно
 https://github.com/ValveSoftware/halflife/blob/master/utils/qrad/lightmap.c#L1358 наверное в этой функции, там PVS задействуется ещё
и такое есть https://github.com/ValveSoftware/halflife/blob/master/utils/qrad/lightmap.c#L1143-L1164
Проще наверное навелосипедить, пустив без отражений лучи от light_environment в разные стороны и собрать временный список поверхностей неба связанный с этим конкретным light_environment, потом выделить наружные границы суммы всех собранных брашей и записать координаты получившейся коробки, дальше если игрок в этой коробке смотреть в параметры light_environment которая с ним связана и применять их к солнцу.

Обновил #38

**Comment by 0x4E69676874466F78** [comment]
light_spot с `_sky` = 1: c2a2g, c2a2h, c2a4, c2a4e, c2a4f, c2a4g
Все из них с в том числе light_environment.

**Comment by 0x4E69676874466F78** [comment]
@w23 
> Выходит, что нам нужно делать не глобальное солнце, а просто ещё один источник света.

А он будет только за свою зону отвечать?
> Нужно опять собирать эксперименты эти поганые, как туда правильно всё складывать и вообще.
Надо наверное у lifekilled поспрашивать он же ковырялся в этом углубленно.

**Comment by w23** [comment]
> > Выходит, что нам нужно делать не глобальное солнце, а просто ещё один источник света.
>
> А он будет только за свою зону отвечать?

Ага. Вроде это именно то, чего мы хотим.
Не знаю, правда, что там именно со скайбоксом.

**Comment by 0x4E69676874466F78** [comment]
Ещё инфа: на hlrad (компилятор из ZHLT) light_environment работает иначе, он не учитывает другие light_environment и получается всего одна энтити на всю карту. Этот компилятор очень популярный и вроде в модах активно используется.
Моё предложение: если на карте только 
* или одна light_environment 
* или одна light_spot с `_sky`=1 
* или одна light_environment и одна light_spot с `_sky`=1 находящиеся близко друг к другу

то делать солнце(а) глобальным(и).
