### ISSUE TITLE
Crash on change map in thirdperson mode

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#175]
Просто из test_light перейти через портал в test_main.
```
Вызвано необработанное исключение: нарушение доступа для чтения.
this->**m_pStudioHeader** было nullptr.
```

**Comment by 0x4E69676874466F78** [comment]
![image](https://user-images.githubusercontent.com/4449851/222124473-9d953ad4-c2a1-4fb2-8636-4ac35fe527d3.png)
Ошибка в том же файле что и https://github.com/w23/xash3d-fwgs/issues/325#issuecomment-1449919256
Есть смысл за одно править эти багули.

**Comment by w23** [comment]
Более не воспроизводится.
