### ISSUE TITLE
Scale the color factor down

### ISSUE THREAD

**Issue by w23** [w23/xash3d-fwgs#184]
I feel like it should be possible to renormalize every light source and get rid of weird color scale factor.

**Comment by 0x4E69676874466F78** [comment]
Держи карты для теста: https://github.com/w23/xash3d-fwgs/issues/33#issuecomment-957818556

**Comment by 0x4E69676874466F78** [comment]
#260?

**Comment by 0x4E69676874466F78** [comment]
С этим разобрались?
