### ISSUE TITLE
List of geometry (by entity id and face id) that is ignored for a specific light 

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#187]
Возьмём те же лампочки в туннеле на c0a0b, они сделаны в виде брашей:
![изображение](https://user-images.githubusercontent.com/4449851/139832684-fc02010e-d6a8-408b-be2d-c6267afb3fbf.png)
По хорошему я должен вложить point light внутрь этих брашей, но если я так сделаю они не будут светиться а если поставлю рядом освещение будет некорректным, следовательно нужно задать какие поверхности надо проигнорить. В ряде случаев достаточно entity id (для брашей-энтити), но в данном случае нужно по face id.
Возвращаясь к идее с форматом я бы написал это так:
```
{
"origin" "-2473 2454 -1523"
"_light" "255 255 255 200"
"_light_IGNORE_FACE_ID" "3280 3284 3286 3291 3288 3283 3239 3303"
"_light_IGNORE_ENTITY_ID" "52"
}
```

**Comment by 0x4E69676874466F78** [comment]
Есть проблема с func_breakable энтитями, если энтити такая уничтожается её ид может занять другая энтити которая создаётся в рантайме (например какая-то модель типа снарков или других порождающихся монстров).
Следовательно нужна проверка на уничтожилась ли энтити или нет, если уничтожился то _light_IGNORE_ENTITY_ID надо выкидывать. Либо вообще ограничиться только face id.

**Comment by w23** [comment]
Здесь речь может идти о двух вещах:
1. Игнорировать определённые браши при расчёте теней. То есть некоторые браши прозрачные и не отбрасывают тень от заданного источника света.
2. Игнорировать определённый источник света при расчёте освещения определённой поверхности.

(2) сделать немного коряво, но можно. Но насколько я понял это не то, что здесь запрашивается.

(1) сделать в виде именно "один источник -> набор поверхностей" крайне трудно и неприятно. Не могу придумать ничего, что не ломало бы производительность и структуры данных пополам.
Можно сделать список поверхностей (брашей, энтитей, ...), которые в принципе не отбрасывают тень для **всех** источников света, а не для конкретных.

**Comment by 0x4E69676874466F78** [comment]
@w23 речь про 1. Так нам надо пробить сквозь эту геометрию, значит она должна быть прозрачной.

> (1) сделать в виде именно "один источник -> набор поверхностей" крайне трудно и неприятно. Не могу придумать ничего, что не ломало бы производительность и структуры данных пополам.

Печально. Примерно понимаю, даже если сделать динамические свитчи (хз можно ли это в сишке по простому) всё равно нужны условия и при обходе наверное будут кэшпромахи, а городить отдельный список поверхностей для конкретного источника это надо менять архитектуру.

>  Можно сделать список поверхностей (брашей, энтитей, ...), которые в принципе не отбрасывают тень для всех источников света, а не для конкретных.

Наверное это будет приемлемо, это лучше чем ничего. Альтернатива некрасивые тени. Ещё вариант можно эти поверхности запатчить чтобы они стали с additive-режимом, но это тоже будет не просто.

**Comment by 0x4E69676874466F78** [comment]
Есть ещё одна (возможно глупая) идея которая может помочь в случае с лампочками.
Мы можем добавить источнику параметр грубого кулинга геометрии рядом с ним, типа от какого расстояния считать что мы что-то видим, всё что внутри просто отсекается. Не знаю насколько это сложно реализовать, просто в голову пришло.

**Comment by w23** [comment]
> Есть ещё одна (возможно глупая) идея которая может помочь в случае с лампочками. Мы можем добавить источнику параметр грубого кулинга геометрии рядом с ним, типа от какого расстояния считать что мы что-то видим, всё что внутри просто отсекается. Если это проще в реализации то была бы хорошей штукой для таких случаев, потому что тогда будут видны тени от других лампочек.

Вот это хорошая идея, и её легко реализовать: задавать виртуальный радиус источнику: если источник света ближе, или же теневой луч упёрся в этот радиус, то считать, что тени нет.

> Сами лампочки я бы наверное с патчингом мог сделать полупрозрачными стёклами с мелкими отражениями как у реальных лампочек.

Вклад от этого в пиксели будет незаметный, а производительность будет страдать.

**Comment by 0x4E69676874466F78** [comment]
@w23 
> Вот это хорошая идея, и её легко реализовать

Это круто!

> Вклад от этого в пиксели будет незаметный, а производительность будет страдать.

Ну надо посмотреть если возможность патчинга будет (часть вещей всё равно желательно запатчить из геометрии). Будет тормозить уберу.

**Comment by w23** [comment]
Решил не делать?

**Comment by 0x4E69676874466F78** [comment]
Я запатчил эти места иначе и вроде там ок визуально. В других местах особо не бросалось пока где есть надобность. Если остро понадобится тогда открою.
