### ISSUE TITLE
Tonemapping with gamma correction

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#194]
Я думаю можно взять отсюда реализацию:
https://www.shadertoy.com/view/3llyzH
```
    // Gamma correction 
    return pow(mapped, vec3(1.0 / 2.2));
```
Заодно можно добавить обработку консольной команды gamma.
Там ещё экспозиция есть, тоже можно взять. Я потестировал вроде ок.
Ещё не ясно отличие реализаций ACESFilm какая-то из них потенциально быстрее может быть с тем же самым результатом?

**Comment by w23** [comment]
Так у нас ранее это и было. Не именно это, а `sqrt(C)`, что с пивом примерно такое же.

А вскопипащенный ACES уже содержит гамма-коррекцию, поэтому я не очень понимаю, что тут делать.

**Comment by 0x4E69676874466F78** [comment]
@w23 точно уверен что содержит?
https://knarkowicz.wordpress.com/2016/01/06/aces-filmic-tone-mapping-curve/ я почитал, да могут вхардкодить гамму прям в значения, но это не очень красиво.
А в этой реализации по ссылке гамму вынесли.
Если я правильно понимаю всё это.
Единственно что я для себя понял, что когда будет PBR-материалы я буду тестить на референсах https://github.com/ampas/aces-dev/tree/master/images а то возможно обосрамс.
