### ISSUE TITLE
rendering artifacts on intel hw on linux

### ISSUE THREAD

**Issue by w23** [w23/xash3d-fwgs#2]
Apparently dynamic uniform buffer offsets need to be properly aligned:
```221 API High Miscellaneous 2258532037 Validation Error: [ VUID-vkCmdBindDescriptorSets-pDynamicOffsets-01971 ] Object 0: handle = Command Buffer 183, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x869e76c5 | vkCmdBindDescriptorSets(): pDynamicOffsets[0] is 80 but must be a multiple of device limit minUniformBufferOffsetAlignment 0x40. The Vulkan spec states: Each element of pDynamicOffsets which corresponds to a descriptor binding with type VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC must be a multiple of VkPhysicalDeviceLimits::minUniformBufferOffsetAlignment (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkCmdBindDescriptorSets-pDynamicOffsets-01971)```

**Comment by w23** [comment]
this is fixed in https://github.com/w23/xash3d-fwgs/commit/e5b14c039377cdf497f026e8f0c2b6ae0e70f934
and i forgot to tag this

**Comment by nilsoncore** [comment]
^ misuse of `#` symbol, sorry.
