### ISSUE TITLE
 materials: not applies for studiomodel

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#216]
На оружие не применяется, однако в логах есть запись:
```
[2021:11:18|02:08:56] Uploading texture pbr/HGUN_Back1.png, mips=10
[2021:11:18|02:08:56] Loading texture pbr/HGUN_Back1.png => 780
```

**Comment by w23** [comment]
Нужны ассеты для отладки

**Comment by 0x4E69676874466F78** [comment]
@w23 https://github.com/w23/xash3d-fwgs/issues/33#issuecomment-974228364 здесь есть "материал" для револьвера для отладки.
