### ISSUE TITLE
Engine mirrors

### ISSUE THREAD

**Issue by a1batross** [w23/xash3d-fwgs#224]
In Quake mirrors are fully supported (although completely forgotten).

Old Xash3D restored that feature but it was cut in the new engine.

It was checked by texture name. If it starts with "reflect" or "!reflect", the reflect bit is applied to the surface: https://github.com/FWGS/xash3d/blob/master/engine/common/model.c#L1957 \
Rendering code: https://github.com/FWGS/xash3d/blob/master/engine/client/gl_mirror.c

Half-Life doesn't use this texture anywhere as far as I know but mods do.

**Comment by 0x4E69676874466F78** [comment]
Нам легко поддержать это, тупо добавив материалы для этих текстур выставив металлик и минимальшую шероховатость = зеркало.

**Comment by 0x4E69676874466F78** [comment]
https://github.com/w23/xash3d-fwgs/issues/33#issuecomment-976854146 сделал тут.
