### ISSUE TITLE
rtx: skybox looks way duller than in gl renderer

### ISSUE THREAD

**Issue by w23** [w23/xash3d-fwgs#230]
It's almost as if gamma is slightly incorrect?
Tried: _SRGB instead of _UNORM, looks relatively correct (modulo aces tonemap).

Not clear why would skybox texture *only* require _SRGB. I think all of the textures need to be _SRGB, but then they look completely wrong.

**Comment by 0x4E69676874466F78** [comment]
Подозреваю что это из-за того что небо это additive и тогда https://github.com/w23/xash3d-fwgs/issues/267#issuecomment-991669013 (1 пункт).
Как раз совпадает https://github.com/w23/xash3d-fwgs/blob/405a9ecbb4ce2e8183e716175b701cd4b6ea25f7/ref_vk/shaders/ray.rchit#L99 с https://github.com/w23/xash3d-fwgs/issues/267#issuecomment-990953957
Только я не на 2.2 а на 2 просто.
Да и кто у нас payload.emissive? additive только.

**Comment by 0x4E69676874466F78** [comment]
Так что после того как починишь additive надо будет выпилить этот pow для skybox.

**Comment by 0x4E69676874466F78** [comment]
Это можно закрыть. Была проблема с гаммой. Детали здесь: https://github.com/w23/xash3d-fwgs/issues/321
