### ISSUE TITLE
Broken transparency on explosions/smoke (from grenade, rocketlauncher)

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#256]
![изображение](https://user-images.githubusercontent.com/4449851/144666176-300cea9b-d9ac-44bd-a56d-33166756f88a.png)
![изображение](https://user-images.githubusercontent.com/4449851/144666545-ec3f7eab-0eb6-41fc-adc1-5d087845bc73.png)

**Comment by 0x4E69676874466F78** [comment]
Сейчас дым не чёрный а белый но всё равно не очень красивый. Чёрные квадратные спрайты остались.

**Comment by w23** [comment]
Здесь для традиционного рендера сломан блендинг. Дело в том, что rendermode работают сильно по-разному для разных типов энтитей.

Для лучей у нас нет субтрактивной полупрозрачности без никто (без преломлений, етц). Надо добавлять.

**Comment by 0x4E69676874466F78** [comment]
> Дело в том, что rendermode работают сильно по-разному для разных типов энтитей.

Например?
