### ISSUE TITLE
No spark is visible at the rail junction on c0a0b. 

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#263]
https://user-images.githubusercontent.com/4449851/145187605-f6d781a0-7562-4645-bf97-883e01006d21.mp4

На бранче E177 тоже не видно.

**Comment by w23** [comment]
А как должно быть?

**Comment by 0x4E69676874466F78** [comment]
@w23 
https://user-images.githubusercontent.com/4449851/145186922-2bf72f00-8087-485f-92d8-9bb83bf9984f.mp4

**Comment by w23** [comment]
а. это, наверное, типы партиклов не все

**Comment by w23** [comment]
Посмотрел в лог, похоже что это `CL_DrawTracers`

**Comment by w23** [comment]
Да, это трейсеры и фу они стрёмные. Они вообще делаются в скринспейсе. Надо прям расковыривать

**Comment by w23** [comment]
Ладно я сделал: https://github.com/w23/xash3d-fwgs/pull/268
Но там криво, надо цвет протаскивать правильно. Он там сейчас супер кривой.

**Comment by 0x4E69676874466F78** [comment]
https://user-images.githubusercontent.com/4449851/145402106-4a68b252-bbcc-48f5-bdf0-d1323a01c0e9.mp4
Да, ну теперь хоть показывается подобие.
