### ISSUE TITLE
rtx: better spherical lights sampling

### ISSUE THREAD

**Issue by w23** [w23/xash3d-fwgs#266]
- [x] actual spherical surface sampling, examples
  - https://www.shadertoy.com/view/wsScWt
- [x] how to properly address spotlights angles

**Comment by w23** [comment]
References to read:
- [ ] https://momentsingraphics.de/I3D2019.html
- [ ] https://onrendering.com/data/papers/pivot/pivot.pdf

**Comment by 0x4E69676874466F78** [comment]
Связано #151
