### ISSUE TITLE
rtx: some emissive entities break light clusters

### ISSUE THREAD

**Issue by w23** [w23/xash3d-fwgs#279]
[test_brush3.zip](https://github.com/w23/xash3d-fwgs/files/7697685/test_brush3.zip)
![test_brush3_shot0000](https://user-images.githubusercontent.com/321361/145690112-fad982f8-6bae-46f3-85de-e748d877f2c4.png)

**Comment by 0x4E69676874466F78** [comment]
Вот минималистичные карты [test_brush3_bug.zip](https://github.com/w23/xash3d-fwgs/files/7697706/test_brush3_bug.zip)
2 где видна границы, 3 где просто чёрный браш, вода тут не виновата.

**Comment by 0x4E69676874466F78** [comment]
На test_rtxlight баг можно поймать в динамике на одном из углов:
![изображение](https://user-images.githubusercontent.com/4449851/146065417-9de00edd-081d-4d9b-be73-5895ee1c8617.png)

**Comment by MaxG2D** [comment]
> On test_rtxlight, the bug can be caught in dynamics at one of the corners: ![image](https://user-images.githubusercontent.com/4449851/146065417-9de00edd-081d-4d9b-be73-5895ee1c8617.png)

This is now fixed, however, the bug at `c1a4i` still exists
![c1a4i_0000](https://user-images.githubusercontent.com/88550439/147418643-2302b38a-2826-4c31-aa06-67907d8616c4.png)

**Comment by MaxG2D** [comment]
@w23

**Comment by 0x4E69676874466F78** [comment]
@MaxG2D я не могу найти это место с таким багом, скинь сохранение.

**Comment by MaxG2D** [comment]
[save001.zip](https://github.com/w23/xash3d-fwgs/files/7777539/save001.zip)

**Comment by 0x4E69676874466F78** [comment]
@MaxG2D нету бага. Ты точно слил изменения?

**Comment by 0x4E69676874466F78** [comment]
![изображение](https://user-images.githubusercontent.com/4449851/147422232-cde82fa8-8be5-4822-96e6-a834b65a4acc.png)

**Comment by 0x4E69676874466F78** [comment]
Я понял, это видно только на фонарике.

**Comment by 0x4E69676874466F78** [comment]
![](https://media.discordapp.net/attachments/881757556811395072/924803915772493874/unknown.png)
![](https://cdn.discordapp.com/attachments/881757556811395072/924803916401618974/unknown.png)
![](https://cdn.discordapp.com/attachments/881757556811395072/924803916737159228/unknown.png)


https://user-images.githubusercontent.com/4449851/147422362-77b6f905-0566-4066-9dbe-fdfe95bb0e1c.mp4
