### ISSUE TITLE
patch: hot reload by console command

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#281]
Тюнить на лету патчи сейчас невозможно, перезагрузка туда-сюда отнимает время.
Оказывается там вообще приходится всю игру перезапускать в некоторых случаях.

**Comment by w23** [comment]
Довольно трудно делать обновление удаления поверхностей. Там нужно вмешиваться в структуры данных, считающиеся постоянными после загрузки уровня. Это либо пытаться аккуратно перезагружать вообще весь уровень (неизвестно, насколько легко сделать, т.к. там есть вещи, приходящие из движка, над которыми у нас нет контроля). Либо аккуратно пересобирать бласины (готовить специальный путь в коде для этого).

Остальное, вроде, нетрудно.

**Comment by 0x4E69676874466F78** [comment]
> Довольно трудно делать обновление удаления поверхностей

Готов без проблем пережить отсутствие этой штуки. Удалять поверхности нужно довольно редко и можно заранее всё написать и немного помучиться с перезагрузкой игры.

Другое дело смена _light для поверхностей, вот это нужно очень часто. Как и тюнинг ключей энтити. Кстати о тюнинге ключей, как я понимаю влиять на энтити кроме световых я никак не могу?

Мне ещё нужно  #291 иначе замена текстур по большей части бесполезная.

**Comment by w23** [comment]
сделяль https://github.com/w23/xash3d-fwgs/commit/659402cb2ab9049aad96f5bdd0aee74f174dd667

удалять не умеет, остальное должно уметь.
