### ISSUE TITLE
RTX: Incorrect alpha on map c1a4d

### ISSUE THREAD

**Issue by MaxG2D** [w23/xash3d-fwgs#290]
VK:
![unknown2](https://user-images.githubusercontent.com/88550439/146099157-19c9ecc0-9477-4965-804f-0f1c35ed99d9.png)
VK PathTracing:
![unknown](https://user-images.githubusercontent.com/88550439/146099129-7ce98a57-d8e9-4974-a9e5-1ced613dc20f.png)

**Comment by 0x4E69676874466F78** [comment]
Происходит потому что emissive текстуры в текущей реализации рендера не прозрачные.

**Comment by MaxG2D** [comment]
I thought of checking it out in GL renderer, and surprisingly, the texture is completely different... 
![c1a4d_0000](https://user-images.githubusercontent.com/88550439/147152187-cf089bb4-20fe-4b77-8242-cc16163e2872.png)

**Comment by 0x4E69676874466F78** [comment]
@MaxG2D because RenderMode is Color.

**Comment by 0x4E69676874466F78** [comment]
У нас `rendermode` `1` (color) просто применяет на текстуру цвет из `rendercolor` и полупрозрачность из `renderamt`.
![изображение](https://user-images.githubusercontent.com/4449851/147158100-92c5eca8-b75c-44d6-913c-0cc2af85d5da.png)
В то же время в GL всё тоже самое только браш теряет текстуру и работает с чистым цветом.
![изображение](https://user-images.githubusercontent.com/4449851/147158062-9dc1a6ff-6a9e-4537-a213-46533f044387.png)

**Comment by 0x4E69676874466F78** [comment]
GL:
![image](https://user-images.githubusercontent.com/4449851/222713865-9da31d81-9c21-4c9b-8083-88b764f7524a.png)
VK rastr:
![image](https://user-images.githubusercontent.com/4449851/222713927-9ddcd282-4b0e-4ddd-93c4-cb0d6868f964.png)
VK ray tracing (#460):
![image](https://user-images.githubusercontent.com/4449851/222713964-0a7d8a76-feba-40ab-af3a-4c3e405dae5a.png)
