### ISSUE TITLE
No vertex alpha\No alpha value for sprites supported

### ISSUE THREAD

**Issue by MaxG2D** [w23/xash3d-fwgs#293]
GL:
![1](https://user-images.githubusercontent.com/88550439/146623352-ccf70586-a492-412b-9979-34e704034e5c.jpg)
VK:
![2](https://user-images.githubusercontent.com/88550439/146623356-761f7131-76b0-4893-aac4-fcd5d710f749.jpg)

**Comment by MaxG2D** [comment]
GL:
![3](https://user-images.githubusercontent.com/88550439/146623555-0049c4c0-4d45-4d23-a606-4437ee81f800.jpg)
VK:
![4](https://user-images.githubusercontent.com/88550439/146623559-3306091b-a2b7-4af2-bc32-9fcd597d89c5.jpg)

**Comment by 0x4E69676874466F78** [comment]
Да там на том же c4a1f вот такое:

https://user-images.githubusercontent.com/4449851/146655969-dbf74074-10b3-4e19-b1f5-d4bb34bce1a2.mp4

https://user-images.githubusercontent.com/4449851/146655971-b4043df2-d95c-4c56-b499-db62c08bf285.mp4

**Comment by 0x4E69676874466F78** [comment]
На test_sprite есть 4 блок с этим:
![изображение](https://user-images.githubusercontent.com/4449851/146656974-4d0e7108-5f58-4d90-8017-1fb52970c6c4.png)
![изображение](https://user-images.githubusercontent.com/4449851/146656989-44c82a26-e637-4704-8431-7dc23d4bd9ca.png)

Похоже на моём бранче с изменённым макс кусочки начались странные проблемы.

**Comment by w23** [comment]
Это как-то сделано

**Comment by 0x4E69676874466F78** [comment]
@w23 так закрой. Ишья не моя.
