### ISSUE TITLE
broken lighting over emissive texture

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#296]
Рабочий коммит e3e8693b130530b71a786e688455da34921956b5
Не рабочий коммит 4becafc02c0c02eb28351cc649d9a37ef94093a8
![изображение](https://user-images.githubusercontent.com/4449851/146693181-eb7a5037-e340-4376-b343-ed35601260d6.png)

**Comment by 0x4E69676874466F78** [comment]
https://github.com/w23/xash3d-fwgs/commit/4becafc02c0c02eb28351cc649d9a37ef94093a8#diff-6c13a93e0df24a15163750928ca9fdb9d0850074e5ac490f38066c5d63e96c10R439 это дополнительное условие ломает.

**Comment by w23** [comment]
Оно там by-design. Я пробовал, как оно будет выглядеть, если эмиссив будут строго только эмиссив.

**Comment by 0x4E69676874466F78** [comment]
> Следующей мыслью была как раз маска: участки, которые светят и не принимают, и те, которые только принимают, но не светят сами.

А как быть с тем что какие-то источники могут светить, но слабее других источников?
