### ISSUE TITLE
Broken sprite renderer 

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#297]
Это устарело см. последние комментарии 
~~https://user-images.githubusercontent.com/4449851/146812445-772941d1-8e05-45b7-9ecc-467a858b5b3e.mp4~~

~~При смене оружия меняются артефакты. Там ещё присутствуют какие-то круги.~~

**Comment by 0x4E69676874466F78** [comment]
[test_sprite_bug.zip](https://github.com/w23/xash3d-fwgs/files/7786332/test_sprite_bug.zip) тестовая карта с единственным спрайтом и минимум геометрии с 1 источником света. 

Бага нет если если девственно загрузиться карту без загрузок с других карт.
Если сделать r_drawviewmodel 0 то получение и переключение оружия не оказывает влияния и не ломает спрайт.
Но если хотя бы раз оружие появилось, то перезагрузка/смена уровня мусор не убирает, спрайт будет всегда сломан.
Кроме того если запуститься с test_main без оружия то при переходе на test_sprite или если вписать map test_sprite_bug то спрайт уже будет сломан.
Ломаются любые спрайты с любыми режимами кроме тех что аддитив.

Модели ломают каким-то образом память не аддитив спрайтов и возможно не только их память.

Если посмотреть на этом бранче: https://github.com/w23/xash3d-fwgs/pull/322 то там покажет сразу замусорили спрайт или нет (чёрная окантовка которая пропадает при баге, но которая сама по себе баг денойзера или там ещё что-то срётся в него откуда-то).

![изображение](https://user-images.githubusercontent.com/4449851/147606576-2ae39a46-9941-4d8e-b63f-19fc7c0a4424.png)
![изображение](https://user-images.githubusercontent.com/4449851/147606603-9489d770-7c07-4036-b957-2782d806c18b.png)

**Comment by 0x4E69676874466F78** [comment]
Новая карта [test_sprite_bug2.zip](https://github.com/w23/xash3d-fwgs/files/7786511/test_sprite_bug2.zip)

Особенности:
Если мы залетели в комнату с гманом и посмотрел на него то вернушись назад спрайт сломан.
Если мы залетели в отдельную комнату с костюмом и взяли его, то вернувшись назад спрайт сломан.
Если мы взяли костюм в своей комнате спрайт в этой комнате не сломался, залетели в другую с костюмом, там спрайт тоже нормальный, однако если мы вернёмся назад то увидим что спрайт в исходной комнате сломан.

**Comment by 0x4E69676874466F78** [comment]
Зашумленный фон подозрительно напоминает проблему с #304

**Comment by 0x4E69676874466F78** [comment]
Бага отчасти ушла но не до конца. 
![image](https://user-images.githubusercontent.com/4449851/218741176-30269e34-39ed-44e3-90cf-695a70f83b58.png)

**Comment by 0x4E69676874466F78** [comment]
Цвет неправильный на [test_sprite_bug2](https://github.com/w23/xash3d-fwgs/files/7786511/test_sprite_bug2.zip)

https://user-images.githubusercontent.com/4449851/218741607-92d67fc7-bc61-49a8-a354-355c902b2df6.mp4

**Comment by 0x4E69676874466F78** [comment]
Само мерцание похоже где-то из-за этих функций

https://github.com/w23/xash3d-fwgs/blob/eaf8b3c55a5ba322b45bd79cd6d3f8377f44abea/ref_vk/vk_sprite.c#L876-L878

У спрайтов есть смешвание кадров между собой для большей их плавности, оно почему-то сломано.

**Comment by w23** [comment]
> Само мерцание анимированных спрайтов похоже где-то из-за этих функций
> 
> https://github.com/w23/xash3d-fwgs/blob/eaf8b3c55a5ba322b45bd79cd6d3f8377f44abea/ref_vk/vk_sprite.c#L876-L878
> 
> У спрайтов есть смешивание кадров между собой для большей их плавности, оно почему-то сломано.

Тут два класса проблем:
1. Мусор в памяти у спрайтов вместо нормалей, поэтому их освещение было сломано и мерцало чем попало.
2. lerp действительно не алё, но не для этой тестовой карты. lerp переменные в порядке, но не в порядке их рендеринг для лучей: смешивание делается отрисовкой двух копланарных квадов с разными прозрачностями, что в традиционном рендере их нормально смешивает. Для лучей так просто не получится. Пока просто вырубил лерп.

**Comment by 0x4E69676874466F78** [comment]
Закрыто в пользу #433
