### ISSUE TITLE
Materials: Replacing textures is not reliable

### ISSUE THREAD

**Issue by MaxG2D** [w23/xash3d-fwgs#301]
Same texture name, same RenderMode, yet, the replacing code sometimes breaks:
![c1a2_0000](https://user-images.githubusercontent.com/88550439/146847600-3e89b74a-10f7-470a-99d5-05f12f8f4cde.png)
![c1a2_0001](https://user-images.githubusercontent.com/88550439/146847607-2a487525-3f7b-466b-b2a6-bb7460c446e1.png)

Looks like something related to the kusok indexing.

**Comment by 0x4E69676874466F78** [comment]
А где название карты где это происходит?

**Comment by MaxG2D** [comment]
> And where is the name of the map where is this happening?

c1a2

**Comment by 0x4E69676874466F78** [comment]
```
{
"for" "-0fifties_f02"
"basecolor_map" "/colors/FFF.png"
"base_color" "1 0 0"
"roughness" "0.2"
}
```
![изображение](https://user-images.githubusercontent.com/4449851/146920534-8f7fc523-a7e6-4c07-a142-133d379d123b.png)

**Comment by w23** [comment]
... not patched surfaces seem to have different textures: `-1fifties_f02`, `-2fifties_f02`, `-3fifties_f02`.
`ui_infotool` code goes through a slightly different code path to read texture name.
I suspect this is the case of "random tiling" or whatever.

**Comment by w23** [comment]
:smil:
![c1a2_shot0001](https://user-images.githubusercontent.com/321361/147207887-f6044436-892e-4d3e-9eeb-4694982285de.png)

I think no more changes should be made to the engine regarding to this, so I'm closing it.

**Comment by 0x4E69676874466F78** [comment]
> I suspect this is the case of "random tiling" or whatever.

Да точно. Это те самые случайные тайлы при каждой загрузки карты, правда у нас они выходят не случайные каждый раз :( так как всегда одно и то же расположение. https://www.youtube.com/watch?v=NNv17T02WlY

**Comment by 0x4E69676874466F78** [comment]
https://github.com/FWGS/xash3d-fwgs/issues/712 вот. Пока это нас не касается, как починят надо будет свериться.

**Comment by 0x4E69676874466F78** [comment]
Там починили, надо синхронизоваться будет.
