### ISSUE TITLE
rtx: alpha mask materials should not be translucent

### ISSUE THREAD

**Issue by w23** [w23/xash3d-fwgs#304]
This should not happen (note how the grid is slightly see-through)![c1a0d_shot0003](https://user-images.githubusercontent.com/321361/147019534-05df1503-5850-4283-a491-3af3ddbe8ef3.png)

**Comment by 0x4E69676874466F78** [comment]
Так там наверное полупрозрачность?

**Comment by 0x4E69676874466F78** [comment]
![изображение](https://user-images.githubusercontent.com/4449851/147712265-dd64ebab-48b9-4f41-9d9d-4441c9ec4c9f.png)

**Comment by 0x4E69676874466F78** [comment]
Бага больше нет.
![image](https://user-images.githubusercontent.com/4449851/222739009-5d2c471e-2d9b-443b-a399-013bcaead97a.png)
