### ISSUE TITLE
materials: alpha value for `"base_color"` key

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#308]
Добавить 4 значение в base_color для альфа канала.
Например задаю:
```
{
"for" "!water"
"base_color" "1 1 1 0.5"
}
```
И теперь текстура полупрозрачная.

**Comment by MaxG2D** [comment]
Also, texture based alpha translucency would help a lot. Currently, it's not possible to edit refractive glass texture, cause it becomes opaque.

**Comment by 0x4E69676874466F78** [comment]
@w23 по идее должно наследовать режим какой у неё уже стоит. В идеале ещё дать сменить режим и доп настройки режима.

**Comment by w23** [comment]
Могу тривиально добавить четвёртую компоненту.

Смена режима сложнее:
1. Нужно вообще понимать, на какие режимы можно менять. У нас до сих пор не доделана система материалов вообще: #460 
2. Потянет за собой нетривиальный рефакторинг, т.к. нужно (? надо проверить) будет тогда модель пилить модель на отдельные бласины исходя из материалов. Или по крайней мере аккуратно подкладывать нужные флажки в нужных местах.
