### ISSUE TITLE
Glitch with glasses on c1a0c when texture overwritten by material 

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#317]
Они почему-то непрозрачно зеркальные. У них стоит rendermode 2 (texture), renderamt 60, rendercolor 0 0 0, сама текстура generic028.
![изображение](https://user-images.githubusercontent.com/4449851/147374658-7c309b69-fd18-46b7-a6b3-9557b2938341.png)

**Comment by 0x4E69676874466F78** [comment]
Я забыл что у меня в материалах есть подмена и забыл что надо быть предельно осторожно с глобальными материалами.
С другой стороны, должно ли это
```
{
"for" "generic028"
"basecolor_map" "/colors/white.png"
"metal_map" "/colors/white.png"
"roughness_map" "/colors/555.png"
}
```
Ломать рендермод с прозрачностью?

**Comment by MaxG2D** [comment]
#308

**Comment by 0x4E69676874466F78** [comment]
Ага.

**Comment by 0x4E69676874466F78** [comment]
На текущий момент проблемы в том виде что была уже нет.
Рендермод не ломается, но в то же время у нас нет отражений на стёклах, нельзя настроить для них metal_map, roughness_map и подозреваю normal_map тоже.

**Comment by 0x4E69676874466F78** [comment]
Связано: #521
