### ISSUE TITLE
Gamma correction and lighting

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#321]
Проблемы с гаммой в ксаше здесь: https://github.com/FWGS/xash3d-fwgs/issues/694 (см. особенно комментарии).

Нужно учитывать несколько вещей:
1. в вулкане в меню гамма сейчас как если в ксаше задать `gamma 2.2`.
2. в вулкане в рендере гамма видимо тоже 2.2, но это не точно! потому что насколько я понял движковые функции для работы с гаммой на текстурах не используются и что там сейчас происходит загадка. Говорят текстуры в ХЛ уже в sRGB.
3. ксашевская `gamma 1.9` это примерно 2.2 оригинальной Half-Life WON версии! (если сравнивать по градиенту).
А вот `gamma 2.2` какая-то совсем другая. Нужно сравнить кто из них прав, но субъективно права оригинальная халфа.

Необходимо правильно преобразовать текстуры в линейное пространство и только потом применять гамма коррекцию!
pow это грубая аппроксимация, нужно использовать специальные функции!

**Comment by w23** [comment]
Пользуясь случаем, хочу сообщить, что я недавно на стриме совсем сломал гамму, убрав sqrt | pow(, 1./2.2).
Ничего вулкан вместо нас не делает, и эта коррекция должна быть (т.к. мы пишем всё ещё в LDR sRGB буфер).

Вот картинка `pix.x / res.x` от 0 к 1.
Вверху -- с коррекцией. То есть из линейного пространства переводим в нелинейный sRGB.
Снизу -- без. То есть пишем цвет в sRGB как есть.
Штука в том, что физически линейный свет должен выглядеть, как наверху.
![c1a4i_shot0000](https://user-images.githubusercontent.com/321361/147517919-d340f6bc-aa0d-485c-a3d3-d0a1b0414016.png)

То есть мне там назад всё нужно разламывать лол. И думать про текстуры, что там с ними и вообще.

**Comment by 0x4E69676874466F78** [comment]
А может нам нужно переводить текстуры в линейное пространство прежде чем лучи пулять по ним и потом гамма-коррекцию в шейдере делать?

**Comment by 0x4E69676874466F78** [comment]
Я думаю делаем ошибку что наваливаем кучу слоёв коррекции каждый из которых маскирует проблемы предыдущего.
Нужно начать с этапа до тонемаппинга, тонемаппинг это когда пересвет и недосветом, то есть большой разброс яркостей которые надо вписать в 8 бит, это можно сказать ещё одна коррекция.
Надо сначала сделать в LDR как надо, чтобы текстуры выглядели правильно.

Убрал "экспозицию", убрал тонемаппинг, выставил `float sampling_light_scale = 0.1;`, убрал гамму и пошёл на test_light3 где только сурфейсы с небом. Смотрю небо что-то тёмное, странно, добавил гамма-коррекцию и опа оно как надо стало.
![изображение](https://user-images.githubusercontent.com/4449851/147709551-b64e6194-edef-4f2b-8f10-f5fd459d6c94.png)
![изображение](https://user-images.githubusercontent.com/4449851/147709570-87fad8f2-52ad-4472-afc7-9f011ab90789.png)
Небо корректное при гамма коррекции как и в GL. Это при том что небо само 
```glsl
payload.emissive = pow(texture(skybox, gl_WorldRayDirectionEXT).rgb, vec3(2.2));
```
Без этого pow оно светлее чем надо. 
Однако если я выпилю гамма-коррекцию:
```glsl
colour = pow(colour, vec3(1. / 2.2));
```
Оно станет опять правильным. Вот так и костыляем костыли.

**Comment by 0x4E69676874466F78** [comment]
Сделал простой тест (отключены гамма-коррекция, тонемаппинг)
```glsl
	colour = base_color.rgb;
	imageStore(dest, pix, vec4(colour, 0.));
```
![изображение](https://user-images.githubusercontent.com/4449851/147710316-e898153c-9f8b-42dc-9fdd-b7a9108f801e.png)
Серый ровный 128 128 128 как и я задавал текстуре.
![изображение](https://user-images.githubusercontent.com/4449851/147710325-a4a4f94e-d18d-4870-94fe-90c8c571f8da.png)
А тут равномерный градиент.

Вопрос: нужно ли преобразовывать текстуры с гамма-коррекцией в линейные (без гамма-коррекции) перед тем как применять освещение чтобы потом их не сломать гамма-коррекцией постобработкой?

**Comment by 0x4E69676874466F78** [comment]
```glsl
float sampling_light_scale = 0.05;
```
```glsl
colour *= pow(base_color.rgb, vec3(2.2));
```
И включил гамма коррекцию на выходе.
Стало (естественно) тормозить (где там до этого момента можно сделать текстуре обратную коррекцию?).
Но! выглядит (почти?) как надо вроде. Почему только пол такой вопрос. Смешивание неправильно?
![изображение](https://user-images.githubusercontent.com/4449851/147711076-f8b442b6-f56d-4344-bcfa-1062b36cbe16.png)
![изображение](https://user-images.githubusercontent.com/4449851/147711107-ef08a8e1-12b7-4ee8-a539-ec6eaeddf626.png)
А вот что если гамма-коррекцию на выходе не сделать:
![изображение](https://user-images.githubusercontent.com/4449851/147711118-d03928b5-5f02-43c3-9ae8-38f95e1f2922.png)
Что мы уже где-то видели...

В другом месте:
![изображение](https://user-images.githubusercontent.com/4449851/147711419-5c7890e1-77a8-4598-8533-beaf9aa420b8.png)
![изображение](https://user-images.githubusercontent.com/4449851/147711426-5efff8bb-3f54-4023-9772-620155f92b45.png)
Прям идеально почти.

Однако:
![изображение](https://user-images.githubusercontent.com/4449851/147711488-862b1de9-e511-4ddf-bb4e-b37763bee6bb.png)
![изображение](https://user-images.githubusercontent.com/4449851/147711494-d55f9f70-ffaa-45bb-a59b-20b963b71706.png)

Это наверное о чём говорил SNMetamorph, pow слишком грубая функция для этого, надо правильно восстанавливать.

**Comment by 0x4E69676874466F78** [comment]
![](https://cdn.discordapp.com/attachments/881757556811395072/925904924536107049/unknown.png)
![](https://cdn.discordapp.com/attachments/881757556811395072/925904924850675872/unknown.png)

**Comment by 0x4E69676874466F78** [comment]
И да, `color /= pdf * 2;` это всё-таки ближе к правде.

**Comment by 0x4E69676874466F78** [comment]
![изображение](https://user-images.githubusercontent.com/4449851/147712440-adde5170-2641-490a-a329-aa037d535383.png)
![изображение](https://user-images.githubusercontent.com/4449851/147712445-7c55df42-9d9f-433b-85e5-c28db7133216.png)

**Comment by w23** [comment]
Посмотрел на это. Наблюдения для debug_gradient.png:
1. У неё в метадате написано, что она sRGB.
2. В сторонних просмотрщиках выглядит линейно (цвет от 0 до 255 распределён равномерно, на половине длины имеем значения около 127, на четвертях от начала и до конца по 63 и 192 соответственно).
3. При конверсии в читаемый глазами P3 PPM цвета тоже выглядят линейно.
4. В движке она тоже выглядит линейно! (кладём в payload.emissive, перекладываем в additive, показываем additive как есть). Видим то же самое распределение цветов.
5. Судя по исходникам, движок делает гамма-коррекцию только для лайтмапов и прочего освещения, текстуры не корректируются.
6. В вулкан-классическом рендере мы текстуры перемножаем на лайтмапы как есть линейно, и пишем на экран тоже как есть, линейно, без коррекции. Это выглядит практически так же, как GL рендер (citation needed).

Предполагаю, что остальные текстуры ведут себя так же (citation needed).

Что это всё значит? :tada: Противоречие! :tada: 
- С одной стороны, текстуры сделаны так, что освещение к ним должно применяться в том же пространстве, что и они сами. То есть они как бы линейные.
- С другой -- гамма-коррекция при выводе будет ломать цвета текстур, т.к. они не делались с расчётом на неё. Т.е. они как бы уже перцептуальные (гамма-откорректированные).

Поэтому у нас и получается, что в одних случаях гамма-коррекция выглядит корректнее, а в других -- некорректнее. Зависит от того, чей именно вклад перцептуально "перевешивает": самой текстуры, или освещения.

Что делать?
.
.
.
.
страдать, конечно.

Вводные: не делать гамма-коррекцию некорректно. Делать её нужно, иначе зачем это всё.
В идеальном мире нужно ремастерить текстуры под гамма коррекцию, чтобы они нормально смешивались с освещением, и нормально же гамма-корректировались после.
Реалистично, думаю, начать просто собирать варианты, где текстуры выглядят ну прям плохо, и ремастерить их в порядке болезненности.

**Comment by w23** [comment]
Ещё очень рыхлая сонная мысль на ночь: а что если представить, что текущий цвет текстуры это максимальный -- тот, который должен быть виден после гамма-преобразвания её при освещении 1. Тогда смешивание её с освещением должно быть хитрым образом нелинейное (каким? что делать с освещением > 1? пойду спать.)

**Comment by 0x4E69676874466F78** [comment]
@w23 
1. Нет там никаких метаданных. Тебе наврали.
![изображение](https://user-images.githubusercontent.com/4449851/147741190-e2a51e91-09db-4c33-be50-929cadefcd97.png)
Однако текстура с гамма-коррекцией.
2. надо наверное говорить линейно для человека (перцептуально / гамма-откорректированно) и в линейном цветовом пространстве или как ещё лучше чтобы не путаться? А то и там и там линейно только линейность разная.
3. Это не понял. В первый раз слышу.
5. Да недавно [был коммит](https://github.com/FWGS/xash3d-fwgs/commit/aa07dab8abbc6fd0f1769c5daf1fe81b7b0c7c2a), я поискал TextureToGamma а его не нашлось, как и нет обратной функции.

> Поэтому у нас и получается, что в одних случаях гамма-коррекция выглядит корректнее, а в других -- некорректнее. Зависит от того, чей именно вклад перцептуально "перевешивает": самой текстуры, или освещения.

В выглядит она некорректнее потому что pow не надо применять ни для перевода в линейное пространство из гамма-скорректированного ни как понимаю для гамма-коррекции. 

> Что делать? страдать, конечно.
Эээ, ты кажется не понял!
Страдать не надо, нужно лишь на входе текстуры из гамма-скорректированного sRGB преобразовать в линейное пространство. И в конце применить корректную гамма-коррекцию.

**Comment by 0x4E69676874466F78** [comment]
Сейчас сделаю тестовый бранч.

**Comment by 0x4E69676874466F78** [comment]
Это (#139) тоже мешает:
![изображение](https://user-images.githubusercontent.com/4449851/147749764-cf8d7ae0-8c12-4849-9daa-0b1eceb38ffe.png)

**Comment by 0x4E69676874466F78** [comment]
Возможно ты и прав на тему страданий, но тут надо все сопутствующие проблемы решить, типа групп сглаживаний и денойзера, 

Вот бранч: https://github.com/w23/xash3d-fwgs/pull/326
`vk_rtx_bounces 1`

Вернул для test_gradient.rad
```
DEBUG_RAD        255 255 255  200

DEBUG_G_E        255 255 255  200
DEBUG_G_R_E      255 255 255  200
DEBUG_G_D_E      255 255 255  200
DEBUG_G_D_R_E    255 255 255  200
DEBUG_GC_E       255 255 255  200
DEBUG_GC_R_E     255 255 255  200
DEBUG_GC_D_E     255 255 255  200
DEBUG_GC_D_R_E   255 255 255  200
```
![изображение](https://user-images.githubusercontent.com/4449851/147754972-a1cd7b64-7ea0-43b9-aa03-3b4d710000ca.png)
![изображение](https://user-images.githubusercontent.com/4449851/147754984-ffaa5bd5-15f8-4329-a2d6-78d69437b5a5.png)
Смешивание освещения с чёрным какое-то странное. Чёрный начинается с 9 9 9.
![изображение](https://user-images.githubusercontent.com/4449851/147754990-8cb4ad78-eaff-4f15-81c3-81e77e736027.png)
![изображение](https://user-images.githubusercontent.com/4449851/147754992-087ad04c-3556-400f-be5d-3fb684d25ef5.png)
У эммиссив текстур дела получше, но тоже есть проблемы. Перепрыгивает оттенки. 0 1 3 5 6, куда делся 2 и 4?


Люди там мудрят с цветовыми пространствами вообще так: https://github.com/google/filament/blob/4846ccd86d1fdb6de136903dca0e331a3adb4bd1/filament/src/ColorSpace.h

**Comment by 0x4E69676874466F78** [comment]
Возможно ты и прав на тему страданий, но тут надо все сопутствующие проблемы решить, типа групп сглаживаний и денойзера, 

Люди там мудрят с цветовыми пространствами вообще так: https://github.com/google/filament/blob/4846ccd86d1fdb6de136903dca0e331a3adb4bd1/filament/src/ColorSpace.h

А пока я сделал кривой бранч для экспериментов: https://github.com/w23/xash3d-fwgs/pull/326

**Comment by 0x4E69676874466F78** [comment]
Ясно что если без всяких коррекций вывести base_color.rgb в color и  мы получим текстуры с гаммакоррекцией.
Не ясно как мы должны с ними работать.
Из продвижения по проблеме стало ясно что для правильной гамма-коррекции надо использовать более точную функцию, однако мои надежды на неё разрушились в прах, я-то думал что это решил проблему убитых тёмных оттенков, а нет.

**Comment by 0x4E69676874466F78** [comment]
Дополнительную пелену даёт `colour += speculour;`

**Comment by 0x4E69676874466F78** [comment]
Ошибка наступает где-то около `colour *= base_color.rgb;` когда я комментирую я вижу размытый результат но там тёмные оттенки не убиты.

**Comment by 0x4E69676874466F78** [comment]
Это оказалось что прямое освещение и баунсы отличаются по даваемой картинке..

**Comment by 0x4E69676874466F78** [comment]
Для более точной отладки рекомендую выключать денойзер (например KERNEL_SIZE = 1), а то он тоже вносит свои небольшие но искажения.

**Comment by 0x4E69676874466F78** [comment]
https://github.com/w23/xash3d-fwgs/issues/321#issuecomment-1002823638 тут на самом деле надо не pdf делить а `ldiffuse *= color / 2;` и возможно спекуляр (не тестировал).
Сделал в своём бранче примерный вид какой должен быть. Спекуляр выпилил до починки групп сглаживаний. Денойзер тоже пока заглушил.
Буду на этом делать rad файлы сейчас. 
Думаю для корректного освещения ещё не хватает групп сглаживаний и рассеивания у точечных источников света.

![изображение](https://user-images.githubusercontent.com/4449851/147767354-119c7ed1-30d7-45f4-b5f6-29420bc65761.png)
![изображение](https://user-images.githubusercontent.com/4449851/147767367-c14c0b43-d6b6-4346-80ea-710c9c6aedbe.png)

![изображение](https://user-images.githubusercontent.com/4449851/147767504-240e3879-3af5-4356-b659-9cc005a0a08b.png)
![изображение](https://user-images.githubusercontent.com/4449851/147767531-4912f9f5-aa50-4906-91fc-127f38b5279e.png)

![изображение](https://user-images.githubusercontent.com/4449851/147767685-a2aa729d-3199-44ea-884a-d25f75a8e515.png)
![изображение](https://user-images.githubusercontent.com/4449851/147767701-7c34e8a4-08bf-4e2c-ae49-e4084ad83b9f.png)

![изображение](https://user-images.githubusercontent.com/4449851/147767889-15cc1601-cbb7-4b43-8dff-3d6aa5b52286.png)
![изображение](https://user-images.githubusercontent.com/4449851/147767849-c6528d11-8099-4640-b9ff-242dfebf8847.png)

**Comment by MaxG2D** [comment]
That is looking way more accurate! :1st_place_medal:

**Comment by 0x4E69676874466F78** [comment]
@MaxG2D да, спасибо. 👌 
Так как я выключил спекуляр от материалов тоже пришлось временно отказаться.

**Comment by 0x4E69676874466F78** [comment]
Оказалось всё равно нужно `color /= pdf * 2;`

**Comment by 0x4E69676874466F78** [comment]
При текущем подходе для аддитиве нужно переводить текстуры в линейное пространство, это 100%. 
Все текстуры в халфе уже с гамма-коррекцией, включая те материалы что я готовил (я тогда не думал о всех этих пространствах и делал как на глаз так и в игре).
При попытке наложить ещё одну гамма-коррекцию происходит очевидная чушь, но только в случае с additive, потому что путь emissive текстур отличается от base_color. 
На base_color действует лучевое освещение которое чудным образом уже как будто делает преобразование в линейное пространство или для такого подхода оно и не нужно?
На emissive (дополнительно) линейно kusok.emissive оказывает влияние.
Это ты должен сам лучше понимать, ты же писал эту пускалку лучей, как они там смешиваются с base_color.

Не используй пока aces_tonemap, он с причудами, пока reinhard наш выбор (но в начале можно и без тонемаппера вообще), потом отладим можно будет другие тонемаперы нормально прикрутить.
Перед тем как использовать тонемаппер нам нужна ещё автоэкспозиция типа такой https://bruop.github.io/exposure/

**Comment by 0x4E69676874466F78** [comment]
И так ответ на твой вопрос чем отличается base_color от additive (emissive текстур).
И заодно ответ на мой вопрос почему терялись оттенки при преобразовании base_color текстур в линейное пространство, а для additive не терялись.

У base_color путь довольно сложный связанный с логикой лучей, всеми этими баунсами.
Можно очень грубо упростить до:
```glsl
colour += scale * imageLoad(src_diffuse_gi, p).rgb;
colour *= base_color.rgb;
```
Без второго умножения на base_color будет мыло. Сегодня [выше писал](https://github.com/w23/xash3d-fwgs/issues/321#issuecomment-1003064058) что там чего-то картинка отличалась, а это не просто так.
У additive в других недрах есть всякая своя логика, но допустим можно свести к:
```
out_additive = payload_opaque.emissive + additive;
colour += imageLoad(src_additive, pix).rgb;
```
То есть у нас здесь никаких умножений не происходит, а просто плюсуем.
Но это тупой ответ, а более сложный в том что умножением ты делаешь подобие SRGBtoLINEAR, ты же умножаешь базовый цвет на самого себя! Делаешь грубейшее быстрое приближение (аппроксимацию). 

Поэтому собственно всё так похоже на правду, но только для base_color.

**Comment by 0x4E69676874466F78** [comment]
Все текстуры у нас sRGB с гамма-коррекцией.
Таким образом правильно должно быть так:
1. на месте sampleTexture(tex_index, texture_uv, uv_lods) или texture(skybox, gl_WorldRayDirectionEXT).rgb нам нужно это обернуть sRGB_OECF то есть преобразовать в линейное пространство. С additive это делается проще простого. Поправлю у себя в следующем коммите этот момент.
2. Поправить работу лучей так чтобы они это учитывали. Как? Пока ещё не понял. Сейчас там делается умножение мыльных лучей на чёткую текстуру и тем самым делается преобразование в линейное пространство, только это по сути делается весьма своеобразно (мне кажется это криво, как минимум преобразование в линейное пространство должно быть не таким примитивным).
3. В конце просто делаем правильную гамма-коррекцию через OECF_sRGB(colour);

У взрослых дядь эти функции называются ещё EOTF_sRGB и OETF_sRGB.

**Comment by 0x4E69676874466F78** [comment]
Думаю это связано с  #262

**Comment by 0x4E69676874466F78** [comment]
#597 думаю стоит связать если вдруг кто-то это тут читать будет.

**Comment by 0x4E69676874466F78** [comment]
Я кстати забыл резюмировать своё мнение:
Если мы имеем дело с уменьшением картинки нам обязательно нужно делать преобразование в линейном пространстве потому что пиксели наслаиваются-перемножаются.
Если мы имеем дело с увеличением картинки нам нужно делать это обязательно в sRGB пространстве, чтобы сохранить структурность картинки, при этом мы никакие пиксели не перемножаем и артефакта их наслаивания нет.
