### ISSUE TITLE
Error: Too many emissive surfaces found: 256; on c1a0c.bsp

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#329]
В этом месте:
![изображение](https://user-images.githubusercontent.com/4449851/147970621-02f3e09d-4ccf-49dc-9387-852bc4c1a445.png)
Из-за этого лампа настроенная через патч не светится.

Кстати, один из тормозов там от `+0~LIGHT6A       150 5   5    25000` эти красные лампочки, 
![изображение](https://user-images.githubusercontent.com/4449851/147972138-2142b163-2ecb-43b8-8bab-d0cc16a92ece.png)
у каждой как минимум 6 сторон и ты похоже не кулишь заднюю сторону.
![изображение](https://user-images.githubusercontent.com/4449851/147972111-e5900e97-00d2-48b4-80e0-268ab02a8bcf.png)
Их в этом месте 4 штуки 24 поверхности получается.
Как вариант могу выключить свечение от них и повесить через патчи лампочки, но это будет не очень физически корректно.

**Comment by 0x4E69676874466F78** [comment]
И ещё, парсить логи на предмет количества светящихся текстур бесполезно, там всегда по одной строчке вне зависимости от числа поверхностей.

**Comment by 0x4E69676874466F78** [comment]
То же самое в лифте дальше.

**Comment by w23** [comment]
Такие поверхности только руками выпатчивать. Код сборки источников света ничего не знает и не может знать про то, как там какие плоскости ориентированы относительно остальной карты, поэтому добавляет их все.

**Comment by 0x4E69676874466F78** [comment]
@w23 а мы никак не можем их кулить? они же прижаты к стене. Bspguy такую геометрию как-то кулит.

**Comment by 0x4E69676874466F78** [comment]
Ещё вопрос 256 это прям максимум или мы можем больше?

**Comment by w23** [comment]
> @w23 а мы никак не можем их кулить? они же прижаты к стене. Bspguy такую геометрию как-то кулит.

Это нужно, чтобы код сборки источников света знал об окружающей геометрии и задумке автора. Может, можно каким-то образом перебрать все поверхности, и если источник света слишком близко к какой-либо из них (насколько близко?), то отсекать.


> Ещё вопрос 256 это прям максимум или мы можем больше?

Это ограничение текущего кода, исходя из соображений `uin8_t` и ожидания, что если их больше, то, наверное, будем тормозить! Формат поменять можно, и можно сделать их произвольно много. Вопрос в том, что будет с производительностью, если их придётся перебирать сильно больше.

**Comment by 0x4E69676874466F78** [comment]
> насколько близко

Они прям впритык, но мне сложно измерить, bpguy их вообще не даёт выбрать, но по ощущением они впритык или около 0.01, это в рамках DebugVec0 который показывает bspguy.

> Вопрос в том, что будет с производительностью, если их придётся перебирать сильно больше.

В данный момент мы имеем ситуацию что света нет где он должен быть. Можно поменять формат и оценить масштаб тормозов.

**Comment by 0x4E69676874466F78** [comment]
> Max number of polygon lights 256 reached

Если сходить на c2a3c там спамит этим и на винде это сильно тормозит, кстати если переключиться на классический то спам не пропадает, и игра всё равно тормозит.

**Comment by 0x4E69676874466F78** [comment]
Что касается куллинга задних частей то как показала практика они в среднем не сильно помогают в производительности зато ломают часть важных эффектов где внутренние и задние части куллить не надо..

**Comment by 0x4E69676874466F78** [comment]
Флуд `Error: vk: Max number of polygon lights 256 reached` на c1a4b,

**Comment by 0x4E69676874466F78** [comment]
Что-то произошло и больше данного предупреждения я вовсе не вижу. Определить корректность сложно.

**Comment by w23** [comment]
Нет, этот лимит поднимается только изменением формата.
Но мы какое-то время назад приглушали всякую избыточную ругань, может быть как раз оно.

**Comment by 0x4E69676874466F78** [comment]
>  Но мы какое-то время назад приглушали всякую избыточную ругань, может быть как раз оно.

Оно не должно было совсем выключиться, должно было троттлиться, а я в логах не вижу даже 1 сообщения.

**Comment by w23** [comment]
It's nowhere near the limit on c1a0c (103 of 256)
