### ISSUE TITLE
Need test map with various rendering entities

### ISSUE THREAD

**Issue by w23** [w23/xash3d-fwgs#33]
For faster renderer iteration roundtrip a test map would be nice that contains all (or most common/reasonable) variants/permutations of rendered entities. For example:
- all types of beams
- all types of particles/sprites
- all types of studio models (normal, float, chrome)
- many brush types
- all of the above with all possible rendering modes and fx

The idea here is to be able to quickly compare reference GL renderer to underdeveloped VK renderer. It could be even automated to produce and compare screenshots offline.

**Comment by 0x4E69676874466F78** [comment]
[test_shaders.zip](https://github.com/w23/xash3d-fwgs/files/7026259/test_shaders.zip)
This is alpha version and needs some specifies for a better experience of development.
Notes: 
1. due to the limitations of the engine (errors: nummodels == MAX_MAP_MODELS; WARNING: MakeNodePortal:new portal was clipped away from node x9999 and broken map; ReadSurfs: 9108 > numplanes; ZHLT does not protect against errors - Host_Error: ED_AllocEdict: no free edicts (max is 900), MAX_MAP_ENTITIES, etc), I had to make two maps, they are connected by a "teleport" (there is an bad player orientation currently because info_landmark/trigger_changelevel is sucks). In the future, there may be 3 or more maps. To overcome the error "no free edicts" I had to add ```edicts "1500"``` to \valve\liblist.gam
2. I use generally env_laser for beams as it is easier to design, except "experimental rotare beam unit" and  "animate ring beam" (they are env_beam). env_beam requires many extra entities and manipulations for the same effect.
3. Room1 has a designation (number) RenderFX mode from through decals for beam lasers. Left to right 0: "Normal", 1: "Slow Pulse", 2: "Fast Pulse", 3: "Slow Wide Pulse", 4: "Fast Wide Pulse", 9: "Slow Strobe", 10: "Fast Strobe", 11: "Faster Strobe", 12: "Slow Flicker", 13: "Fast Flicker", 5: "Slow Fade Away", 6: "Fast Fade Away", 7: "Slow Become Solid", 8: "Fast Become Solid", 14: "Constant Glow", 15: "Distort", 16: "Hologram (Distort + fade)"
4. Room2 contains 3 levels (floor) of models for different amount (-1: "0", 1: "128", 2: "255"); and 4 models per Render mode (0: "Normal", 1: "Color", 2: "Texture", 3: "Glow", 4: "Solid", 5: "Additive"), there are special brushes for testing the imposition of different modes. No RenderFX modes yet. FX color set red to anymodel.
5. Room3 has a many similar structure to Room2, but 1 sprite used. Sprite scale is 0.5, framerate 60. Groups (columns) by FX Color: 255,255,255; 255,0,0;. Each row is RenderFX mode (see 3 item). There are also brush tests. No signed with decal yet.
6. Room4 a set of trash, but there is a ring beam and there is a demo of a bug (hlgoldsrc affected too) with Render mode texture and sprites (if you walk and look around the reflection sprites). Additive mode is not affected by this bug (second half of the room).

Map source included.

**Comment by 0x4E69676874466F78** [comment]
The previous map can be considered a stress test or very advanced for render.
I am making a new simpler map (or group of maps) with a new more isolated approach.
So far, basically only 1 room is ready for brushes (but it may need refactoring).
[test_shaders_basic.zip](https://github.com/w23/xash3d-fwgs/files/7027701/test_shaders_basic.zip)
There are two "boxes" in the room, one with a regular texture and the other with a texture with transparency. No RenderFX modes. Three groups with 0, 128, 255 amount. Between them are the normal brushes as separators. Each group has 6 Render modes (feft to right) and 5 FX Color modes (up to down) ie blue, green, red, white, black.

**Comment by 0x4E69676874466F78** [comment]
New test maps: [test_maps.zip](https://github.com/w23/xash3d-fwgs/files/7085970/test_maps.zip)
There is a bug with changing levels, models transiting to other rooms after moving from room 4 and you can suddenly get stuck in the wall after moving (random bug). info_landmark is sucks.

**Comment by 0x4E69676874466F78** [comment]
Исправил проблемы выше. Добавил карту со светом.
[test_maps2.zip](https://github.com/w23/xash3d-fwgs/files/7117373/test_maps2.zip)

**Comment by 0x4E69676874466F78** [comment]
[test_maps3.zip](https://github.com/w23/xash3d-fwgs/files/7146687/test_maps3.zip)
Поправил мелкие корявости на карте со светом, добавил там динамические источники света (один который недокументированный, другой в качестве теста который будет корректно работать только на лучах), добавил порталы для удобства, скомпилировал стандартным qrad (а не hlrad как было до этого).
Добавил начальную версию карты с брашами воды (предстоит ещё поместить в воду браши и спрайты), в конце карты есть сложный браш для теста (потом его перенесу в отдельную карту со сложными эффектами).
Прочие мелкие исправления.

**Comment by 0x4E69676874466F78** [comment]
Забыл упомянуть: 
Добавлен источник света под углом с маленьким объектом чтобы можно было отладить отбрасываемую с него тень.
У основного источника который светит прямо добавлен браш перекрывающий одну из сторон, тоже можно увидеть тень на потолке. Убрана полоска обозначающая силу света (1024) вместо неё теперь узенький блок, но как показывает практика свечение бьёт ещё дальше и этот блок просто бесполезная условность.
Добавлена новая текстура 512х512 для оценки юнитов, жирные линии это границы 512х512, ~~линии потоньше 256х256~~, самые тонкие линии это 128х128, большие синие квадратики это 64х64, красные 32х32, зелёные 16х16.

Заметил мелкие проблемы:
Новая текстура оказалась не заменена самым свежим вариантом где видно деление на 256х256.
Съехал точечный источник света (light) внутри "тубы", он расположен не по центру.
Исправлю завтра, и заодно добавлю простые бимы на карту со спрайтами.

**Comment by 0x4E69676874466F78** [comment]
[test_maps4.zip](https://github.com/w23/xash3d-fwgs/files/7148035/test_maps4.zip)
Исправлены проблемы выше.

На карте test_sprite добавлены бимы (env_beam), так как у них нет режимов отрисовки каждый бим занимает целую строку. С ring beam есть баг у xash ( https://github.com/FWGS/xash3d-fwgs/issues/614 ), если они расположены вдали от игрока и при запуске карты включаются то при подходе к ним их не видно, поэтому я добавил кнопку для их включения (надо два раза нажать, т.к. фактически они включены и их надо выключить чтобы показать снова).

На карте test_light добавлены ещё два режима динамического света, один (`effects` 4) заметно более яркий и дальше бьёт, другой (`effects` 64) похож на прошлый, но не мерцает. Поставил тот что не мерцает ближайшим от игрока (где раньше был мерцающий).
Добавлены кнопки для остановки их движения.

На карте test_brush2 преобразована вторая ванночка где добавлены отметки верхней и нижней грани, разница 8 юнитов. 
Чтобы нижнюю увидеть надо присесть рядом.

Добавлен lights.rad где добавлен `+0~WHITE        255 255 255 100` который шёл с хаммером (а valve.rad шёл с worldcraft вроде). 

### Подробнее про динамические источники света
Особенность этих источников света что они просвечивают всё на своём пути и наверное эту логику повторять не нужно, хотя в конечном итоге потребуется тестирование карты с ракетой с точки зрения художественного исполнения.
Как изменять яркость источников я не понял, `effects` 8 светит тусклее чем  `effects` 4, а `effects` 64 вроде как `effects` 8 только не мерцает.
Нашёл список этих режимов: https://github.com/FWGS/xash3d-fwgs/blob/ddc4d7666874ce050d33ba6cc5781f08180776c5/common/const.h#L107
А вот где они применяются: https://github.com/FWGS/xash3d-fwgs/blob/ddc4d7666874ce050d33ba6cc5781f08180776c5/engine/client/cl_tent.c#L2699
Похоже хардкод яркости. Причём один из эффектов EF_BRIGHTLIGHT имеет двойное назначение и используется ещё для фонарика, там есть грязная проверка что если энтити игрок то эффект имеет константный радиус (нет мерцания), а если энтити какая-то другая то радус в рамках диапазона (есть мерцание). Так что нужно учитывать эту особенность при реализации фонарика чтобы не получить непредвиденных последствий (=непонятных багов) на уровне с ракетой. По хорошему логика применяемая к игроку должна быть отдельно (то есть заведён новый режим отдельно для энтити игрока).

**Comment by 0x4E69676874466F78** [comment]
[test_light.zip](https://github.com/w23/xash3d-fwgs/files/7163180/test_light.zip)
Добавлены маленькие emissive источники света для теста.

**Comment by 0x4E69676874466F78** [comment]
[test_brush2.zip](https://github.com/w23/xash3d-fwgs/files/7173669/test_brush2.zip)
Сбоку есть телепорт в другую комнату с текстурами воды. Там просто лежат браши с разными текстурами без func_ энтити.

**Comment by 0x4E69676874466F78** [comment]
[test_maps6.zip](https://github.com/w23/xash3d-fwgs/files/7190490/test_maps6.zip)

**Comment by 0x4E69676874466F78** [comment]
[test_maps7.zip](https://github.com/w23/xash3d-fwgs/files/7211959/test_maps7.zip)
На test_light:
Поправил надоедливый телепорт.
Добавил солдат где видно вспышки от стрельбы, они слева вдалеке огороженная комнатка.
Добавил test_sky_simple с простым небом.

**Comment by 0x4E69676874466F78** [comment]
[test_maps8.zip](https://github.com/w23/xash3d-fwgs/files/7252978/test_maps8.zip)
Добавил тестовую карту комнат с поправленными текстурами.

**Comment by 0x4E69676874466F78** [comment]
[test_maps9.zip](https://github.com/w23/xash3d-fwgs/files/7273671/test_maps9.zip)
На test_light:
1. поменял цвет свечения у светящихся текстур в мелких коробах.
2. добавил две модели тетраэдра (нужно извлечь не только maps, но и models), вроде там разное сглаживание групп указано (1 и 32), разница в игре по крайней мере есть, но пока я ковырялся в глючном milkshape и там с группами сглаживаний проблема и возможно группы сглаживаний на самом деле не те, тем не менее на этих моделях видно почему такая срань с чернотой и это должно помочь в отладке.

**Comment by 0x4E69676874466F78** [comment]
[test_maps11.zip](https://github.com/w23/xash3d-fwgs/files/7360808/test_maps11.zip)
1. Изменена тестовая текстура на серый оттенок (пока перекомпилена только test_light т.к. именно для неё это сделано чтобы лучше видеть пересвет).
2. На test_light:
2.1 Добавлена комната со спотлайтами, там внутри ещё есть миникомнатка и вторым пространством к ней, ну а второй этаж с лестницей и так виден (там сполтайт с силой 1000).
2.2. В комнате с поинтами теперь они идут первым рядом, а светящиеся текстуры вторым.

**Comment by 0x4E69676874466F78** [comment]
[test_maps12.zip](https://github.com/w23/xash3d-fwgs/files/7382347/test_maps12.zip)
На test_light добавлены комнаты (где поинтлайты проход) сравнения R G B с R G B V поинтлайтов.

**Comment by 0x4E69676874466F78** [comment]
[test_maps15.zip](https://github.com/w23/xash3d-fwgs/files/7461914/test_maps15.zip)
1. добавлены test_light2, test_light3. Игрок находится внутри комнаты скайбокса и можно видеть комнаты снизу. Сразу советую сделать `sv_maxspeed 1000`.
2. на test_light2 спереди поинты, сзади споты, справа сурфейсы, слева отладочная херня (коробка с другой текстурой и коробка с поинтом и спотом рядом); там по 4 коробки (128³, 256³, 512³, 1024³) на столбец (из этих 4 коробок) с силой света (20, 25, 50, 200, 500, 750, 1000), цвет внутри 255 255 128; у сурфейсов задана сила 1000, 5000, 100000; сама текстура коробок серый цвет (128 128 128), но в wally цвет почему-то превратился в 161 161 161 а в редакторе 147 147 147, кто-то где-то лажает или какая-то магия. Но всё равно видно что курад ограничен цветом текстуры! Он чутка обрезает до 128 128 116 вместо ожидаемых 128 128 128. 
3. я достиг предела `lightdata        [variable]    2036256/2097152  (97.1%)VERY FULL!` поэтому для детального теста поверхностей сделан test_light3.
4. test_light3 с сурфейсами тест отдельный на разный размер светящихся поверхностей с разной силой внутри тех же коробок. Сила там 10, 50, 100, 500, 1000, 5000, 50000, 100000. Достиг максимального значения поверхностей, пришлось резать карту.

**Comment by 0x4E69676874466F78** [comment]
[test_maps16.zip](https://github.com/w23/xash3d-fwgs/files/7489229/test_maps16.zip)
1. На test_brush2 добавлены дополнительные поверхности и пояснения к ним, достаточно подойти и покажет что это и с какой текстурой.
2. На test_light выключена крутилка по умолчанию, добавлена кнопка чтобы её включить.
3. На test_sprite исправлен косяк где браш почему-то съехал.

**Comment by 0x4E69676874466F78** [comment]
[test_maps17.zip](https://github.com/w23/xash3d-fwgs/files/7534139/test_maps17.zip)
1. Добавлена test_material первая версия с материалами, хотел сделать больше удобств (сразу кучу объектов с разными материалами с наличием или без того или иного компонента), но пока так, для начала сойдёт, тем более можно просто комментировать компоненты и на лету перезагружая материалы смотреть как смотрится. 
2. Розовые (маджента) поверхности это где подразумевается замена материалами.
3. Структура материалов сделана согласно https://github.com/w23/xash3d-fwgs/issues/155
4. Формат материалов как-то так: https://github.com/w23/xash3d-fwgs/issues/156
3. На всякий случай нормали сохранены в обоих форматах (directx и opengl), но дальше надо определиться в каком формате делать, совместимее всего в directx (и только он поддерживается в ModLab), но это не столь принципиально (можно в Materialize пересохранить).

**Comment by 0x4E69676874466F78** [comment]
[test_maps18.zip](https://github.com/w23/xash3d-fwgs/files/7542226/test_maps18.zip)
1. добавил запрошенные объекты и текстуры для теста нормалей
2. добавил ещё некоторые штуки.
2. обновил структуру pbr согласно последним изменениям.
3. c2a3_gar3 обновлён (он имеет нестандартный размер в силу некоторых проблем тайлинга и чисто для отладки) теперь он debug_c2a3_gar3, потом может ещё раз обновлю его когда разберусь с тайлингом.

**Comment by 0x4E69676874466F78** [comment]
[test_maps18.1.zip](https://github.com/w23/xash3d-fwgs/files/7550205/test_maps18.1.zip)
Исправил неверное положение текстур для нормалей, проглядел.

**Comment by 0x4E69676874466F78** [comment]
[test_maps19.zip](https://github.com/w23/xash3d-fwgs/files/7571618/test_maps19.zip)

**Comment by 0x4E69676874466F78** [comment]
[test_maps20.zip](https://github.com/w23/xash3d-fwgs/files/7576561/test_maps20.zip)
Обновлены немного материалы. Есть материал для теста нормалей на инопланетной пушке.
Решётка на c1a0 сделана отладочной и должны быть золотой, но basemap сломан и текстура не заменяется.

**Comment by 0x4E69676874466F78** [comment]
[test_maps20.zip](https://github.com/w23/xash3d-fwgs/files/7576578/test_maps20.zip)
1. Изменена структура директорий, старую pbr папку лучше удалить.
2. Обновлены немного материалы. Есть материал для теста нормалей на инопланетной пушке

**Comment by 0x4E69676874466F78** [comment]
[test_maps+materials22.zip](https://github.com/w23/xash3d-fwgs/files/7695857/test_maps%2Bmaterials22.zip)

* Добавлены новые материалы для оружий от меня и материалы для LAB_CRT от 5FB5
* Добавлена test_gradient для теста соответствия гаммы как base_color так и emissive (потом добавлю туда ещё спрайты)
* На test_light, test_material мелкие изменения.

**Comment by 0x4E69676874466F78** [comment]
[test_maps+materials23.zip](https://github.com/w23/xash3d-fwgs/files/7741213/test_maps%2Bmaterials23.zip)
* Добавлена потерянная test_light4.
* Добавлена test_light5 для теста светящихся текстур, сразу смотреть в test_light5.rad
* Добавлены разные тестовые карты test_sky*, test_brush*
* Какие-то мелкие изменения в материалах, пока не на что смотреть.

**Comment by 0x4E69676874466F78** [comment]
[test_maps24.zip](https://github.com/w23/xash3d-fwgs/files/7781263/test_maps24.zip)
* Переделана test_light2, теперь там более удобные градации и свет в коробках белый, так же расположение сделано более удобным (удивляюсь что ранее я сделал такую почти бесполезную карту, видимо тогда был не совсем в себе).
* Добавлены для более точкой отладки test_light2_nobounce и test_light3_nobounce собранные с параметром `-bounce 0` то есть без отскоков.
* Добавлена test_random_tiling для теста случайных тайловых текстур из набора (требуется сделать мерж с мастером).

**Comment by w23** [comment]
Слушай, а где всякие test_shaders карты? Тут их нет

**Comment by 0x4E69676874466F78** [comment]
Повторюсь здесь:
test_shaders это старая карта одна из первых, которая была забракована за слишком большую сложность, поэтому в последующие архивы она не попала, но всё ещё есть тут в этом комментарии https://github.com/w23/xash3d-fwgs/issues/33#issuecomment-903181446
Я уже несколько дней хочу сделать хранилище для карт куда всё положить, но пока руки не дошли.

**Comment by 0x4E69676874466F78** [comment]
Переехало сюда https://github.com/0x4E69676874466F78/test_maps_for_hlrtx_project

**Comment by 0x4E69676874466F78** [comment]
Можно закрыть наверное?

**Comment by w23** [comment]
Ага. Если нам понадобятся какие-то ещё нетривиальные карты для тестирования, можно будет создать новые тематические ишьи с меткой соответствующей.

**Comment by 0x4E69676874466F78** [comment]
@w23 лучше сразу в репе раз уж я её создал: https://github.com/0x4E69676874466F78/test_maps_for_hlrtx_project

**Comment by 0x4E69676874466F78** [comment]
Ты открепить забыл.

**Comment by w23** [comment]
Хмм. Надо либо закрепу оставить -- это полезное. Либо в ридми засунуть.
Вообще надо ридми обновить, там протухло всё давно
