### ISSUE TITLE
patch: emissive texture color is not apply by patch

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#330]
Сначала заметил что если текстура уже есть в рад файле, то при попытке перезаписать её свет яркость и цвет текстуры остаётся от рад файла. Однако всё оказалось хуже, патч никак не влияет на цвет и яркость текстуры, только на светимость лучами.
![изображение](https://user-images.githubusercontent.com/4449851/147978352-a534ab02-f9eb-4ba0-b662-bd92a17b601d.png)
Например так должно светить зелёным (c1a1):
```
{
"_xvk_surface_id" "1183" // +0~DRKMTLS1      205 0   0    6000
"_light" "0 205  0 10000"
}
```
Но видно что текстуре всё равно:
![изображение](https://user-images.githubusercontent.com/4449851/147978462-6635dd18-9776-47da-b429-0d96e7fde946.png)

**Comment by 0x4E69676874466F78** [comment]
Есть более явные места где это будет бросаться в глаза. Так что лучше исправить проблему не сильно затягивая с ней.

**Comment by w23** [comment]
Исправил в https://github.com/w23/xash3d-fwgs/pull/457

По иронии, так сказать, конкретно в случае скриншотов выше это не чинит, потому что там родная текстура красная, и если ей назначить зелёный эмиссив, оно перемножает (1, 0, 0) на (0, 1, 0) и получает черноту. Но светится зелёным при этом, да. Потому что эмиссив текстур у нас пока нет.

**Comment by 0x4E69676874466F78** [comment]
@w23 ну мы умеем менять текстуры, естественно если бы мне реально потребовалось там зелёное свечение я бы сменил текстуру. Зелёный свет чисто для показа проблемы, я просто не подумал что там что-то может пойти не так. Там вообще нужна анимационная красная текстура. В оригинале там мигание сделано через лампочку, что в случае лучей явно не катит.
Спасибо.
