### ISSUE TITLE
patch: not replaced texture

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#332]
Пытаюсь исправить недоработку вальвы здесь:
![изображение](https://user-images.githubusercontent.com/4449851/148119680-cc5e15cd-ebfb-47a7-aba9-283139a382ce.png)
Чтобы было так (как на следующей карте):
![изображение](https://user-images.githubusercontent.com/4449851/148119740-7e4b8598-6126-4ae6-9de4-8e3d8182fc1d.png)

Но не получается. Возможно потому что в этой карте нигде не задействуется эта текстура, на другие текстуры которые присутствуют на карте замена происходит.

c1a1f.bsp.patch
```
{ // fix wrong texture
"_xvk_surface_id" "2362 2363 2352 2351 2386 2389 2562 2563 1002 1003 1013 1014"
"_xvk_texture" "crete4_flr03"
}
```

**Comment by w23** [comment]
Ооххх. Это трудно сделать, потому что текстуры с такими именами мы загружаем не сами. Они прилетают из движка уже готовенькие. В лучшем случае тут только копипастить код загрузки текстур из движка. Хз, насколько это трудно и возможно ли вообще.

**Comment by 0x4E69676874466F78** [comment]
Ок, тогда попробую через собственные материалы патчить.

**Comment by w23** [comment]
Получается через собственные материалы?
В теории большинство текстур с простыми именами должно быть можно загрузить через новый материал. Только у нас поддержки этого скорее всего нет. Типа, надо будет к ним приделывать какой-то особый символ в начале, типа `@crete4_flr03`, чтобы он пытался такую текстуру загрузить, если её нет. Либо можно вообще не приделывать такой символ, а пытаться её загрузить всегда.

**Comment by 0x4E69676874466F78** [comment]
> Получается через собственные материалы?

Я забыл и уже не помню как я тогда хотел это патчить, щас в голову приходит только что возможно я думал заменить текстуру для конкретно этой карты, но это тогда затронет возможно другие поверхности если там есть такая текстура, в общем бред.

> В теории большинство текстур с простыми именами должно быть можно загрузить через новый материал

Надо попробовать. Прям щас я не в состоянии, завтра проверю.

**Comment by 0x4E69676874466F78** [comment]
Это немного через жопу, но работает. Остались проблемы только запатчить текстурные координаты ну и анимационные тектуры свои.
