### ISSUE TITLE
patch: change texture coordinates

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#333]
Если на c1a1f попытаться сменить текстуру на правильную, там новая текстура не выглядит корректно:
![изображение](https://user-images.githubusercontent.com/4449851/148121700-bee16072-bbd2-402e-92c7-cf1f668847f1.png)

Требуется задать вручную текстурные коодинаты. Неплохо бы иметь то же самое что в редакторах:
![изображение](https://user-images.githubusercontent.com/4449851/148121606-4c390fd5-0f11-4df1-ad02-6d7bea2ccaee.png)
Кнопки не в счёт, они просто автоматически задают нужные настройки. 

Это не приоритетная задача, но для полноценного патчинга не помешает.

c1a1f.bsp.patch
```
{
"_xvk_surface_id" "999 1010" // LITEPANEL1
"_xvk_texture" "+0LAB1_W6"
}
```

**Comment by 0x4E69676874466F78** [comment]
Запатчил здесь текстуру:
![Image](https://user-images.githubusercontent.com/4449851/226111627-100ac728-6c46-46f6-9369-341aa0affde7.png)
Но как видно текстурные коодинаты оказались неверные.

**Comment by 0x4E69676874466F78** [comment]
В таком же формате как в картах идут. Это я могу по крайней мере прогнозировать через bspguy.

**Comment by w23** [comment]
Если в таком же формате, как в карте, то там сразу закодированы все возможные трансформации, в т.ч. и повороты. Только руками это патчить без внешних тулов крайне тяжело, потому что это абстрактные попугаи. Если bspguy такое может (или можно через редактор карт какой), то ок.

Если делать варианты (2), то там патчинг без внешнего более "естественный" что ли -- можно числа визуально подгонять итерациями к искомому виду в понятных терминах "сдвинь вправо-влево-вверх-вниз-растяни-поверни".

**Comment by 0x4E69676874466F78** [comment]
Ишью ты закрыл, но ты сделал только масштабирование, а сдвиги? или сдвигать надо тоже через масштабирование? какой там формат сейчас?

Кстати там в пуллреквести попало лишненькое https://github.com/w23/xash3d-fwgs/pull/503/files#diff-399b3eb03c5dd3a3acddc9129d8ca5ff0ee0bf130dd3f62d85fbbc40bdd10f68

**Comment by w23** [comment]
> Ишью ты закрыл, но ты сделал только масштабирование, а сдвиги? или сдвигать надо тоже через масштабирование? какой там формат сейчас?

И масштабирование, и сдвиги.
```
_xvk_soffscale "<offset> <scale>" // S
_xvk_toffscale "<offset> <scale>" // T
```


> Кстати там в пуллреквести попало лишненькое https://github.com/w23/xash3d-fwgs/pull/503/files#diff-399b3eb03c5dd3a3acddc9129d8ca5ff0ee0bf130dd3f62d85fbbc40bdd10f68

Это похожа на косяк гита. Это было вкоммичено ещё на прошлом стриме.

**Comment by 0x4E69676874466F78** [comment]
> И масштабирование, и сдвиги.

Понял, спасибо!
