### ISSUE TITLE
patch: origin for brush-entity (func_wall and etc)

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#335]
Есть такая проблема:
![изображение](https://user-images.githubusercontent.com/4449851/148458635-4fa31191-cd47-4134-9f1b-77b82af55c3e.png)
Часть энтити-брашей втоплены внутрь геометрии и там происходит постоянное сражений граней. Это в игре заметно. 
Так как это энити хотелось бы сделать что-то вроде:
c1a1c.bsp.patch
```
{
"_xvk_ent_id" "36"
"origin" "0 0 -7"
}
```
Где в origin относительные координаты от начальных. Так bspguy показывает когда пытаюсь этот браш сдвинуть.
![изображение](https://user-images.githubusercontent.com/4449851/148458963-a3eecfc3-ecf0-4ad8-8e63-149ced38dafb.png)

**Comment by 0x4E69676874466F78** [comment]
Эта же проблема есть ещё в самом начале на c1a0a в лифте. Там тоже можно сдвинуть браши (на -0.1) и станет хорошо:
![изображение](https://user-images.githubusercontent.com/4449851/148679151-f681df96-0ead-453e-a9db-5ab553f92576.png)

**Comment by w23** [comment]
С `_xvk_ent_id` проблема -- оно начинает ходить по ногам патчинга источников света, и надо рефакторить.
Дело в том, что у меня там энтити разнесены по типам, с совершенно разными кишками и всем. Патчинг по индексу подразумевает несколько другой подход и некоторый рефакторинг, который может ещё и источники света затронуть.
Текущая схема с `model` тоже, в общем, так себе. Но она костылём простая в исполнении на текущем коде.

Зарефакторить на полный список энтит с произвольными патчами было бы угарно, там сразу универсально можно было бы патчить что угодно единым способом. Но это опять сколько-то часов-стримов работы.
