### ISSUE TITLE
materials: `"roughness_map"` and `"metal_map"` need to be correct by `"roughness"` and `"metalness"` values

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#342]
Сейчас я могу подправить `"basecolor_map"` через `"base_color"` что очень удобно, но для `"roughness_map"` и `"metal_map"` коррекция через  `"roughness"` и `"metalness"` не работает и для ускорения разработки материалов было бы полезно.

**Comment by w23** [comment]
Или ты хочешь, чтобы значения из текстур умножались на скалярное значение? Не уверен, что это должно так работать.

**Comment by 0x4E69676874466F78** [comment]
@w23 
> Или ты хочешь, чтобы значения из текстур умножались на скалярное значение? Не уверен, что это должно так работать.

Да я хочу поверх roughness_map/metal_map умножить/разделить через  roughness/metalness ровно так же как сейчас делаю это с basecolor_map через base_color.
Сложно на глаз понять как должно выглядеть а по сто раз пересохранять и перезагружать текстуры неудобно.
А так я просто подберу правильное значение на лету, а потом через скрипт запатчу текстуру.

**Comment by w23** [comment]
Хорошо, могу сделать тупо умножение. Это, кстати, немного и упростит шейдерный код (но неясно, ускорит ли).

Про нормали надо почитать. Мне с ходу неясно, тривиальная там математика (можно ли так же тупо умножить), или надо что умнее делать.

**Comment by w23** [comment]
По нормалям вроде так же просто всё. Можно умножить XY конечной нормали, а Z нормализовать.
