### ISSUE TITLE
Broken shadows from alpha surfaces

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#360]
![изображение](https://user-images.githubusercontent.com/4449851/171160593-980b1f37-eda2-41ac-a209-c00252991f91.png)
Если при этом вызвать vk_rtx_reload то чудным образом оно становится корректным:
![изображение](https://user-images.githubusercontent.com/4449851/171160784-c7c446f8-04a5-47a4-bb83-c4e7521bd8d6.png)

**Comment by w23** [comment]
Исправлено в https://github.com/w23/xash3d-fwgs/commit/18a7c61505f25be5bda093847ae0d644bc7b5aa8
