### ISSUE TITLE
Slow performance and cannot allocate dynamic geometry buffer 

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#364]
```
Error: Cannot allocate dynamic geometry buffer for 46 vertices (3680 bytes) and 132 indices (264 bytes)
Error: Cannot allocate geometry for beam
```
Save file: [save.zip](https://github.com/w23/xash3d-fwgs/files/8839050/save.zip)

GL:
![изображение](https://user-images.githubusercontent.com/4449851/172027771-bbb38ea6-5930-40c2-abdc-467d609a10c1.png)
VK (мерцает):
![изображение](https://user-images.githubusercontent.com/4449851/172027797-713e39f9-193a-4e59-a681-387b558c7992.png)
![изображение](https://user-images.githubusercontent.com/4449851/172027814-d9bb1167-2785-4b6e-9ebd-ae7335db6137.png)
VK-RTX (тоже мерцает):
![изображение](https://user-images.githubusercontent.com/4449851/172027883-916ac3be-6b65-4ab3-a05a-65087d5ad647.png)

**Comment by 0x4E69676874466F78** [comment]
Тормоза наверное из-за спама в консоль, но это не отменяет проблему с мерцанием и аллокацией. 
Если смержишься с мастером то по идее тормоза консоли должны пройти на винде.

**Comment by w23** [comment]
Even after explicitly looking at per-submodel bones transformation it is detected as dynamic: `Submodel 3/3: name="tripmine_boned_world", is_dynamic=1`

**Comment by w23** [comment]
The common case of exploding boxes and meat has been solved in https://github.com/w23/xash3d-fwgs/pull/543/commits/9ff4961124fd8c30eb369953efdb1bb62cb41ca0

This particular tripmine one seems as a weird and rare edge case. It's not often that we get hundreds of tripmines visible in a frame.

**Comment by w23** [comment]
One possible way to address this would be to detect dynamic-ness of the model early: compute `g_studio.verts` before asking for a cached submodel, and use some kind of a (float-precision-fuzzy) hash of verts to get a submodel that is numerically the same.

It is a rather uncomfortable thing that currently feels like an extra.

**Comment by 0x4E69676874466F78** [comment]
Сейчас подвисает совсем немного только на лучах, в традиционном подвисов нет.

Если я буду повторять взрыв, т.е. загружаться с сохранения, прыгать, умирать, опять загружаться и опять прыгать-умирать то с попытки 3 я словлю такую ошибку:
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/c74521d3-047a-4f5e-99c2-90adfa7dd338)
Если нажать повтор:
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/5e9944e1-97ba-427d-b4ba-93cdfc3963f3)
