### ISSUE TITLE
Crash on AMD when ALT+TAB

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#365]
В полном экране если сделать альт-таб то упадёт с генерик-ошибкой:
```
Program: \build\amd64-debug-prefix\ref_vk.dll
File: \ref_vk\profiler.h
Line: 147

Expression: g_aprof.stack_depth == 0
```
а в логе:
```
Host_MultiError: Error \ref_vk\vk_swapchain.c:247 present_result failed (-1000255000): VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT
```
Амд, винда.

С нвидией ошибки нет!

https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkAcquireFullScreenExclusiveModeEXT.html#_description

Но мы такое расширение не используем насколько я понимаю.
В чате предположили что: SDL может юзает если не с NO_API собирались

**Дополнение:**
> Почему перед рекрейэтом свапчейна не ждете девайса? Буффер может использоваться как бы
> У тебя N изображений связанных со SwapChain, ты захватываешь только некоторое изображение из SwapChaiin-а(и то оно может быть не готово, так как соотвествующий семафор еще не в сигнальном состоянии), а в остальные изображения то GPU еще может писать до этого момента 
Нужно дождаться пока все операции  на GPU выполнятся

> Так же надо обработать юзкейс с  VK_ERROR_SURFACE_LOST_KHR 
> Пересоздать surface

**Comment by EliteCombineSoldier** [comment]
the issue isnt exclusive to AMD cards
Windows 10
RTX 3070
516.40 Drivers
The game also crashes when alt-tabbing
however it doesnt always crash
![‏‏لقطة الشاشة (715)](https://user-images.githubusercontent.com/51729858/174662271-399396db-e4dd-4ff0-8dd1-bc6f13a03fbb.png)

**Comment by 0x4E69676874466F78** [comment]
@EliteCombineSoldier is it in the better-sampling-passes-parallel branch?

**Comment by w23** [comment]
We do both:
- wait for device idle before destroying and recreating swapchain
- recreate swapchain on surface lost (and a few other supposedly transient errors)

**Comment by w23** [comment]
> the issue isnt exclusive to AMD cards Windows 10 RTX 3070 516.40 Drivers The game also crashes when alt-tabbing however it doesnt always crash ![‏‏لقطة الشاشة (715)](https://user-images.githubusercontent.com/51729858/174662271-399396db-e4dd-4ff0-8dd1-bc6f13a03fbb.png)

Can you provide logs? It's not clear what the exact cause of this call stack.
