### ISSUE TITLE
Crash when load test_shaders_room3 with RTX (assert instance_offset != ALO_ALLOC_FAILED)

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#366]
Это старая карта, но раньше она работала. Падает только если включены лучи или включить их на лету на этой карте.
Сама карта: [test_shaders_room3.zip](https://github.com/w23/xash3d-fwgs/files/8985538/test_shaders_room3.zip)

**Comment by w23** [comment]
Это из-за `MAX_ACCELS 1024`. Если их поднять до 2048, карта работает.
Но т.к. утверждается, что раньше карта работала, мы поменяли что-то в стратегии аллокации бласин.
По идее нужно распилить MAX_ACCELS на две вещи: макс количество бласин в тласине, и общее макс количество бласин предсобранных и в кеше.
