### ISSUE TITLE
Crash when I throw a grenade (or fire a rocket) on test_surf4_test

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#367]
Карта [test_surf4_test.zip](https://github.com/w23/xash3d-fwgs/files/8985561/test_surf4_test.zip)

![изображение](https://user-images.githubusercontent.com/4449851/175790385-6e1724b2-07fa-4f46-877e-3871cd4bb46e.png)

Не важно с лучами или без.

**Comment by w23** [comment]
На карте нет `mleaf_t->compressed_vis`. Нужно добавлять всё во все листочки, считая всё видимым.
