### ISSUE TITLE
Flickering squares on skybox after loading some maps

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#368]
Если зайти на test_light, потыкать лучи туда сюда, увидеть там кривые спрайты, потом зайти на [test_shaders.zip](https://github.com/w23/xash3d-fwgs/files/8985578/test_shaders.zip) в комнату с моделями (2 комната), там войти в область тормозов (место где много геометрии в воздухе), тоже потыкать лучи туда-сюда (оставить режим без лучей) и потом загрузиться на карту [test_surf4_test.zip](https://github.com/w23/xash3d-fwgs/files/8985561/test_surf4_test.zip) то под лучами на небе можно увидеть мерцание белых и чёрных квадратиков.

https://user-images.githubusercontent.com/4449851/175790587-9c0455e4-0dc1-4a93-9f2f-d3803506dc30.mp4

**Comment by 0x4E69676874466F78** [comment]
[testbw.zip](https://github.com/w23/xash3d-fwgs/files/9077890/testbw.zip)
Демка с глюком. Но на данный момент она падает. 
```
Error: SDL_GL_SetSwapInterval: No OpenGL context has been made current
loading models\scientist01.mdl
Mem_Alloc: out of memory (alloc at A:\xash3d-fwgs\engine\client\cl_demo.c:956)
```
https://github.com/FWGS/xash3d-fwgs/issues/634

**Comment by 0x4E69676874466F78** [comment]
[testbwquad.zip](https://github.com/w23/xash3d-fwgs/files/9123220/testbwquad.zip)
Вот быстрая демка. `playdemo testbwquad` быстро перекинет на баг.

**Comment by w23** [comment]
У меня воспроизводится сразу с `+map test_surf4_test` безо всяких подпрыгиваний до.

**Comment by 0x4E69676874466F78** [comment]
@w23 повезло. Проверил у себя квадратиков так нет. В общем где-то опять тайминги?

**Comment by 0x4E69676874466F78** [comment]
на c1a1f:

https://user-images.githubusercontent.com/4449851/180624050-776ce66e-1b32-43f8-afd4-1f3371b09912.mp4

**Comment by 0x4E69676874466F78** [comment]
Ошибки нет если внутри vk_framectl.c выставить submit( cmdbuf, true ); у R_EndFrame.

**Comment by 0x4E69676874466F78** [comment]
Закрываю ибо бага больше нет.
