### ISSUE TITLE
Crashes inside nv drivers when creating the first ray tracing pipeline when built against VulkanSDK-1.3.216

### ISSUE THREAD

**Issue by w23** [w23/xash3d-fwgs#379]
No idea why.
Turning validation on or off doesn't help.
Runs fine with `vk_only 1`.
Haven't tried other 1.3 versions.
Drivers are latest.
No info about similar problems on teh internets.

The only thing that helps is downgrading Vulkan SDK to 1.2.198.

Things to check:
- [ ] other 1.3 versions
- [ ] diff compiled shaders
- [ ] diff vk headers
- [ ] diff compiled assembly.

**Comment by 0x4E69676874466F78** [comment]
Не подтверждаю.
Что сделал:
```
set VULKAN_SDK=A:\VulkanSDK-1.3.216.0
waf configure -8 -T debug --sdl2=a:\SDL2-2.0.16 --prefix=A:\hl1dev\xash3d-fwgs-win32-0.20
```
Далее waf install и оно чёто не смогло пересобраться, удалил папку build и заново сделал строчки выше, на сей раз waf install (который делает waf build когда потребуется сам) прошёл успешно.
Далее запустил:
```
set VK_LAYER_PATH=A:\VulkanSDK-1.3.216.0\Bin
::set VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_api_dump;VK_LAYER_KHRONOS_validation
set VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation
start /b A:\hl1dev\xash3d-fwgs-win32-0.20\xash3d.exe -ref vk -vkdebug -rtx -dev 2 -console -log +load quick > NUL
```
И всё работает нормально.

**Comment by w23** [comment]
:thinking: У меня дрова посвежее, вроде.

**Comment by 0x4E69676874466F78** [comment]
Ну да, есть новее, 516.59. Быстро они их клепают.
Ну попробуй поставить это
https://www.nvidia.com/content/DriverDownload-March2009/confirmation.php?url=/Windows/512.95/512.95-desktop-win10-win11-64bit-international-dch-whql.exe&lang=ru&type=TITAN

**Comment by w23** [comment]
Даунгрейдить дрова такое себе, особенно с учётом того, что мы их апали намедни, чтобы починить всякое.
Но разобраться надо, да, и это одна из гипотез.

**Comment by 0x4E69676874466F78** [comment]
@w23 эти должны работать с лампочками. Нужно проверить имеют ли здесь место дрова или нет.

**Comment by w23** [comment]
Короче если взять шейдеры, собранные сдк 1.2, то всё работает.
Если заменять их по одному, то начинает падать с момента подставления нового `ray_primary.rchit.spv`

**Comment by w23** [comment]
Там есть вот такое :thinking::
```
--- broken.spv  2022-07-26 23:35:34.092030909 -0700
+++ working.spv 2022-07-26 23:35:44.550181856 -0700
@@ -772,6 +772,7 @@
                OpDecorate %616 NonUniform
                OpDecorate %618 NonUniform
                OpDecorate %619 NonUniform
+               OpDecorate %payload Location 0
                OpDecorate %skybox DescriptorSet 0
                OpDecorate %skybox Binding 7
                OpDecorate %MAX_POINT_LIGHTS SpecId 0
```

И ещё пачка дебажных появилось в сломаном:
```
@@ -903,7 +904,6 @@
 %LIGHT_GRID_CELL_SIZE = OpSpecConstant %float 128
 %MAX_LIGHT_CLUSTERS = OpSpecConstant %uint 262144
 %SBT_RECORD_SIZE = OpSpecConstant %uint 32
-               OpLine %1 26 11
        %main = OpFunction %void None %10
          %12 = OpLabel
      %geom_0 = OpVariable %_ptr_Function_Geometry Function
...
```

**Comment by w23** [comment]
```https://github.com/KhronosGroup/glslang issues 2736``` :thinking: :thinking:
Если руками удалить `Location` из работающего, то оно продолжает работать.

**Comment by w23** [comment]
Если убрать `-g` у `glslc`, то собранные шейдеры вновь работают.

Ссанина.

**Comment by 0x4E69676874466F78** [comment]
@w23 драйвер-то проверил? может реально самый свежий косячный. Бывает и такое тоже.

**Comment by w23** [comment]
В том, что это именно драйвер косячный, сомнений практически нет -- он не должен падать вне зависимости от того, каким мусором его кормят.
Вопрос в том, что делать-то теперь. По-хорошему, надо соорудить минимальное репро, разобраться, куда отправлять в нвидию, и отправить.
А пока они там разбираются, надо либо откатить драйвер, как ты предлагаешь, либо, как предлагаю я, убрать дебаг-инфо и заниматься чем занимаюсь, ибо я пока не лажу в шейдеры. Нагонять лажу в шейдеры я будут позже, а там, гляди, либо драйвер починят, либо изменения в шейдерах скроют проблему.

**Comment by 0x4E69676874466F78** [comment]
> По-хорошему, надо соорудить минимальное репро, разобраться, куда отправлять в нвидию, и отправить.

Означает минус стрим?)

**Comment by w23** [comment]
Очень давно не воспроизводилось. Наверное, починили.
