### ISSUE TITLE
Uploading light data from staging is extremely slow

### ISSUE THREAD

**Issue by w23** [w23/xash3d-fwgs#385]
Uploading the entire light grid data (~100-200Mb) each frame is _surprisingly_ slow. Takes about 40ms.
Need to upload only the essentials. E.g. track which light clusters were made dirty (and possibly light index subranges) and upload only those.

**Comment by 0x4E69676874466F78** [comment]
Не забудь в биосе попробовать сделать 8x шину.

**Comment by w23** [comment]
уже посмотрел на это всё. материнка в принципе только 4х на втором слоте тянет, так в мануале написано.
Надо было апаться на тредриппер всё же
