### ISSUE TITLE
ASSERT R_VkMeatpipeLoad fails on spirv-parsing branch

### ISSUE THREAD

**Issue by Valor760** [w23/xash3d-fwgs#394]
Если выкачать чистый spirv-parsing бранч, то происходит краш на R_VkMeatpipeLoad, потому что не может загрузить файл "rt.meat". По поиску нигде в директории его нет.

 - Branch: spirv-parsing
 - OS - Windows 10 x64
 - Asus TUF RTX 3070
 - Driver version: 517.48
![image](https://user-images.githubusercontent.com/31585840/197381053-9d86d7e5-36e5-4bfe-bbbc-e5532713d8d8.png)

Как я понял, этот файл создается с помощью sebastian.py файла в ref_vk директории, но проблема, что нет нигде нет .spv шейдеров и скрипт падает с ошибкой 
Exception: Cannot load shader ray_primary.rgen.spv

**Comment by 0x4E69676874466F78** [comment]
`python.exe sebastian.py --path ..\build\ref_vk\shaders .\rt.json --output путь_до_халфы\valve\rt.meat`

**Comment by Valor760** [comment]
@0x4E69676874466F78 
Да, почти так и делал(аутпут только не указывал в valve диру). Проблема, что у меня нет нигде .spv файлов в шейдерах, которые просит скрипт.
![image](https://user-images.githubusercontent.com/31585840/197409741-8b86d94d-e58d-4e90-9b5f-4bedba78fa62.png)

**Comment by 0x4E69676874466F78** [comment]
@Valor760 я же тебе написал путь, эти файлы лежат не в той папке шейдеров которую ты указал.

**Comment by Valor760** [comment]
@0x4E69676874466F78 Все, понял, тогда полный путь будет(если брать чистый бранч и по гайду билда на wiki)
`python sebastian.py .\rt.json --path ..\build\amd64-debug\ref_vk\shaders --output ..\build\amd64-debug-prefix\valve\rt.meat
`
Все равно было бы неплохо этот скрипт вшить в условный ваф, чтобы автоматом, но можно на потом оставить)

**Comment by 0x4E69676874466F78** [comment]
@Valor760 да просто ещё не успел он это в Waf запихнуть.
