### ISSUE TITLE
Use `r_speeds` to output performace stats

### ISSUE THREAD

**Issue by w23** [w23/xash3d-fwgs#412]
Look at what happens with gl renderer, and make it consistent if it makes sense.

See:
- https://github.com/w23/xash3d-fwgs/pull/477#issuecomment-1475320475
- https://github.com/w23/xash3d-fwgs/pull/477#issuecomment-1475326649
- https://github.com/w23/xash3d-fwgs/pull/477#issuecomment-1475333666

**Comment by 0x4E69676874466F78** [comment]
Да нужно переместить 
https://github.com/w23/xash3d-fwgs/blob/d6d9011dcc92ea33eac41dc649de5bd7b7c514d4/ref/vk/vk_framectl.c#L189-L205
в r_speeds, а то после обновы движка там починили Con_NPrintf который теперь отображается всегда, даже без -dev.
