### ISSUE TITLE
Some sprites should not be depth tested

### ISSUE THREAD

**Issue by w23** [w23/xash3d-fwgs#414]
Vk renderer (both rt and traditional) depth tests all the sprites. But some of them should not be tested, e.g. PYLESOS weapon hit location.

**Comment by 0x4E69676874466F78** [comment]
> PYLESOS 

egon, Gluon Gun, Quantum Destabilizer
Глюонная пушка (или квантовый дестабилизатор)

**Comment by 0x4E69676874466F78** [comment]
Связано  #150, #171, #293
Я бы волуметрики в форме искажённой (под спрайт) сферы рисовал из 2д спрайтов, но не умею пока.

**Comment by 0x4E69676874466F78** [comment]
Связано #442

**Comment by w23** [comment]
В текущей формулировке это можно сказать сделано. Просвечивающие партиклы идут как `kRenderGlow`, и в традиционном рендере они, как и положено, без depth-test. А в лучах для них пока костыль в виде soft particle overshoot луча.

**Comment by w23** [comment]
@0x4E69676874466F78  Это сделано, или не очень?

**Comment by 0x4E69676874466F78** [comment]
@w23 в этой формулировке https://github.com/w23/xash3d-fwgs/issues/414#issuecomment-1454504327 сделано.
