### ISSUE TITLE
Remove func_wall entities from dynamic geometry and fix detect for dynamic geometry 

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#415]
Энтити func_wall в принципе не могут двигаться, это статическая геометрия во всех возможных случаях.
Но мало просто убрать их из списка динамической геометрии, они вскрывают другую проблему: даже если геометрия находится в статическом состоянии (например func_rotating выключенная по умолчанию) эта геометрия всё равно считается динамической и для неё считаются кластеры. В идеале обнаруживать движется или не движется эта геометрия на самом деле.

**Comment by 0x4E69676874466F78** [comment]
@LifeKILLED предлагает как вариант по матрицам отслеживать. В идеале конечно так.

В самой халфе существет множество типов динамически энтити, не все из них всегда динамические.
`func_wall` как уже писалось это не динамическая энтити, но в редких случаях она может иметь эффекты рендера, например быть полупрозрачной и пульсировать (менять полупрозрачность до непрозрачной), то есть надо проверять наличие ключа renderfx если он 0 или его нет это 100% статическая непрозрачная геометрия. Хорошая карта для проверки `crossfire` (23МБ кластеров).
`func_wall_toggle` то же самое что `func_wall` только геометрия может по триггеру быть выключена или включена.
`func_breakable` почти то же самое что и `func_wall_toggle` за исключением того что эта энтити имеет здоровье и по его истечению уничтожается безвозвратно, на `c4a3` характерный пример где эти энтити выжирают 12МБ кластеров.
`func_rotating` имеет флаг активации, если выключено это то же самое что и `func_wall`, может быть включён через кнопку или по событию.
`func_plat` и `func_platrot` поведение как у `func_rotating`.
`func_conveyor` аналогично `func_rotating`.
`func_train` сложный случай, хотя оно похоже на `func_rotating` у него есть энтити `path_corner` где есть параметр wait (сколько стоять на данном участке) по идее `func_train` в этот момент будет работать, но фактически будет стоять.
`func_button` может быть динамична только в момент нажатия (вдавливается).
`func_door`, `func_door_rotating` аналогично `func_button`.

Учитываются же только видимые браши?

Микрооптимизации:
`func_water` если `WaveHeight` 0 (или отсутствует?) то это скорее статическая геометрия.

**Comment by 0x4E69676874466F78** [comment]
Пример на crossfire:
![image](https://user-images.githubusercontent.com/4449851/222921791-8c5092f4-feea-4c34-99cd-d2d340c8520c.png)
![image](https://user-images.githubusercontent.com/4449851/222921806-c873b815-3a2d-4336-8dc7-9bfac521a51a.png)
![image](https://user-images.githubusercontent.com/4449851/222922192-0e3c548e-d8bb-45ca-88f2-970e0b2bfb7c.png)

**Comment by 0x4E69676874466F78** [comment]
К какой информацией обладает рендер о динамической геометрии? Если там есть указатель на модель (какой-то числовой идентификатор), то всё довольно просто. Все func_wall перечислены в списке энтитей карты, у каждого func_wall есть ключ под названием "model" внутри модел как раз содержится номер модели, типа `*35`, почему там звёздочка не знаю, но она у всех `func_` с геометрией есть сколько я их видел.

**Comment by w23** [comment]
Начал копать сюда (из соображений #335). Штука в том, что рендер грузит модели, а не энтити. Модели содержат только геометрию, и ничего не знают о том, как она будет использоваться (прозрачно, непрозрачно, статически, не статически, с эффектам, без, и т.п.). Энтити прилетают в рендер снаружи, и рендер заранее про них не знает ничего.
Можно попробовать взрефакторнуть всё так, чтобы некоторым набором эвристик собирать энтити в статичные-с-точки-зрения-рендера фиговины. Подумаю, как

**Comment by w23** [comment]
И да:
- на уровне движка вся информация о том, какого типа был порождающий `func_`, утеряна. По крайней мере в прямом виде. Возможно, её можно как-то восстановить по флажкам, но хз.
- с точки зрения рендера все энтити потенциально динамические, как в смысле могут удаляться-создаваться, так и в смысле, что их кишочки (эффекты, трансформация, ...) могут меняться как попало.

**Comment by 0x4E69676874466F78** [comment]
@w23 ты же достаёшь лампочки из карты, откуда у тебя доступ к их ключам? Вот ровно через это ты смотришь в список энтитей, находишь те где есть ключи "model" это будут как раз брашевые энтити, в значении ключа будет ид модели, по идее он должен совпадать с идом/индексом внутренней структуры геометрии. Ну можешь отфильтровать динамику по ключу "classname", именно там лежит тип энтити. Для начала тебе надо обратить внимание на "func_wall", они гарантированно статические.

**Comment by 0x4E69676874466F78** [comment]
> Может ли несколько энтитей ссылаться на одну и ту же модель?

Я не уверен на 100% но на 99(,9)% нет. Если взять test_light у меня там есть пирамидки, все пирамидки func_rotating и каждая имеет разную модель. Специально сделал их func_wall сейчас, результат тот же самый. Проверил в 3 компиляторах, даже самом современном-продвинутом (primext). Никто никакие оптимизации не делает.

> Может ли модель использоваться в func_wall и не func_wall контекстах?

Это продолжение предыдущего вопроса? типа могут ли разные по функционалу энтити ссылаться на одну модель? Учитывая предудыщий ответ это исключено.
