### ISSUE TITLE
Behind the map is garbage with pieces from the sky

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#416]
За картой где чернота рисуется мусор от скайбокса, раньше кажется такого не было. Это не приоритетно совсем, но чтобы не потерялось оставлю здесь заметку.
![image](https://user-images.githubusercontent.com/4449851/216788245-6aa4f37b-7eec-457f-ad29-afa62cf4d5dc.png)

**Comment by w23** [comment]
гипотеза: payload.prev_pos_t не зануляется.
