### ISSUE TITLE
Broken vk_rtx_reload_rad & vk_rtx_reload_patches cvars

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#417]
Не оказывают влияния.

**Comment by 0x4E69676874466F78** [comment]
Ну оно понятно почему:
https://github.com/w23/xash3d-fwgs/blob/d6d9011dcc92ea33eac41dc649de5bd7b7c514d4/ref/vk/vk_rtx.c#L143-L147
https://github.com/w23/xash3d-fwgs/blob/d6d9011dcc92ea33eac41dc649de5bd7b7c514d4/ref/vk/vk_scene.c#L64-L76

**Comment by w23** [comment]
Я немного забыл уже, как патчами пользоваться. Напиши, пожалуйста, как над этим быстро итерировать. Типа:
1. Открываем карту c53f45q, идём туда-то
2. Открываем патч файл такой-то
3. Правим строчку такую-то
4. Релоадим, должны увидеть результат

**Comment by 0x4E69676874466F78** [comment]
1. открываем карту test_material видим всё по стандартному
2. создаём файл \valve\luchiki\maps\test_material.bsp.patch внутри указываем 
```
{
"_xvk_ent_id" "244" 
"_light" "255 0 0 1000"
}
{
"_xvk_surface_id" "277 279 363"
"_light" "0 0 0 0"
}
```
3. перезагружаемся и видим что вдали лампочка стала красно сильно светить, а вблизи 3 лампы перестали светить (правда их текстуры по прежнему светлые, это баг #330 ).
