### ISSUE TITLE
Models flicker if you stand in a certain place

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#422]
Загружаемся в test_model, подходим справа к стенке у дверного проёма и наблюдаем мерцание моделей в additive режиме отрисовки. При этом ещё и тормозить начинает. 
В консоли много ошибок 
`Cannot allocate geometry for studio model/sprite quad`

https://user-images.githubusercontent.com/4449851/218747017-19abec8d-8c00-438f-a496-8c5afc27415a.mp4

**Comment by 0x4E69676874466F78** [comment]
Здесь всё по прежнему как было.

**Comment by w23** [comment]
Захачить это можно тупым увеличением лимтов на размеры буфера геометрии, кеша бласин, и т.д. Но оно будет тормозить.

По-нормальному это решается только полным рефакторингом того, как мы обходимся со студийными/динамическими моделями и бласинами. Нужно привязывать бласины к конкретным энтитям, иметь предсобранные бласины для всех студийных моделей, которые будем использовать, и т.д.

**Comment by w23** [comment]
Fixed in #537 537
