### ISSUE TITLE
Wrong matrices

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#426]
Видно дверях и лифтах. Например хорошо видно на с1a0a.
Кажется это больше касается вертикальных движений.

https://user-images.githubusercontent.com/4449851/219014835-f8f954dd-364a-4418-b82b-0bc52707ff00.mp4

**Comment by w23** [comment]
Исправление есть: надо prev_matrix перед загрузкой транспонировать из row-major в col-maror.

**Comment by w23** [comment]
fixed in https://github.com/w23/xash3d-fwgs/commit/149dc7cadef78840ae3fafccc53e5ff59df90dcc
