### ISSUE TITLE
Full support RAD files

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#43]
There is currently no support for rad files by map name (overlapping lights.rad list).
See #37 Qrad Textures

**Comment by w23** [comment]
There is now :)
At least it tries to load rad files by map name `rad/maps/<mapname>.bsp.rad`
It does not seem to find texture names correctly though.

Need to read qrad sources to figure out how it's supposed to do that.

**Comment by 0x4E69676874466F78** [comment]
@w23 
> Need to read qrad sources to figure out how it's supposed to do that.
https://github.com/ValveSoftware/halflife/blob/master/utils/qrad/qrad.c#L1509

**Comment by 0x4E69676874466F78** [comment]
https://github.com/w23/xash3d-fwgs/commit/2b2552cd72297ea682a7b3bdbd8f42c168972d19
Close?

**Comment by w23** [comment]
We might need to try this too: https://csm.dev/threads/radius-osveschenija-v-half-life.38602/#post-935193 (thanks @lewa-j)

**Comment by 0x4E69676874466F78** [comment]
And https://github.com/ValveSoftware/halflife/blob/master/utils/qrad/lightmap.c#L1020

**Comment by w23** [comment]
I think we mostly got RADs interpretation correct.
Last thing we need to fix here is quality-of-life:
- [ ] loading rads from `rad/<mapname>.rad` instead of `rad/maps/<mapname>.bsp.rad`
