### ISSUE TITLE
Sprite lerping does not work in ray traced mode

### ISSUE THREAD

**Issue by w23** [w23/xash3d-fwgs#433]
lerping means drawing 2 coplanar quads blended on top of each other, which is not something ray tracing can do easily for all blending modes

lerping is disabled for now

**Comment by 0x4E69676874466F78** [comment]
На ЦП заранее посчитать промежуточные кадры и добавить их в поток?
Условно говоря было у спрайта 10 кадров, мы пошли в материалы, посмотрели какому кадру какая новая текстура соответствует (если они есть, это к тому чтобы не сломать логику патчинга материалов), далее из этих 10 текстур построить промежуточные и вставить в массив кадров. В теории наверное это можно и на видяхе посчитать в компуте шейдере, но с ЦП проще в плане предрасчёта.

**Comment by 0x4E69676874466F78** [comment]
Султим вообще забил на смешивание, кто бы сомневался.

**Comment by w23** [comment]
Я забыл, а в каких местах это можно наблюдать?

**Comment by 0x4E69676874466F78** [comment]
> Я забыл, а в каких местах это можно наблюдать?

В любых где анимированные спрайты. Например идёшь на test_light и смотришь на порталы.
Вот тебе пример с GL и VK для сравнения чтобы было понятно:

https://github.com/w23/xash3d-fwgs/assets/4449851/80486dad-0633-4a4e-96ea-116f31abfe1b
