### ISSUE TITLE
The starting black screen is broken

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#435]
Проявляется на картах c0a0, c4a1. На секунду появляется карта как есть, только потом стартует чёрный экран с плавным затуханием.

**Comment by 0x4E69676874466F78** [comment]
Больше не наблюдается, но когда это было исправлено?

**Comment by w23** [comment]
Может, с триапи+прозрачностью?
Я так никогда на это и не смотрел, поэтому сложно сказать. Можно забисектить, чтобы добыть какое-то понимание.

**Comment by 0x4E69676874466F78** [comment]
Ладно я завтра поищу коммит после которого оно починилось.

**Comment by 0x4E69676874466F78** [comment]
Исправлено похоже в E260 #529 где-то в этом районе.
