### ISSUE TITLE
Crash when I blast the barrels fast on c2a5

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#450]
Беру гауспушку и быстро шмаляю по бочкам, происходит вылет:
![image](https://user-images.githubusercontent.com/4449851/222113042-73508b64-2727-435e-ad70-4fb55ca5debd.png)
Отладчик даже не хочет запускаться 😎

**Comment by 0x4E69676874466F78** [comment]
c2a5e выходим наружу и гарантировано падаем при взрывах.

**Comment by w23** [comment]
Fixed by increasing MAX_ACCELS to 2048

**Comment by 0x4E69676874466F78** [comment]
На бочках больше не валится.
