### ISSUE TITLE
Crash when trying to load c5a1

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#451]
![image](https://user-images.githubusercontent.com/4449851/222122234-7f05d49e-1f25-4f41-9ad6-e660599437b8.png)

**Comment by w23** [comment]
Скорее всего слишком дофига лайт кластеров хочет обновить, не влезает в стейджинг.
Много способов чинить, подумаю.

**Comment by w23** [comment]
Can be fixed by increasing staging buffer size to 128MiB
