### ISSUE TITLE
Blue noise 

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#455]
Пишу чтобы не потерялось.

Пример от @ncuxonaT:
> я нагенерировал себе несколько наборов случайных точек, более-менее равномерно заполняющих квадрат 0-1
одна точка на один кадр, у каждого пикселя оффсет синим шумом
на каждый боунс следующая точка в последовательности
у диффуза и микронормали свой "сид"
я генерировал 100 точек кандидатов обычным рандомом и оставлял одну, наиболее удаленную от всех предыдущих
с хаммерсли и соболем артефакты из-за автокорреляции
с синим шумом выглядит глаже
```
uniform vec2 uRandomDiffuse[bounce_count];    //current frame random numbers

vec2 bluenoise_pixel_offset = texture(texture_noise_blue, fract(gl_FragCoord.xy * 0.00390625)).rg;    //256x256 blue noise texture    

for(int i = 0; i < bounce_count; i++)
{
    vec2 random_diffuse = fract(uRandomDiffuse[i] + bluenoise_pixel_offset);
    vec3 trace_dir = mat3_tbn * random_dir_cosine(random_diffuse);
    ...
}
```

**Comment by w23** [comment]
https://github.com/Calinou/free-blue-noise-textures/tree/master/64_64_64

**Comment by w23** [comment]
Done in #559
