### ISSUE TITLE
Lighting from animation texture doesn't work

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#458]
В c1a1f в комнате с зомби от ноутбука нет никакого освещения.

**Comment by w23** [comment]
Нужно какое-то время чесать репу. Трудно. Варианты, сыро:
I. Для каждой поверхности пробегать по всем текстурам в анимации, и если хотя бы одна из них светит, считать её за динамический источник. При добавлении в текущем кадре, сверять, что она реально светит, и добавлять условно.
II. Научиться для всех polylight динамическому обновлению свечения, как-то связывать с текущей текстурой.
III. не знаю даже

**Comment by 0x4E69676874466F78** [comment]
Что интересно на a2845670021f81cfd72a364367d8885c45b5592b у светящихся анимационных текстур есть окрашивание текстуры, но нет света от неё. Дальше уже и окрашивания нет, но сама текстура меняется. Я немного перепутал и тут по хорошему надо на две задачи разбить.
