### ISSUE TITLE
Render modes for transparency

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#460]
Сейчас всё additive, добавляю чтобы назначить приоритет.
Нужно для денойзера.
Связано #290,  #310

**Comment by w23** [comment]
Ща перед сном сыро накидаю ранних черновик списка вариантов прозрачности, которые нам вообще могут быть нужны:
1. Additive. Тупо всквозную добавляет цвет. Это для всяких вяло светящихся партиклов, бимов и прочего.
2. Subtractive/scattering. Затеняет всё то, что за. Например, дым всякий.
3. Преломляша. Принимает свет с двух сторон: и отражает извне, и преломляет внутрь.

1+2 не самые физически корректные пацаны. Дым, например, должет принимать свет тоже. Делать нормальный объёмный дым это долгая история, пока оставим до лучших времён.

Нужно ещё пройтись по списку рендермодов, и понять, на что из вышеперечисленного они должны мапиться. Возможно, там нет простой линейной истории, и маппинг этот сильно зависит не только от ещё и имени текстуры, но и может требовать исключительного патчинга в конкретных случаях.

По-хорошему, эта информация должна привязываться не к ентити/модели, а к материалу поверхности. Но я сейчас с ходу не вспомню, насколько свободно это связывание, конфликтует ли оно потенциально с анимированными текстурами, и пр.

**Comment by 0x4E69676874466F78** [comment]
> 1+2 не самые физически корректные пацаны. Дым, например, должет принимать свет тоже. Делать нормальный объёмный дым это долгая история, пока оставим до лучших времён.

А как волуметрики будут работать?

**Comment by w23** [comment]
> > 1+2 не самые физически корректные пацаны. Дым, например, должет принимать свет тоже. Делать нормальный объёмный дым это долгая история, пока оставим до лучших времён.
> 
> А как волуметрики будут работать?

Волуметрики как в ку2 и у султима условно простые: глобально одинаковые везде, статичные, и один источник света. Дым же более локальный и динамический, надо репу чесать. Сделать можно, но позже

**Comment by 0x4E69676874466F78** [comment]
> Волуметрики как в ку2 и у султима условно простые: глобально одинаковые везде, статичные, и один источник света. Дым же более локальный и динамический, надо репу чесать. Сделать можно, но позже

Ну мы хотели коробки с ними чтобы их можно ещё было спавнить динамически.

**Comment by w23** [comment]
Ага, но эти все завитушки на чуть попозже.

**Comment by w23** [comment]
В #470 идёт обсуждение формата материалов, который цепляет и этот аспект.
