### ISSUE TITLE
NAN / devided by zero on c1a0c, c1a1a, c1a4b

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#461]
![image](https://user-images.githubusercontent.com/4449851/222711908-7b1eb67d-1a7a-4a89-8f09-8304dec32dd7.png)
![image](https://user-images.githubusercontent.com/4449851/222711936-19641cfd-cff2-476b-a313-7c192340cc9e.png)
![image](https://user-images.githubusercontent.com/4449851/222711969-84723805-2b67-4c01-9174-d2d3ad654c0f.png)
![image](https://user-images.githubusercontent.com/4449851/222712002-5b825781-5a2f-49bf-8e9a-41d5e42d519a.png)

**Comment by w23** [comment]
Когда это началось примерно?

**Comment by 0x4E69676874466F78** [comment]
> Когда это началось примерно?

c5a1343fc698d39e8c828a866d00a13c77a6b2b6 ещё рабочий
3ecd21a25bea9d8fe7873e75687c148ecba8ed66 сломалось

**Comment by 0x4E69676874466F78** [comment]
```
#ifndef RAY_BOUNCE
#define PROJECTED
//#define SOLID
//#define SIMPLE_SOLID
#else
//#define PROJECTED
//#define SOLID
//#define SIMPLE_SOLID
#endif
```
в else нефига, значит getPolygonLightSampleSimple и видимо он и багованный. Сделал для теста #define SIMPLE_SOLID и всё норм.

**Comment by 0x4E69676874466F78** [comment]
Ещё есть желтизна на c4a1a, прыгаем на второй остров и там:


![Image](https://user-images.githubusercontent.com/4449851/226112683-103bc9dd-278f-4420-8eaa-e548c6c15be1.png)

**Comment by 0x4E69676874466F78** [comment]
На c1a4b тоже желтизна.

**Comment by 0x4E69676874466F78** [comment]
На c1a2 это выглядит более локально, без резкого переключения на весь экран:
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/98dc676f-ac0e-415f-8677-de65ef4b262d)
