### ISSUE TITLE
Crash when minimizing a window

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#463]
Просто открываем игру и жмём значок свернуть окно.
![image](https://user-images.githubusercontent.com/4449851/222760244-5bd54248-9aa6-455d-82c8-8d62f31ecd02.png)
> 	XVK_CHECK(vkCreateImage(vk_core.device, &ici, NULL, &image.image));
> Необработанное исключение по адресу 0x00007FFAE18961F7 (nvoglv64.dll) в xash3d.exe: 0xC0000094: Integer division by zero.

**Comment by w23** [comment]
Лол драйвер невидии такой "минимальный размер текстуры 0х0, и максимальный 0х0, делай чё хочешь". Ну я и делаю, а он такой "НЕК! БАБАХ".

Надо, наверное, просто не создавать свопчейн и не рисовать ничего, если там такое. В спеке пока ничего не нашёл, кто им так разрешил.

**Comment by w23** [comment]
Ещё это воспроизводится, если переключать разрешение десктопа.

**Comment by w23** [comment]
Больше не падает-падает, но раздражает валидацию. Всё равно надо чинить.

**Comment by 0x4E69676874466F78** [comment]
Если я выставляю родное разрешение моего экрана, снимаю галку "run in a window" то после альтаба оно грохается.
