### ISSUE TITLE
Texture of func_conveyor stopped moving

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#465]
На test_light текстура на конвейерах застыла.

**Comment by w23** [comment]
Да, это известная фигня. Я хотел отойти от модификации uv в шейдере. Но, если честно, пока непонятно, как лучше. Потому что альтернатива шейдерам, это загрузка uv через стейджинг, то есть сразу это динамика со всеми вытекающими.
