### ISSUE TITLE
Incorrect rendering of the surfsky

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#474]
Идём на de_dust2, нужно бежать на точку B (есть указатели, ближе от терроров) проход прям рядом там.
![image](https://user-images.githubusercontent.com/4449851/223975004-ac493515-adb1-407b-92a7-8433e8840f6c.png)
![image](https://user-images.githubusercontent.com/4449851/223975020-7f25c5aa-8187-4a13-8a02-32975666dbef.png)
GL:
![image](https://user-images.githubusercontent.com/4449851/223975340-ad1cea71-86c5-499d-9c38-d6ac0aa0c6e8.png)

**Comment by w23** [comment]
It seems that "feature" of the vk renderer where it would literally draw sky where SURF_SKY surfaces are found is not a feature, but a bug. It seems that GL renderer just skips SURF_SKY surfaces and doesn't render them at all. And sky is rendered where there's no other geometry.

Another hypothesis is that there's some other flag besides SURF_SKY which prevents such surfaces to be rendered.
Verify this.

**Comment by w23** [comment]
Пока промежуточный итог таков (см комменты в #572): 
- Не рисовать небо на месте `SURF_DRAWSKY` мы не можем, т.к. иначе на лучах становится видна невидимая геометрия. В GL рендере она прячется то за PVS, то за far plane.
- Автоматически вырезать именно лишние небеса не представляется возможным -- нет чётких однозначных критериев.
- Можно попробовать использовать текущий механизм удаления поверхностей.
  - Пока, сломан, нужно чинить: #577

**Comment by 0x4E69676874466F78** [comment]
Возможная эвристика:
Не удалять поверхность с SURF_DRAWSKY если за SURF_DRAWSKY пустота или другой SURF_DRAWSKY.
Удалять поверхность с SURF_DRAWSKY если за SURF_DRAWSKY обычная геометрия и сам SURF_DRAWSKY окружён обычной геометрией.

**Comment by 0x4E69676874466F78** [comment]
Ситуация сложная. По идее случай слева это портал который надо удалять и в GL он удалён. Но в то же время для QRAD этот портал существует и оттуда бьёт солнце. 
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/8c5e7aa7-0132-4471-b557-839797c2893d)
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/7b1d5a2c-a26e-4a1b-8886-7cbdd5bdee42)

**Comment by w23** [comment]
> Ситуация сложная. По идее случай слева это портал который надо удалять и в GL он удалён. Но в то же время для QRAD этот портал существует и оттуда бьёт солнце.

Именно так.
Более того, студийные модели из него и в GL рендере должны подсвечиваться (если солнце правильно направлено).

**Comment by 0x4E69676874466F78** [comment]
> > Ситуация сложная. По идее случай слева это портал который надо удалять и в GL он удалён. Но в то же время для QRAD этот портал существует и оттуда бьёт солнце.
> 
> Именно так. Более того, студийные модели из него и в GL рендере должны подсвечиваться (если солнце правильно направлено).

Ну вон из портала зелёный исходит, это light_environment.

**Comment by 0x4E69676874466F78** [comment]
Короч как починишь #577 эту задачку можно закрывать на ближайшее время.

**Comment by w23** [comment]
> > > Ситуация сложная. По идее случай слева это портал который надо удалять и в GL он удалён. Но в то же время для QRAD этот портал существует и оттуда бьёт солнце.
> > 
> > Именно так. Более того, студийные модели из него и в GL рендере должны подсвечиваться (если солнце правильно направлено).
> 
> Ну вон из портала зелёный исходит, это light_environment единственный на карте.

Да, в qrad-запеканке они учитываются (там несколько сложнее -- учитываются не сами поверхности, а порождающие их браши, я не разбирался глубоко). А в GL рендере эти поверхности хотя и не рисуются, но, судя по коду, всё равно учитываются в динамическом освещении.

**Comment by 0x4E69676874466F78** [comment]
> > > > Ситуация сложная. По идее случай слева это портал который надо удалять и в GL он удалён. Но в то же время для QRAD этот портал существует и оттуда бьёт солнце.
> > > 
> > > 
> > > Именно так. Более того, студийные модели из него и в GL рендере должны подсвечиваться (если солнце правильно направлено).
> > 
> > 
> > Ну вон из портала зелёный исходит, это light_environment единственный на карте.
> 
> Да, в qrad-запеканке они учитываются (там несколько сложнее -- учитываются не сами поверхности, а порождающие их браши, я не разбирался глубоко). А в GL рендере эти поверхности хотя и не рисуются, но, судя по коду, всё равно учитываются в динамическом освещении.

Ага:
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/111d3661-4015-4253-a17e-05efdfac65fc)

**Comment by 0x4E69676874466F78** [comment]
Кстати GL там всё же рисует небо, но только внизу:
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/caf42479-022a-4d7e-980b-579695afb2e9)

Это при том что сам браш неба не касается пола.

**Comment by w23** [comment]
Для потомков: см. комменты в #577 за подробностями, что там за небесные поверхности на `de_dust2`, что там их две front+back, и что они детектятся разными тулами и удаляются парами.
