### ISSUE TITLE
no VK_KHR_ray_tracing device extension?

### ISSUE THREAD

**Issue by Demez** [w23/xash3d-fwgs#50]
in Quake 2 RTX and the [vk_raytracing_tutorial_KHR](https://github.com/nvpro-samples/vk_raytracing_tutorial_KHR) repo, `vkEnumerateDeviceExtensionProperties()` returns 144 device extensions, but for some reason, this is only listing 137 device extensions for me, and `VK_KHR_ray_tracing` is missing from the list, and i have no idea why

OS: Windows 10 20H2
GPU: EVGA RTX 3060 XC 12 GB
Vulkan driver: 1.2.189.0
Nvidia Driver: 471.96
32-bit build of Xash3D

**Comment by w23** [comment]
`32-bit build of Xash3D` <-- this.

Ray tracing extensions are only available in 64-bit mode. This is a driver limitation, 32-bit drivers simply do not expose these extensions. There's nothing we can do about it, unfortunately.

How to build 64-bit Xash3D: https://github.com/w23/xash3d-fwgs/wiki/64-bit-build-on-Windows

**Comment by Demez** [comment]
ah, somehow missed that small oversight when trying to figure out why that could be happening, my bad

**Comment by w23** [comment]
No worries! I ran into that myself and had a fair amount of headbanging trying to figure out what's wrong :). I don't think it's documented anywhere visibly enough.
