### ISSUE TITLE
Shadow gap on some geometry

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#507]
Лучше всего видно на cs_cbble
![image](https://user-images.githubusercontent.com/4449851/232007669-88b9935b-caf3-4e61-95d6-1fa781dff5cc.png)
![image](https://user-images.githubusercontent.com/4449851/232007711-235733ee-a1ac-46c2-bc44-a4ae23ed5872.png)
![image](https://user-images.githubusercontent.com/4449851/232007765-a8219de2-5555-48bc-9dea-436e353ade36.png)
![image](https://user-images.githubusercontent.com/4449851/232007813-3921ad43-8407-4c3d-a98f-26130569e43d.png)

Это из-за того что геометрия немного в воздухе и кулятся грани которые мы не видим.
> надо не делать куллинг треугольников, да
> надо оценить просадку производительности (если есть вообще)

Страдаем этой проблемой не только мы, но и рендер султима и rtx remix.

**Comment by w23** [comment]
Глянь там #508 не ломает ли что ещё.

**Comment by 0x4E69676874466F78** [comment]
> Глянь там #508 не ломает ли что ещё.

Не ломает.
