### ISSUE TITLE
patch: apply material for brush-entity only

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#526]
Существуют всякие объекты типа турбин-вентиляторов с генерик текстурой, эта же текстура используется на этом же уровне на столе (c1a3) было бы удобно применить материал с нужными параметрами чисто для энтити турбины, не трогая остальное.
Учитывая что на энтити может быть сразу несколько текстур то надо указать к какой именно текстуре нужно привязать материал.
```
{
"_xvk_ent_id" "39"
"_xvk_texture" "generic028"
"_xvk_material" "generic_metal1"
}
```

Связано #470

**Comment by 0x4E69676874466F78** [comment]
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/a9de45c8-cc3d-48c3-a5d0-959847cf6b3b)

**Comment by 0x4E69676874466F78** [comment]
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/542b1485-fb61-4715-97e0-8c04a6503c81)

**Comment by 0x4E69676874466F78** [comment]
Теперь это делается через:
```
{
	"_xvk_ent_id" "39"
	"_xvk_map_material" "generic028 generic_metal1"
}
```

**Comment by w23** [comment]
Done in #572
