### ISSUE TITLE
Render texture and color modes (blend incorrectly)

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#528]
Первая проблема, не совсем корректно рисуется режим color:

VK rastr:
![image](https://user-images.githubusercontent.com/4449851/235193750-398639c1-df3f-4268-bd18-4de39093c8c4.png)

VK RT:
![image](https://user-images.githubusercontent.com/4449851/235193775-7cae5753-2dc9-4fe7-9e4a-ca89b6c39fb8.png)

Это создаёт не совсем корректный вид на c1a4d.

Вторая, сильно некорректно рисуется режим texture:
![image](https://user-images.githubusercontent.com/4449851/235194571-062e7627-b6b3-44e6-8d3b-55637088f1b0.png)
Проблема отрисовки во-первых заключается в этой строчке:
https://github.com/w23/xash3d-fwgs/blob/8ac1a76259c7bd0e9e6b6ab7d2d8254850b18381/ref/vk/shaders/trace_simple_blending.glsl#L53
Здесь SRGBtoLINEAR применяется не к тому объекту, должно быть:
```glsl
vec3 color = kusok.model.color.rgb * SRGBtoLINEAR(texture_color.rgb) * geom.vertex_color.rgb * alpha;
```
Во-вторых есть вторая проблема связанная с альфой, ~~альфа оказывается в пространстве SRGB, а не в ожидаемо линейном.~~
Можно написать так (аппроксимация SRGBtoLINEAR для альфы): 
```glsl
vec3 color = kusok.model.color.rgb * SRGBtoLINEAR(texture_color.rgb) * geom.vertex_color.rgb * pow(alpha,2.2);
```
И станет сильно лучше. Но это только замаскирует проблему.
![image](https://user-images.githubusercontent.com/4449851/235195793-693466c4-065c-4191-9dd4-33c4a7a01efb.png)
Но это по прежнему не до конца корректный вид.
~~Дело в том что сейчас revealage работает как-то неправильно. Если у стекла в режиме texture стоит 0 альфа то фактически это не полностью прозрачное стекло, а невидимая поверхность которая затеняет за собой окружение.
В качестве выхода можно назначить~~
```glsl
float revealage = 1.5;
```
~~это починит стёкла, но это сломает glow спрайты.~~
Я здесь уже не знаю как починить.

**Comment by 0x4E69676874466F78** [comment]
Проблема глубже и зависит от яркости текстуры. Тёмные текстуры визуально выглядят более полупрозрачными нежели светлые.

**Comment by w23** [comment]
Вот бы написать перебор всех параметров (альфы, цветов модели и фона), вывести это всё на графики, и сравнить напрямую. Так было бы понятнее, чё у них там.

**Comment by 0x4E69676874466F78** [comment]
pow 2.2 на альфу делать не надо, это просто маскирует проблему и создаёт новую.
Проблема даже не в яркости текстуры а в самом режиме смешивания. 
Режим texture работает валидно на растеризации невалидно на лучах.

**Comment by 0x4E69676874466F78** [comment]
VK rastr:
![image](https://user-images.githubusercontent.com/4449851/235297026-76f90a7b-c005-4346-9428-e6c4fcc1c3c7.png)
VK RT:
![image](https://user-images.githubusercontent.com/4449851/235297041-f3e7ce90-d38b-4db1-beaf-6b629745d1e5.png)

**Comment by 0x4E69676874466F78** [comment]
c pow 2.2
![image](https://user-images.githubusercontent.com/4449851/235297127-12c4346d-cf7a-4f3f-946c-bb744244d612.png)
вроде бы лучше, но здесь оно вообще пропадает:
![image](https://user-images.githubusercontent.com/4449851/235297175-d1bf00fc-a0c9-4737-b4ca-a840d7f2ccf4.png)
![image](https://user-images.githubusercontent.com/4449851/235297177-b72b6cbf-ebde-41df-ad40-5ea7a81013b5.png)

**Comment by w23** [comment]
Это не исправлено, надо всё ещё разобраться, почему блендинг иной.

**Comment by 0x4E69676874466F78** [comment]
test_main
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/cac54b8d-0b16-482a-a73f-d487cc0decee)

**Comment by 0x4E69676874466F78** [comment]
Ещё сейчас сломался режим Color в RT режиме:
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/67456817-ddde-4a89-965a-409db9705037)

**Comment by w23** [comment]
> Ещё сейчас сломался режим Color в RT режиме

давно?

**Comment by 0x4E69676874466F78** [comment]
> > Ещё сейчас сломался режим Color в RT режиме
> 
> давно?

Завтра выясню.
