### ISSUE TITLE
Win11 built-in antivirus marks xash3d.exe as Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by Tarasus** [w23/xash3d-fwgs#544]
Taken xash3d-fwgs-win32-i386.7z from the latest releases page, unzipped it and windows defender gone wild

Also Virustotal has a lot of detects [link here](https://www.virustotal.com/gui/file/79b59d3799b17e3588395ff55dcadbd4b659bd81f16d36ee68db31634c7cd4bc/detection)

**Comment by 0x4E69676874466F78** [comment]
https://github.com/FWGS/xash3d-fwgs/issues/1385

**Comment by 0x4E69676874466F78** [comment]
> i386

It has nothing to do with us, ray tracing only work on a 64bit build.

**Comment by Tarasus** [comment]
> ray tracing only work on a 64bit build.

Please mark and emphasise that fact in readme.md. 
It is confusing seeing lots of choice options on testing builds release page.

**Comment by 0x4E69676874466F78** [comment]
@Tarasus 
> Please mark and emphasise that fact in readme.md.

This has been in the readme for a long time
https://github.com/w23/xash3d-fwgs/blob/vulkan/README.md?plain=1#L11
