### ISSUE TITLE
Model inheritance bug

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#554]
Патроны револьвера считаются статической моделью, но они привязаны к динамической модели и должны наследовать координаты динамической, но этого не происходит с недавних пор:
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/2211a5d8-ff08-4c35-9e9f-78ff85f5a3f5)
(патроны торчат наружу)
Баг естественно есть и в растеризации:
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/b6304d13-13c3-4053-9adb-b268344a598f)

Патроны через HL model viewer выглядят как отдельная часть
```
$bodygroup "gun"
{
	studio "python_gun"
}
$bodygroup "bullets"
{
	studio "python_bullets"
}
$bodygroup "speedload"
{
	studio "python_speedload"
}
$bodygroup "hands"
{
	studio "python_hands"
}
$bodygroup "scope"
{
	blank
	studio "python_lasersight"
}
```

**Comment by 0x4E69676874466F78** [comment]
Слом на 567d014adaa738edea3a9185cd1d9eea1eb2bb6f
Предыдущий 9636b541c5a2fc7d84043ba1f926fb158a1f1953

**Comment by w23** [comment]
Вот такая гипотеза есть: https://github.com/w23/xash3d-fwgs/blob/d9207963f998c2684b122f0776730cd9ba3447cd/ref/vk/vk_studio_model.c#L70
Надо проверить, не жулькаются ли они через `bonecontroller`
