### ISSUE TITLE
Performance regression on c2a5

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#555]
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/c196f055-acec-4f59-98bc-62a15ad4dbb2)

**Comment by 0x4E69676874466F78** [comment]
Связанная проблема, почему-то текстуры с +0 и +A считаются обязательно анимированными хотя это не так.
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/922498c1-90ce-44c0-a102-91a99f6147a5)

**Comment by 0x4E69676874466F78** [comment]
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/09046284-d3d8-4abb-83d0-0a2595ede5fa)

**Comment by w23** [comment]
Можно проверять на анимацию более жёско: что все текстуры действительно разные.
