### ISSUE TITLE
Crash if you explode three times, die and reload

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#562]
Вынесено из #364

Если я буду повторять взрыв, т.е. загружаться с сохранения, прыгать, умирать, опять загружаться и опять прыгать-умирать то с попытки 3 я словлю такую ошибку:
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/c74521d3-047a-4f5e-99c2-90adfa7dd338)
Если нажать повтор:
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/5e9944e1-97ba-427d-b4ba-93cdfc3963f3)

**Comment by w23** [comment]
- Не воспроизводится на линуксе.
- Воспроизводится на винде.
- Что видим: на винде после загрузки из сейва на той же карте (не обязательно прыгать в мины) у энтитей слетают указатели, таким образом теряя связь с entity data и сабмоделями из мира до загрузки. На линуксе удивительным образом указатели ровно те же самые, поэтому всё продолжает работать нормально. (Это может быть и случайностью на линуксе тоже, это неизвестно).

**Comment by w23** [comment]
То есть эту же проблему мы можем видеть на любом уровне после множества загрузок. Не обязательно с кучей мин.

Что делать?
- [ ] почему энтити теряют указатели на винде, и не теряют на линуксе? Можно ли это исправить?
- [ ] Тупо чистить entity data при перезагрузке, даже если это `is_save_load`
