### ISSUE TITLE
Wrong console/Powershell cursor handling on exit (Windows)

### ISSUE THREAD

**Issue by nilsoncore** [w23/xash3d-fwgs#568]
## To reproduce
1. Open CMD/Powershell instance.
2. Launch Xash3D.
3. Exit the program.

Then:
- in Powershell, the cursor position will not be updated and all subsequent input will override printed output;
- in CMD, the cursor will be placed at the right place.

But, both in CMD and Powershell the printed message "Press Enter to continue..." does not mean anything, as user can freely type in terminal.

## Screenshots
Powershell:
1. Before Xash3D launch.

![xash_ps_before_launch](https://github.com/w23/xash3d-fwgs/assets/65307695/90bbe846-8f06-4cae-87a7-739933764cc0)

2. After Xash3D exit.

![xash_ps_after_launch](https://github.com/w23/xash3d-fwgs/assets/65307695/dbbcb7c0-5eee-4f2b-abf8-f971d11970e8)

3. After retrieving previous input (only key up is pressed).

![xash_ps_paste](https://github.com/w23/xash3d-fwgs/assets/65307695/0855c802-9e5a-416f-8c24-58653e063f3f)

4. After typing stuff.

![xash_ps_write](https://github.com/w23/xash3d-fwgs/assets/65307695/df5938b4-dff4-47c9-bab8-c38b3af0efcf)

CMD:
1. Before Xash3D launch.

![xash_cmd_before_launch](https://github.com/w23/xash3d-fwgs/assets/65307695/4b44ffb8-0114-4922-b59a-454f91d44a67)

2. After Xash3D exit.

![xash_cmd_after_launch](https://github.com/w23/xash3d-fwgs/assets/65307695/93b0b9ef-4e29-4eea-9966-1b22453cff4c)

3. After retrieving previous input (only key up is pressed).

![xash_cmd_paste](https://github.com/w23/xash3d-fwgs/assets/65307695/e889a1ed-9767-4332-b206-f1700ddaaf5a)

4. After typing stuff.

![xash_cmd_write](https://github.com/w23/xash3d-fwgs/assets/65307695/bd31cb94-fc1a-44c5-95d9-a4d93c5d8bc1)

**Comment by nilsoncore** [comment]
Label `ray tracing` is wrong, `visual bug` - maybe?

**Comment by w23** [comment]
Это в апстрим, мы с консолюшкой в вулкане не делаем ничегошеньки. И в движок по крайней мере в `vulkan` ветке стараемся не ходить, даже если там что-то поломано, что причиняет боль.

**Comment by nilsoncore** [comment]
Логично. Пойду тогда им перекину.

**Comment by nilsoncore** [comment]
> Логично. Пойду тогда им перекину.

Хотя, учитывая, как долго скорее всего этот форк не обновлялся, возможно там уже все и подправили. Придется склонировать, забилдить, проверить... Ну да ладно.
