### ISSUE TITLE
Path correction

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#578]
Исправление для PBR путей, убираем `.bsp` и т.п. где не надо:
`pbr/maps/c0a0a.bsp/c0a0a.bsp.mat` -> `pbr/maps/c0a0a.bsp/c0a0a.mat`
`pbr/halflife.wad/halflife.wad.mat` -> `pbr/halflife.wad/halflife.mat`
`pbr/sprites/bexplo.spr/bexplo.spr.mat` -> `pbr/sprites/bexplo.spr/bexplo.mat`
`pbr/models/v_357.mdl/v_357.mdl.mat` -> `pbr/models/v_357.mdl/v_357.mat`

У нас в `maps/c0a0a.rad` всё же и хорошо бы этому следовать везде.
Здесь вылезает проблема с патчами. Мы могли бы поступить по аналогии с PBR:
`luchiki/maps/c0a0.bsp.patch` -> `luchiki/maps/c0a0.patch`
Однако у нас здесь выходит лишние две директории в пути.
Можно было бы патчи положить в maps где лежат rad файлы уже, тем более патчами в массе своей патчится именно освещение, ну и к карте близко.
То есть сделать:
`luchiki/maps/c0a0.bsp.patch` -> `maps/c0a0.patch`
С другой стороны если мы будем патчить не только карты, но и модели, здесь уже возможно стоит иметь структуру `luchiki/*`.
Однако `.bsp` нужно убрать в любом случае.

Обсуждаемо.

**Comment by 0x4E69676874466F78** [comment]
Остаётся решить вопрос что лучше:
1. luchiki/maps/map.patch и luchiki/models/model.patch
2. maps/map.patch и models/model.patch

Первое удобнее что патчи все +- в одном месте, второе удобнее что лежит близко к телу и в случае с картами рядом с рад файлами.

**Comment by w23** [comment]
`rad` файлы лежат близко к картам из соображений удобства параллельной разработки/тестирования вместе с qrad. В условиях конечной установки пользователем смысл располагать их рядом не просто теряется, а ещё и усложняет эту самую установку.

Для конечного пользователя установка должна быть как можно проще. Вида "распакуй вот этот зип вот в этот каталог". Сейчас надо подкладывать три отдельные вещи: и `luchiki`, и `pbr`, и `maps/*.rad`, что не круто.

Каков характерный процесс установки апстримового xash? Как мы можем максимально не усложняя встать на него?

В идеале, конечно, xash должен тупо сам без спросу подтянуть ассеты из стимовой установки, и какие-то дополнительные ресурсы из каталога рядом с exe файлом. Но этот процесс надо согласовывать с fwgs, на что у меня сейчас нет пропускной способности.

**Comment by 0x4E69676874466F78** [comment]
@w23 для конечного пользователя будет от 1 pak файла на мод.
Но я наверное сделаю набор pak файлов:
* base_light.pak
* rt_patch_light.pak
* pbr.pak
* bluenoise.pak
* shaders.pak

Они копируются внутрь папки мода, типа в корень valve.

**Comment by 0x4E69676874466F78** [comment]
Наверное я пойду дальше:
* vulkan_hl_base_light_001.pak
* vulkan_hl_rt_patches_001.pak
* vulkan_materials_pbr_001.pak
* vulkan_materials_shaders_001.pak
* vulkan_materials_shaders_bluenoise_001.pak — голубой шум к шейдерам (потенциально можно подменить на разные реализации этого шума)

001 это версия пакета, по идее если мы добавим 002, то вторая версия точечно перезапишет файлы из первой, так было в движках Id, надо будет проверить как здесь.
Вместо vulkan можно vk сделать, пока не понял как лучше.

**Comment by 0x4E69676874466F78** [comment]
> Каков характерный процесс установки апстримового xash? Как мы можем максимально не усложняя встать на него?

Скачать архив из релиза, распаковать, скопировать модпапки из оригинальной дистрибуции.
Возможно ещё скачать и подложить extras.pak я не помню точно, это могло уже поменяться.
Запустить xash3d. Ничего сложного. 

> В идеале, конечно, xash должен тупо сам без спросу подтянуть ассеты из стимовой установки, и какие-то дополнительные ресурсы из каталога рядом с exe файлом. Но этот процесс надо согласовывать с fwgs, на что у меня сейчас нет пропускной способности.

Технически реализуемо, но это нужно закодить и народ уже как-то справляется и так давно все кому это нужно.
Можно налабать самим cmd/sh файлы для такого, надо только разобраться где там стим хранит пути к играм.

**Comment by w23** [comment]
А, про pak/wad я не подумал вообще. Если оно туда складывается и легко читается, то мне тогда всё равно вообще, как оно будет лежать. Т.е. менять с лучиков можно только если это почему-то будет удобнее тебе, например.

> > В идеале, конечно, xash должен тупо сам без спросу подтянуть ассеты из стимовой установки, и какие-то дополнительные ресурсы из каталога рядом с exe файлом. Но этот процесс надо согласовывать с fwgs, на что у меня сейчас нет пропускной способности.
> 
> Технически реализуемо, но это нужно закодить и народ уже как-то справляется и так давно все кому это нужно. Можно налабать самим cmd/sh файлы для такого, надо только разобраться где там стим хранит пути к играм.

Не знаю, насколько xash умеет в несколько каталогов с игрой, чтобы стимовую инсталляцию не захламлять нашими файлами.
Путь к стиму, по крайней мере по-умолчанию, несложный. См. https://github.com/w23/OpenSource/blob/115c1ee4a42772b20f46054fc068a8882d2f2831/src/OpenSource.c#L639-L652

**Comment by 0x4E69676874466F78** [comment]
> Не знаю, насколько xash умеет в несколько каталогов с игрой, чтобы стимовую инсталляцию не захламлять нашими файлами.
> Путь к стиму, по крайней мере по-умолчанию, несложный. См. https://github.com/w23/OpenSource/blob/115c1ee4a42772b20f46054fc068a8882d2f2831/src/OpenSource.c#L639-L652

Корректнее из стимовской версии скопировать папки с ресурсами, иначе всё может поломаться внезапно.

**Comment by 0x4E69676874466F78** [comment]
Пока закроем.
