### ISSUE TITLE
Draw a skybox if the ray hit on nothing

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#579]
Иначе при удалении паразитных граней скабокса мы ловим проблему:
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/c3c8e42d-3ad9-4806-8131-725c27fa8a76)
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/2debed33-ff7d-46d5-b8ff-84822f78fb18)

**Comment by 0x4E69676874466F78** [comment]
Таких поверхностей там теперь гораздо больше.

**Comment by 0x4E69676874466F78** [comment]
Всё ок.

**Comment by 0x4E69676874466F78** [comment]
Единственное теперь где мы ожидали увидеть черноту там теперь скабокс, например c0a0e (это место не видится но тем не менее):
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/14acec4b-96e3-4d05-8594-85362e927890)
На c1a0a более заметно:
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/59b38a17-ff16-4c8a-91cb-2b7700f45e75)

**Comment by 0x4E69676874466F78** [comment]
Эти вещи можно запатчить добавлением закрывающей грани #540 либо сменить скайбокс на тёмный. Патчить wordspawn на предмет скайбокса мы умеем?

**Comment by w23** [comment]
А в GL рендере это как выглядит?

**Comment by 0x4E69676874466F78** [comment]
> А в GL рендере это как выглядит?
Там последний кадр, нет clear.

**Comment by w23** [comment]
Тут можно через патчи для карты затащить флажок, что делать с фоном -- закрашивать цветом, закрашивать небом, закрашивать предыдущим кадром, заблюривать соседями, и пр.

**Comment by 0x4E69676874466F78** [comment]
@w23 пока что все места это самое начало где скайбокса в принципе нет, кстати вот эверистика! Мы же можем проверить есть ли SURF_DRAWSKY вообще на карте? Если нет то мы просто для пустоты рисуем ничего.

**Comment by w23** [comment]
Можно было бы тупо скайбокс кубмапу заменить на черноту, если не задан, но интересный вопрос, насколько карты действительно рассчитывают на дефолтный скайбокс.

**Comment by 0x4E69676874466F78** [comment]
> Можно было бы тупо скайбокс кубмапу заменить на черноту, если не задан, но интересный вопрос, насколько карты действительно рассчитывают на дефолтный скайбокс.

Рассчитывают, так что лучше мой вариант.

**Comment by 0x4E69676874466F78** [comment]
Какие у нас фактические сейчас вырисовываются стратегии:
1. Если нет SURF_DRAWSKY то рисуем черноту; если есть рисуем там скайбокс. 
2. Удалить все SURF_DRAWSKY нарисовать везде скайбокс // нужно на c2a5 чтобы вертолёт не проваливался в скайбокс

Первый вариант у нас всегда должен быть активен по умолчанию, второй нужен только для ряда карт чтобы не мучиться с удалением вручную SURF_DRAWSKY, для этого надо в патчах добавить ключ `"_xvk_remove_surf_drawsky" "1"` (что-то в таком духе).
