### ISSUE TITLE
Rendering artifacts on hevsuit

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#585]
https://github.com/w23/xash3d-fwgs/assets/4449851/ca036284-6fea-4fe2-9ecb-a7e9a23b6e97

**Comment by 0x4E69676874466F78** [comment]
Изнутри там такое:
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/dd5ee454-6ed4-4c82-b9f4-31e556a43f9e)

**Comment by w23** [comment]
Ага, тоже обратил внимание на прошлом стриме.
Не помню, чтобы раньше такое было. Интересно, когда оно появилось. Не с тем ли, как мы пошалили со sky поверхностями? Или, может, с прозрачкой -- она начала отрабатывать иначе. Или случилась синергия этих двух пацанов.

**Comment by 0x4E69676874466F78** [comment]
Я поищу коммит.

**Comment by 0x4E69676874466F78** [comment]
Коммита ещё не нашёл (не искал, забыл).
Однако обнаружил закономерности в поведении.
Рождать новые костюмы можно через команду give item_suit
Само по себе рождение костюма не влияет ни на что, на новых костюмах баг повторяется.
А вот если попереходить с карты на карту то артефакты у костюмов разительно меняются.
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/d1e128ab-78ff-450f-a0cc-bc03ed7aeda4)
![image-1](https://github.com/w23/xash3d-fwgs/assets/4449851/22c0f623-f2f5-4f27-89b9-d71608cd5314)
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/38eaba4c-894c-4bb9-94d8-89b07e18f296)

**Comment by 0x4E69676874466F78** [comment]
Артефакт начинается после ffa96037474d71357004856f2e42c5f7336dc371 на прыдыдущем 2dc68544d6c045b5a4ab8a316ab3a3fe841d760d не видно.

**Comment by 0x4E69676874466F78** [comment]
> в prev_verts во всех непонятных ситуациях надо дублировать текущие позиции
