### ISSUE TITLE
Broken normal maps

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#595]
Идём в test_material, а там такое:
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/5ef4cde8-1cc7-4e55-ae37-f7ce5042b23a)

Артефакты нормали стабильны, не зависят от положения камеры, как будто их где-то ещё до шейдера пошакалило.

**Comment by w23** [comment]
Здесь предположение такое, что 8-битной точности xy не хватает для того, чтобы достаточно гладко восстановить z. Если через `normalize(tnorm)` "сгладить" нормаль перед масштабированием, то этот ступенчатый шум пропадает:
https://github.com/w23/xash3d-fwgs/blob/60f83245ee47881254af86f421bf07ce002eca22/ref/vk/shaders/ray_primary_hit.glsl#L68-L70

Костыль через масштабирование z компоненты отдельно тоже помогает -- сохраняем её битики, которые в нормализации далее тоже учитываются и сглаживают:
https://github.com/w23/xash3d-fwgs/blob/7e3f8785f7ae0ba1e9ba94655338dbb56b89eb6a/ref/vk/shaders/ray_primary_hit.glsl#L51-L54

Заметки:
- Если нужно сократить до 2 компонент, то трюк с нормализацией не пройдёт, т.к. не с чем нормализовать, и восстановление с z будет давать квантизационную лесенку
- Можно занизить диапазон допустимого отклонения нормали (не знаю, умеет ли в это софт, генерячащий нормалмапы), тогда допустимые значения будут кучнее, и лесенку будет менее видно.
- Можно забить -- на реальных текстурах + цвет + освещение этого эффекта будет видно меньше
- Можно дизерить
- Можно брать более жирный формат с большим количеством бит, но тогда хз, насколько это выигрывает у тупо наличия 3 компоненты.

**Comment by 0x4E69676874466F78** [comment]
Пока что я понял надо нормали обязательно нормализовывать. Я попробую нормализовать и посмотреть что будет.

**Comment by w23** [comment]
> Пока что я понял надо нормали обязательно нормализовывать. Я попробую нормализовать и посмотреть что будет.

Я тут ещё спросонья подумал, что, наверное, нормализовать может быть контрпродуктивно. Потому что смотри, если, например, пытаться закодировать нормализованную (1,1,1), то она станет (.7,.7,.7), и потеряет в точности, т.к не будет использовать весь диапазон значений возможных.

Надо посмотреть на то, что именно генерячат тулы, которые делают эти текстуры, и что принято делать в индустрии.

Ещё можно позапихивать нормаль в 2 компоненты таким же образом, как мы делаем для ж-буфера

**Comment by 0x4E69676874466F78** [comment]
> Я тут ещё спросонья подумал, что, наверное, нормализовать может быть контрпродуктивно. Потому что смотри, если, например, пытаться закодировать нормализованную (1,1,1), то она станет (.7,.7,.7), и потеряет в точности, т.к не будет использовать весь диапазон значений возможных.

Об этом я думал, но глядя на то что на тестовую картинку никак не появлияла нормализация в шейдере мне показалось что пофиг.

> Надо посмотреть на то, что именно генерячат тулы, которые делают эти текстуры, и что принято делать в индустрии.

Это не работает. Мы же не с геометрии получаем карты нормалей, а с diffuse либо аналитически либо вовсе (чаще) нейросетями.

**Comment by w23** [comment]
> > Надо посмотреть на то, что именно генерячат тулы, которые делают эти текстуры, и что принято делать в индустрии.
> 
> Это не работает. Мы же не с геометрии получаем карты нормалей, а с diffuse либо аналитически либо вовсе (чаще) нейросетями.

А, то есть там вообще что попало на входе, ок.
Почитал-поспрашивал про индустрию, там все просто нормализуют, никто не парится о точности в контексте нормализации и оптимального использования бит.

Поэтому можно просто и нам нормализовать (*перед* записью в какую-либо текстуру), а потом уже конвертировать в финальное изображение.

**Comment by 0x4E69676874466F78** [comment]
[debug_circle_normal3_normalize.zip](https://github.com/w23/xash3d-fwgs/files/12840781/debug_circle_normal3_normalize.zip)

При `//#define KTX2` 
debug_circle_normal3_normalize.png
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/e3c40054-150a-4d4e-aa57-6869715ce992)

debug_circle_normal3.png (без нормализации)
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/260b48a3-17a2-4e0a-a816-b40112c81cf9)

debug_circle_normal3_BC5_S.ktx2 и debug_circle_normal3_normalize_BC5_S_mip.ktx2 одинаковы результат
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/b971a3d8-2482-4d3f-a95a-68176fd42435)

При `#define KTX2` 
debug_circle_normal3_normalize.png b debug_circle_normal3.png (без нормализации) одинаковы результат
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/fafe0207-4b3b-415b-b17e-4d5dd2bffe36)

debug_circle_normal3_BC5_S.ktx2 и debug_circle_normal3_normalize_BC5_S_mip.ktx2 одинаковы результат
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/6e7edf43-beb9-43a3-a191-907aaeed0a86)

**Comment by w23** [comment]
Поковырялся с нормалями через shadered и имею два ключевых наблюдения:
1. Нормализованные нормали не нормализованные, по крайней мере в пнг (шадеред не умеет в ктх)
2. Нормализация их всё равно ведёт к квантизационным артефактам даже с 3 компонентами.

Подобнее на скриншоте:
![xashrt-normal-fail01](https://github.com/w23/xash3d-fwgs/assets/321361/6c507a27-c45d-4b60-bd00-5dcaf4dc0cd8)

1. Слева сверху -- оригинальная текстура, приведённая к -1..1
2. Слева снизу -- нормализованная текстура (видна квантизация)
3. Справа сверху -- разница между родной длиной вектора (до нормализации) и единицей. Красные пиксели -- длина больше 1, зелёные -- меньше.
4. Родная длина в абсолютных значениях. Должна быть везде 1, т.е. белая. Серые зоны -- меньше 1, красные -- больше. Розовые -- около 1, но только чуть-чуть больше.

Я вообще хз.

**Comment by w23** [comment]
Попробовал несколько случайных примеров нормалмап из интернета, они все сносные -- да, немного не нормализованные (как правило могут быть несколько меньше 1, но редко когда выше), но при ренормализации таких артефактов не дают. :shrug:

**Comment by 0x4E69676874466F78** [comment]
> Что это за утилита, которой ты готовишь? Есть документация?

chainner, но я несколько много месяцев уже не обновлял, может бага есть? чем ещё лучше попробовать нормализовать из современного?

**Comment by w23** [comment]
> > Что это за утилита, которой ты готовишь? Есть документация?
> 
> chainner, но я несколько много месяцев уже не обновлял, может бага есть? чем ещё лучше попробовать нормализовать из современного?

Я, право, совсем не знаю. А из чего ты готовишь?

**Comment by 0x4E69676874466F78** [comment]
> Я, право, совсем не знаю. А из чего ты готовишь?

Я не помню чем делал уже. Посмотрю что есть в substance на эту тему, может им нормализую.

**Comment by 0x4E69676874466F78** [comment]
ShaderED есть же кстати под линь, даже сборка, не работает?

**Comment by 0x4E69676874466F78** [comment]
[debug_circle_normal3_normalize2.zip](https://github.com/w23/xash3d-fwgs/files/12841977/debug_circle_normal3_normalize2.zip)
Нормализовал с помощью substance designer. Результат другой.

**Comment by w23** [comment]
> [debug_circle_normal3_normalize2_v2.zip](https://github.com/w23/xash3d-fwgs/files/12842019/debug_circle_normal3_normalize2_v2.zip) Нормализовал с помощью substance designer. Пришлось помучиться с интерфейсом (форсировало 16бит). ![image](https://user-images.githubusercontent.com/4449851/273480426-0d7ea922-6956-459d-9144-b6bae852038f.png) Результат другой.

Этот нормализованный вообще как надо, да.

**Comment by w23** [comment]
> ShaderED есть же кстати под линь, даже сборка, не работает?

Есть под линь, но мне быстрее было тупо в виндовую виртуалку, чем возиться.

**Comment by 0x4E69676874466F78** [comment]
> Этот нормализованный вообще как надо, да.

Теперь надо понять чем свободным делать подобное же.

**Comment by w23** [comment]
> > Этот нормализованный вообще как надо, да.
> 
> Теперь надо понять чем свободным делать подобное же, желательно в CLI. В принципе я могу в проект юнити (в materialize) скомпилировать эти узлы в шейдеры и собрать под линь в том числе и даже CLI добавить. А в chainner это надо чинить если в новой версии не починили то я создам там issue.

Если конкретно только нормализацию делать, то можно и своё написать.
Другое дело, если там цепочки эффектов, и надо упаковывать.

Интересно, есть ли у того же imagemagick фильтр нормализации? Умеет ли он в текстурную комперссию?

**Comment by w23** [comment]
https://kwasi-ich.de/blog/2012/10/03/bytenormals/

**Comment by w23** [comment]
https://jcgt.org/published/0003/02/01/

**Comment by 0x4E69676874466F78** [comment]
Закрыто по причине отказа от BC5 как сложного подхода который в наивном исполнении теряет качество, а выигрыша в размере нет никакого.
