### ISSUE TITLE
Transparent surfaces (e.g. glass) look way too dark

### ISSUE THREAD

**Issue by w23** [w23/xash3d-fwgs#60]
There are supposedly two issues:
- Chance of refracting into surface is way too low.
- Rays are double-attenuated by hitting the opposite brush surface from the inside.

Consider:
- [x] treating alpha as *transmittance* or something (after fresnel-based specular-vs-diffuse split)
- [ ] doing (supposedly non-free) backface culling when tracing transmitted "inside" ray

Also, maybe read something like `B. Walter, S. R. Marschner, H. Li and K. E. Torrance, "Microfacet Models for Refraction through Rough Surfaces," Rendering techniques, 2007. `

**Comment by w23** [comment]
This needs two more things:
- me to figure out how to properly handle ray continuation selection (specular vs diffuse bounce vs trasmission vs light contribution)
- possible a resource remaster e.g. to provide 2 textures for glass: specular+diffuse light, and transmissiveness.

**Comment by 0x4E69676874466F78** [comment]
Надо это потюнить, сейчас они заметно темнее чем надо, тормозят свет и это влияет на итоговое освещение, в некоторых сценах очень заметно!
