### ISSUE TITLE
Profiler stack gets unbalanced occasionally

### ISSUE THREAD

**Issue by w23** [w23/xash3d-fwgs#604]
Sometimes this happens:
`[2023:10:14|16:06:13] Host_Error: assert stack[depth].scope_id == scope_id failed at A:\HL1-DEV\xash3d-fwgs\ref\vk\r_speeds.c:216`

Probably related to making screenshots / alt-tabbing.

Crashing here doesn't make much sense. I mean, this is definitely a programming error, so `ASSERT` is justified. But this is also a helper thing, happens rarely, and hard to diagnose only with this message.

What to do:
- Replace the assert with a regular check
- If the check fails, `S_ERROR` print out the full stack so that diagnosing this is possible
- Probably fix the cause, i dunno

**Comment by 0x4E69676874466F78** [comment]
`r_speed 15; r_speeds_graphs "gpuscope.GPU"; r_speeds_graphs_width ""`
Запускаю игру, открываю консоль, жму кнопку свернуть, разворачиваю с панели задач и ошибка.
