### ISSUE TITLE
Glass gibs don't get translucency 

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#613]
Не могу сделать им отражения. Стёкла рождаются динамически. Это студиомодели.
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/e48b39ff-5d69-4db7-bdb3-3c5f18270aa3)
```
{
"for" "#models/glassgibs/chome_glass.mdl"
//"basecolor_map" "chome_glass.png"
//"normal_map" "chome_glass_normal.png"
//"metal_map" "chome_glass_metal.png"
//"roughness_map" "chome_glass_roughness.png"
// FIXME
"basecolor_map" "/colors/white.png"
"base_color" "1 1 1 1"
"roughness" "0.01"
"metalness" "1"
}
```

**Comment by w23** [comment]
О, придётся тоже кастомный код писать для назначения студийным моделям режима материала.
