### ISSUE TITLE
patch: can't turn off smoothing via `_xvk_smoothing_excluded_pairs`

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#619]
Карта c1a1b, напротив красной комнаты есть стена, подсветив фонариком видно такое:
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/7b879162-b9b9-4b60-bc92-8932b56f6f73)
По идее чтобы это выключить достаточно было:
```
{
"_xvk_smoothing_excluded_pairs" "2792 2790 2793 2791 2871 2850 2872 3187" 
}
```
получается так:
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/badab5e7-9cd4-460f-b6da-4baa75fb85ba)
Я даже пробовал там описать лишнее:
```
{
"_xvk_smoothing_excluded_pairs" "2790 2791 2792 2793 3187 2850 2874 2871 2872 2853 2900 2901 3182 3181"
}
```
Не помогает.
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/140ef331-e430-40d0-a2f7-5551d8e5bdae)
Даже хуже стало. Нужно в каком-то особом порядке их описывать?
Помогает только:
```
{
"_xvk_smoothing_threshold" "44"
}
```
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/1ed7d3f7-c390-4f4c-994a-a56b85a9fe96)

Но что там ещё хватает на 45 градусах? Как это проследить?

**Comment by 0x4E69676874466F78** [comment]
Я подумал может ввести новый механизм на такие случаи который сглаживание для всех соседних граней выключает?

**Comment by 0x4E69676874466F78** [comment]
Я кажись понял, я должен повторять пары в списке, недостаточно просто написать список из всех граней. Но у меня всё равно не выходит сделать прям нормально, это очень муторно.

**Comment by w23** [comment]
Я сразу говорил, что сглаживание это прохладная история. Без полной ретопологии будем всё время что-нибудь да огребать.

**Comment by w23** [comment]
Варианты из попроще:
- как ты предложил выше, блокировать любое сглаживание с любыми соседями для заданных поверхностей
- инвертировать смысл: допускать сглаживание только для заданных поверхностей. Я предлагал это раньше именно из-за того, что нам проще знать, что именно надо сгладить, чем ходить потом собирать везде в самых неожиданных местах артефакты.
-

**Comment by 0x4E69676874466F78** [comment]
> инвертировать смысл: допускать сглаживание только для заданных поверхностей. Я предлагал это раньше именно из-за того, что нам проще знать, что именно надо сгладить, чем ходить потом собирать везде в самых неожиданных местах артефакты.

Не, я сдохну все эти трубы сглаживать и прочие полутрубы. Побегай и посмотри сколько там сглаженных поверхностей и сколько надо руками граней задать.

**Comment by 0x4E69676874466F78** [comment]
Вот смотри сколько там надо:
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/d5da33d9-7c7d-4044-aec3-b799b18f6171)
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/541f0764-bc0f-4bf5-a50e-a95f61335eb9)
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/1f734fcf-19b8-41e9-8394-4b95d00c7c3a)
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/9af49471-355d-4618-9e7e-198647ade773)
И далее эту канализацию. 
Бочки повезло что там энтити, а то ещё бы навалилось.

**Comment by w23** [comment]
Ну, беда в том, что теперь нет уверенности, что у нас не отломаны нормали на вообще всех остальных поверхностях теперь. Всех остальных поверхностей больше.

Надо сделать какой-то отладочный вид, который бы в первом приближении просто показывал направление нормалей цветом хотя бы. Далее, например, можно сделать вывод в цвете разницы между строго геометрической нормалью и шейдинг/сглаженной. Это бы выпятило все косяки визуально, останется только зайти в каждый закоулок каждой карты и заметить.

**Comment by w23** [comment]
> > как ты предложил выше, блокировать любое сглаживание с любыми соседями для заданных поверхностей
> 
> Если это не слишком сложно добавлять давай попробуем.

- [ ] давай попробуем

**Comment by 0x4E69676874466F78** [comment]
Далее я напоминаю общую проблему: 45 градусов есть гарантировано в qrad/hlrad для всех модов, без всяких патчей это работает. Да местами там видны кривости, но с ними лучше чем вообще без сглаживания.
Я могу избирательно на картах выключать через  
```
{
"_xvk_smoothing_threshold" "0"
}
```
но мне нужны удобства чтобы не херачить каждую грань отдельно, это очнеь медленно, я уже думаю запатчить bspguy чтобы по горячей клавише копировать в буфер обмена ид грани.

**Comment by w23** [comment]
> но мне нужны удобства чтобы не херачить каждую грань отдельно, это очнеь медленно, я уже думаю запатчить bspguy чтобы по горячей клавише копировать в буфер обмена ид грани.

Как тебе моё предложение выше?

Вот это:


> Можно ещё рядом с инфотулом сделать селектор поверхностей, чтобы выделять в группы было проще. И в шейдерах выделенныеподсвечивать визуально. Типа, делаются консольные команды вида "добавить" "удалить" из набора поверхность под прицелом, а дальше "сбросить" и "сохранить в лог/файл". Это всё биндится на кнопки, и вот уже какой-то редактор получается почти.

**Comment by 0x4E69676874466F78** [comment]
@w23 
> Как тебе моё предложение выше?

Предложение неплохое, но сколько это займёт по времени?

**Comment by w23** [comment]
От половины до двух стримов (в зависимости от того, насколько коряво оно может быть). Но смотри, что это мультипликатор для твоего труда, так что вполне может быть разумно.

**Comment by 0x4E69676874466F78** [comment]
Сначала добавь "блокировать любое сглаживание с любыми соседями для заданных поверхностей" а дальше посмотрим.
