### ISSUE TITLE
Studio model: v_shotgun - unexpectedly big shell

### ISSUE THREAD

**Issue by zgdump** [w23/xash3d-fwgs#63]
No comments, only kek

![image](https://user-images.githubusercontent.com/60278551/133495976-be961c21-9223-44a8-8ca9-2555d9819563.png)

**Comment by w23** [comment]
Does this happen with traditional rasterizer?

**Comment by 0x4E69676874466F78** [comment]
> 
@w23
> Does this happen with traditional rasterizer?

Only for vk, vk-rtx, not gl.

**Comment by MaxG2D** [comment]
Could this be releated to not yet implemented culling in vk_studio.c?

https://github.com/w23/xash3d-fwgs/blob/50ac0c3efa8ef2d4c7f002186cbea29815016370/ref_vk/vk_studio.c#L249

**Comment by 0x4E69676874466F78** [comment]
@MaxG2D вполне возможно из-за отсутствующего куллинга, да.

**Comment by 0x4E69676874466F78** [comment]
С другой стороны почему на традиционном рендере модель не видно?

**Comment by MaxG2D** [comment]
> On the other hand, why is the model not visible on the classic render?

Looking at code, I THINK @w23 needs to implement a custom rayhit shader for parts that are within `zNear` distance. Editing that value in `camera.c` works for regular, non-raytraced VK because the concept of culling is much easier to realize in rasterization - in path tracing, it simply breaks.

**Comment by MaxG2D** [comment]
One thing for sure, it's definitely a culling problem:
![2](https://user-images.githubusercontent.com/88550439/146649492-3a5e4a46-0918-4073-b172-e01e86fe7cfc.jpg)
![1](https://user-images.githubusercontent.com/88550439/146649491-526adb87-7f4e-46b5-b391-db860062b82c.jpg)

**Comment by w23** [comment]
Culling is a good hypothesis, thanks!
But it's not _that_ culling. As you can see it's also disabled for rasterizer.

I think that it's _near-plane_ culling, as we seem to start rays straight from camera origin and not from camera near plane. Moving ray start position should fix it.

**Comment by w23** [comment]
> Looking at code, I THINK @w23 needs to implement a custom rayhit shader for parts that are within `zNear` distance. Editing that value in `camera.c` works for regular, non-raytraced VK because the concept of culling is much easier to realize in rasterization - in path tracing, it simply breaks.

Essentially this, but no custom shader code necessary. We just need to move ray starting postions.

**Comment by MaxG2D** [comment]
> Essentially this, but no custom shader code necessary. We just need to move ray starting postions.

Hmm... Maybe I'm interpreting it incorrectly, but wouldn't that just simply move the camera position? I tried to edit the code to do that by changing the `vec3 origin` in `ray.rgen`, and it did just that, but perhaps I'm doing something wrong?

**Comment by w23** [comment]
What exactly did you do?

`origin` needs to be `uv`-dependent and start on a near plane instead of just camera origin.

**Comment by MaxG2D** [comment]
`vec3 origin    = (ubo.inv_view * vec4(0, 0, 0, 1)).xyz;`

to 

`vec3 origin    = (ubo.inv_view * vec4(0, 0, -4, 1)).xyz; //4.0 is the default near clip value`

fixes the clipping issue, but it shifts the whole camera projection forwards:

![1](https://user-images.githubusercontent.com/88550439/146660321-d89ac0bb-5b63-464a-a19c-df4c6026657b.jpg)
![2](https://user-images.githubusercontent.com/88550439/146660322-51ae6318-5058-47fe-b3c3-129ac6c42794.jpg)

**Comment by w23** [comment]
This doesn't seem correct, `vec3 origin` should depend on `uv` value, otherwise there's no way it would receive the correct position on the near plane (different for every pixel!). You seem to just shifting the point origin forward, but it stays the same for all pixels. Hence the projection shift.

I'm not sure what exactly should the correct math look like. I'm not very clever and have to spend some time with pencil and paper.

**Comment by 0x4E69676874466F78** [comment]
@MaxG2D это скриншот ровно с той же позиции? ты сохранился а потом для каждого раза сделал F7? (load)
Потому что видно что снизу где лучи модель выглядит не так и рядом стена справа тоже!

**Comment by MaxG2D** [comment]
> @MaxG2D это скриншот ровно с той же позиции? ты сохранился а потом для каждого раза сделал F7? (load) перед скриншотом? Потому что видно что снизу где RTX там модель оружия с руками и рядом стена справа выглядит не точно так же как в классическом!

Yes, that's how I've made the screenshot. There might be very small mouse movement between them, but yeah, it's the same exact spot and that shift is caused by the code I posted.

**Comment by 0x4E69676874466F78** [comment]
Перспектива в rtx рендере должна быть той же самой что в классическом рендере.

**Comment by 0x4E69676874466F78** [comment]
Может ли это быть связано с тем cull который в том числе для воды работает? и который у нас не реализован?
https://github.com/w23/xash3d-fwgs/issues/264#issuecomment-1435058944

**Comment by w23** [comment]
Сомнительно (я не вижу, где бы там оно куллилось с достаточно гранулярностью), но это интересная гипотеза

**Comment by w23** [comment]
В общем, мы по кругу тут в комментариях ходим.
Я посмотрел через рендердок, что делает традиционный вулкан, и там да, эта фиговина находится тупо перед near plane, и поэтому не видна. На лучах у нас всё ещё неверный origin для лучей -- он начинается в точке камеры, а не на near plane: https://github.com/w23/xash3d-fwgs/blob/d1376a89e45ef3734a10712b65b614d6df6ea713/ref/vk/shaders/ray_primary.comp#L36-L37

**Comment by w23** [comment]
Другое дело, что даже находясь за камерой, эта бобина будет участвовать в освещении, отбрасывать тень, етц.
Что с этим делать, я не знаю. Можно вырубать пушку из освещения, но тогда просто всё будет корявое (это, кстати, к https://github.com/w23/xash3d-fwgs/issues/462).
Можно захачить и по каким-то косвенным признакам не рисовать `"shell"` submodel.

**Comment by 0x4E69676874466F78** [comment]
>  Можно захачить и по каким-то косвенным признакам не рисовать "shell" submodel.

Давай через это #459 попробуем.

**Comment by 0x4E69676874466F78** [comment]
v_shotgun.mdl.patch
```
{
"_xvk_bone_name" "shell"  // массив названий костей через пробел
//"_xvk_bone_id" "31" // массив идов костей через пробел
//"_xvk_texture_name" "shell"  // массив названий текстур через пробел
//"_xvk_hitbox" "0" // есть хитбокс (1) или нет (0)
"_xvk_dont_apply_for_animation" "reload" // массив анимаций через пробел
// "_xvk_hide_mesh" "1" // можно сделать так, но в нашей парадигме это не требуется
}
```

Вообще я понял что патчи у нас несколько грязновато сдизайнены по части семантики, но я не знаю стоит ли делать чище.
