### ISSUE TITLE
Normalmaps are not smoothed according to smooth geometries

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#630]
Есть проблема что карты нормалей не сглаживаются как нормали геометрии.
Поэтому получается что с одной стороны геомерия выглядит гладкой, а вот картанормалей на ней словно геометрия не сглаживалась вовсе:
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/7b72d43a-1bdf-4bea-9452-19fc22106ab6)
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/61831884-e95b-45d5-94cb-e19fec02cff4)

![image](https://github.com/w23/xash3d-fwgs/assets/4449851/cdd72878-4566-4697-8120-d4a475765841)
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/6c3eda1f-57ac-42f5-8ed1-0711da833421)

Если это сравнительно легко решается то лучше решить, если сложно, то можно забить.

Возможный вариант решения через тесселяцию (на будущее).

**Comment by 0x4E69676874466F78** [comment]
Вот для сравнения эта же текстура (в сером виде) в качестве basecolor:
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/236fed30-79c3-46c8-bc13-f6fa26a16a46)
а вот если подложить только нормаль:
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/bf2d42a5-6dc5-4738-b294-8a80a91c6f41)

Как понимаю это не решается ничем кроме как тесселяцией.

**Comment by 0x4E69676874466F78** [comment]
Я не призываю этим замороачиваться. Таких моментов на карте не много, фактическая нормаль будет более приглушённой.
Решать эту проблему можно толко если в контексте vector displacement mapping, не более.
То есть можно в рамках vector displacement mapping (если мы до него вообще доберёмся, а я надеюсь, ибо крутая дорого-богатая фишка) можно добавить механизм автосглаживания по какой оси (в данном случае X) для энтитей или выделенных вручную граней.

**Comment by w23** [comment]
> Возможное решение может быть в правильном сглаживании тангентов и бинормалей. Сглаживаются ли тангенты там же, где сглаживаются нормали? Нормализуется ли все это в шейдере? Надо будет глянуть в коде.

:tada:  Конечно же нет! :tada: :tada: :partying_face:

**Comment by LifeKILLED** [comment]
А еще, если моделька отзеркалена (правая и левая половины зомбяка), карта нормали выглядит отзеркаленной. Надо инвертировать бинормаль. Вместо того, чтобы передавать в шейдер цЕлую бинормаль, Unity кладет в w-координату 1 или -1, которые указывают на отзеркаливание. В шейдере обработать это не трудно. Трудно правильно рассчитать всë это на ЦПУ. Все примеры очень большие и трудные для понимания

**Comment by w23** [comment]
> А еще, если моделька отзеркалена (правая и левая половины зомбяка), карта нормали выглядит отзеркаленной. Надо инвертировать бинормаль. Вместо того, чтобы передавать в шейдер цЕлую бинормаль, Unity кладет в w-координату тангента цифру 1 или -1, которые указывают на отзеркаливание бинормали. В шейдере обработать это не трудно. Трудно правильно рассчитать всë это на ЦПУ. Все примеры очень большие и трудные для понимания

Мы там на вчерашнем стриме добавили просто флипанье знака тангента, если ориентация текстурных координат не та. Вроде починило косяки, которые мы видели. Хз, насколько это правильное/полное решение.

**Comment by w23** [comment]
Чёт я призадумался.
Вот эта строчка как раз должна тангент поправлять под сглаженную нормаль. Минуя явное сглаживание тангента.
https://github.com/w23/xash3d-fwgs/blob/365fffacca2c4527f33cd356661226015e8f37df/ref/vk/shaders/ray_primary_hit.glsl#L47

**Comment by w23** [comment]
А что если сравнить с одной и той же позиции скриншоты со сглаживанием и без?

**Comment by w23** [comment]
Там ещё может быть момент, что для освещения мы берём `geometry_normal`, потому что shading может давать семплирование вглубь геометрии.

**Comment by 0x4E69676874466F78** [comment]
@w23 
>  T = normalize(T - dot(T, geom.normal_shading) * geom.normal_shading); 

Вообще похеру.

![image](https://github.com/w23/xash3d-fwgs/assets/4449851/d18b9c14-e1e0-4287-a6e9-07ab4e37766a)
Закомментировал:
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/f6faa136-81ac-4292-aa4a-c622c26c2bed)

Но это же только баунсов касается.

**Comment by w23** [comment]
Произведено исследование.
Всё у нас нормально гнётся тангент. Однако, это гнутие никак не влияет на данную конкретную нормалмапу, потому что она порождает исключительно "вертикальные" изменения нормали, тогда когда тангент влияет только на "горизонтальную" компоненту.
Поэтому сглаживание нормалей и тангентов на картинку для этой конкретно текстуры и геометрии влиять не может.

**Comment by 0x4E69676874466F78** [comment]
Закрыто: без тесселяции проблема не решаема.
