### ISSUE TITLE
Rename vk_rtx_* cvars to vk_rt_* cvars

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#632]
Думаю внутри движка фокусироваться на бренде rtx не стоит. Да и на стримах уже в заголовке RT а не RTX.

**Comment by w23** [comment]
Можно даже тупо `rt_`, а не `vk_rt_`.
Меньше писать и вообще.

**Comment by 0x4E69676874466F78** [comment]
> Можно даже тупо rt_, а не vk_rt_.
Хочешь чтобы были vk_ и rt_?

**Comment by w23** [comment]
> Хочешь чтобы были vk_ и rt_? Или всё перевести на rt_?

`rt_` для RT-специфичной фигни.
`vk_` для вулкано-специфичной, но не обязательно лучевой.
`r_` для всего, что технически может быть общим для всех рендеров (например, профайлер/speeds)
