### ISSUE TITLE
Add cvar vk_rt_debug_highlight_surface

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#633]
Передаются иды через запятую или пробел (как у нас принято?).
Подсвечивает в лучевом рендере заданную грань как-нибудь, хоть тупо заливкой цветом (красным например).
Очень поможет в дальнейшей отладки патчей. Т.к. не всегда легко нормально прокомментировать где конкретно грань а потом приходится долго искать.

**Comment by w23** [comment]
Decided that it can be done ad-hoc by modifying patches for now.

**Comment by 0x4E69676874466F78** [comment]
Да, буду использовать заготовки для патчей.
