### ISSUE TITLE
Update brdf.h

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#662]
https://github.com/boksajak/brdf
#### Features:
- Added VNDF sampling from __"Sampling Visible GGX Normals with Spherical Caps"__ by Dupuy & Benyoub
- Added Walter's sampling of GG-X distribution
- Added optional reflectance parameter to specify minimal reflectance of dielectrics per material
- Added function **specularGGXReflectanceApprox** from "Accurate Real-Time Specular Reflections with Radiance Caching" in Ray Tracing Gems by Hirvonen et al.
- All functions and structures put into **brdf** namespace when compiling as C++
- All functions specified as static when compiling as C++

**Comment by w23** [comment]
We have our own PBR sampling code at home, an we're not using external `brdf.h` anymore.
