### ISSUE TITLE
The back side of additive surfaces is not сulled

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#665]
VK rastr/GL:
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/1b589e83-00fc-4562-8eed-1fa38362a4e7)
VK RT:
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/e493e44d-3b78-4067-96a6-dbbc1b7a65dc)

В данном случае линза/призма будет заменена на другой рендермод, но в других случаях аддитивные поверхности возможно будут выглядить коряво. 
Подозреваю эти лучи здесь:
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/9e4499f7-c667-4fcb-8c63-dc59a1612484)
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/5c9ca670-b5f7-4a63-aa9a-ed092a74e66b)
Возможно поэтому выглядят сильно плохо, хотя эти лучи должны быть заменены на волуметрики по идее.

**Comment by w23** [comment]
о, это прекрасный экземпляр проблемы для запекания в набор тестов для воспроизводимого рендера

**Comment by w23** [comment]
Откуда первый скриншот? Карта, локация

**Comment by 0x4E69676874466F78** [comment]
c1a0e
