### ISSUE TITLE
PBR dielectrics/metals is broken if blacked

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#666]
Открываем mirror.mat находим там "for" "reflect1" и раскомментируем там 
```
//"basecolor_map" "/colors/black.png"
//"metalness" "0"
```
Далее идём на test_glass и видим там где были зеркала абсолютно чёрное тело вместо блестящего "чёрного пластика".
Его даже фонарик не берёт. С белым basecolor_map всё работает вроде корректно.

Диэлектрик ещё так устроен что как раз на чёрном отражения у него лучше:
![d5](https://github.com/w23/xash3d-fwgs/assets/4449851/74b1fe66-00ee-4bed-b1a2-aaa2077f3bd3)

Рендер substance designer, в режиме IRay (photoreal).

**Comment by 0x4E69676874466F78** [comment]
https://github.com/KhronosGroup/glTF/blob/main/specification/2.0/Specification.adoc#complete-model

**Comment by 0x4E69676874466F78** [comment]
Вместе с этим возникает ещё одна проблема PBR в отражениях:
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/c5a868de-ee9e-4f06-94dc-5db857937437)
В том же сабстенсе:
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/76212dbd-0874-4417-9743-d073024c71a0)
Обрати внимание цвет от белой лампы на плитке жёлтый! так быть не должно.
Если я сделаю ярче источник света это будет заметнее:
`+0~FIFTS_LGHT5   255 255 255  20000`
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/f0ad3b62-c253-4c6b-9ee1-7029cefe1801)
Усугубим проблему:
`+0~FIFTS_LGHT5   0   0   255  20000`
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/7fd4f64a-66cd-48b1-b1e0-9573419683ef)
В сабстенсе:
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/520a0d3d-da9c-4ff1-b7dd-72eefa079e50)

**Comment by LifeKILLED** [comment]
При отражении от диэлектрика спектр световых волн не меняется, а при дифузе фотоны взаимодействуют с атомами, рассеиваясь под поверхностью во всех направлениях. Так в нашей реальности получаются два разных явления:
1. отражение (а также спекуляр, как его аппроксимация)
2. диффуз (прямой свет с тенями и глобальное освещение)

В случае с металлом отражение принимает цвет поверхности либо благодаря квантовым эффектам (золото) либо благодаря лаку/краске (то есть полупрозрачный цветной слой поверх железки).

Короче, у металла всё умножается на base_color, но у диэлектрика спекуляр на base_color умножать не надо.

У нас же диффуз с отражениями мешаются в одну кучу. Это неправильно.

**Comment by 0x4E69676874466F78** [comment]
Металлы с чёрным basecolor у нас тоже сломаны, вот референс как должно:
![metals](https://github.com/w23/xash3d-fwgs/assets/4449851/93876532-f423-4e1c-982e-4e1fc9a1491b)

**Comment by 0x4E69676874466F78** [comment]
https://github.com/0x4E69676874466F78/test_maps_for_hlrtx_project/releases/tag/2023_12_15 карты обновил где добавил металло-дилектрики.

**Comment by w23** [comment]
Done in the handmade-brdfs branch/PR
