### ISSUE TITLE
Warning for 32bit builds (not supported)

### ISSUE THREAD

**Issue by ertup0** [w23/xash3d-fwgs#670]
**To reproduce**
1. load c1a0d
2. Observe native opengl renderer without RT
3. The console spews a bunch of N/A errors

**Screenshots**

![Screenshot_34](https://github.com/w23/xash3d-fwgs/assets/58479951/e9a4fea5-f207-464a-813a-fe21129cf02e)

**Moar context**
- 6b1eeee26bc49bd5dd75809db9de8da451263db5
OS Windows 10
- RTX 2060 Super
- 546.17

**Comment by 0x4E69676874466F78** [comment]
Please run:
1. `xash -ref vk -dev 3 -console -log` and exit
2. `vulkaninfo --text -o vkinfo.txt` 
attach engine.log and vkinfo.txt here (can be a zip file)

**Comment by w23** [comment]
Judging from a combination of RT-capable HW, recent drivers, and no RT extensions exposed I'd say that you're running a 32-bit build.
32-bit drivers do not expose hardware ray tracing extensions at all. You must run an amd64 build: https://github.com/w23/xash3d-fwgs/wiki/How-to-build-a-64bit

I guess we should have a loud warning about that in the logs, so it's immediately obvious.

We also found this out the hard way. This 64-bit dependency doesn't seem to be widely advertised anywhere about hardware ray tracing.

**Comment by 0x4E69676874466F78** [comment]
@ertup0 were you able to run it with ray tracing?

**Comment by w23** [comment]
> where is the macro for checking 2^5 vs 2^6 bit? i just followed build instructions (64bit obv...)

I'm not really sure if xash has one specifically.
The major part of the task here is to figure this question out. Consult google, compiler docs, etc, and present a PR together with a description why you're doing it a certain way and how/why it will work on all targets/archs/oses/compilers this renderer supports.

**Comment by ils8** [comment]
> > where is the macro for checking 2^5 vs 2^6 bit? i just followed build instructions (64bit obv...)
> 
> I'm not really sure if xash has one specifically.
> The major part of the task here is to figure this question out. Consult google, compiler docs, etc, and present a PR together with a description why you're doing it a certain way and how/why it will work on all targets/archs/oses/compilers this renderer supports.
> 

Q_buildarch 228 in /public/build.c

**Comment by w23** [comment]
> but should i use r_speeds ie profiler to sren'k into log?

speeds/profiler are irrelevant to this task
find the place in `vk_core.c` where the lack of ray tracing is detected

**Comment by 0x4E69676874466F78** [comment]
@ils8 через `vk_core.h` уже доступен `XASH_64BIT`
Тебе надо в `vk_core.c` внутри enumerateDevices (если нет места лучше) сделать условие (!XASH_64BIT) с ошибкой.

**Comment by ils8** [comment]
as per discord, public/build.c l228 :Kappa:

**Comment by ils8** [comment]
https://github.com/ils8/xash3d-fwgs/commit/c3307d9f89574e8b54b7479a9425d5e88b41f7d0

**Comment by 0x4E69676874466F78** [comment]
@ils8 
> [ils8@c3307d9](https://github.com/ils8/xash3d-fwgs/commit/c3307d9f89574e8b54b7479a9425d5e88b41f7d0)

1. Не смешивай задачи. Сделай отдельный бранч для этой фичи. 
2. `public/build.c` где я просил добавить проверку? Зачем заниматься самодурством? Это движок он к рендеру никакого отношения не имеет.
3.  и `#include <stdio.h>` — уже не смешно. Разберись в кодовой базе хотя бы минимально. Там же совсем рядом в `vk_core.c` валяются `gEngine.Con_Printf( S_ERROR "")`. 
4. `printf("AYAYAYYA %s\n", is64 ? "2^6!" : "2^5 :weak:");` — кто это будет читать ты подумал? Нужно адекватное нормальное сообщения без всякого выпердрёжа с 2^6 и 2^5 и чтобы было понятно что лучевые расширения неподдерживаются в 32бит. 

Последний шанс сделать нормально, дальше я сделаю уже сам в 3 строчки.

**Comment by ils8** [comment]
> Пришло (понимание). Ну а какой ты реакции ожидал? Ты словно назло делаешь неправильно/троллишь. Я такого ещё не встречал, поэтому тон уже стал таким, да. Можешь более ответственно относиться к проекту? Безотносительно тона в сообщении выше, все мои замечания остаются в силе, будь добр исправься.

![20231203_10h22m18s_grim](https://github.com/w23/xash3d-fwgs/assets/92700710/0227643f-151e-4964-82a2-bc95126e145a)

**Comment by 0x4E69676874466F78** [comment]
@ils8 тебе надо создать новую чистую ветку (относительно vulkan апстрима) для этого изменения.
https://github.com/w23/xash3d-fwgs/compare/vulkan...ils8:xash3d-fwgs:32vs64bit у тебя много лишнего захватило.
