### ISSUE TITLE
Skybox stuff

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#677]
- [ ] в оригинале текстуры неба располагаются в `gfx/env`, в рендере почему-то `env`, я сходу не въехал.

- [ ] рендер грузит небо по схеме `имя_сторона`, хотя в игре и модах это как `имясторона` 
https://github.com/w23/xash3d-fwgs/blob/6fda8bd977da55b23c9fee2cd00cf9e5b027fc81/ref/vk/r_textures.c#L936-L936

- [x] не работает перезагрузка текстур через перезагрузку материалов

- [x] хотелось бы HDR скайбокс 
  - [x] с настройкой (mat файл) где можно регулировать "яркость" неба (зависимость #193)
  - [ ] https://github.com/KhronosGroup/glTF-IBL-Sampler

**Comment by w23** [comment]
> * [ ]  в оригинале текстуры неба располагаются в `gfx/env`, в рендере почему-то `env`, я сходу не въехал.

Я тоже не помню, почему мы так решили. Всегда можно легко поменять на что угодно.

>     * [ ]  рендер грузит небо по схеме `имя_сторона`, хотя в игре и модах это как `имясторона`
>       https://github.com/w23/xash3d-fwgs/blob/6fda8bd977da55b23c9fee2cd00cf9e5b027fc81/ref/vk/r_textures.c#L936-L936

У нас тоже так было -- мы пробовали оба варианта.
С последними изменениями мы переехали на то, что делает imagelib у себя внутри. А именно: опять пробует два (или даже три?) варианта.
Но, мы также умеем загружать теперь кубмапу целиком из одного КТХ2 файла.

>     * [ ]  не работает перезагрузка текстур через перезагрузку материалов

Сделали в #708.

>     * [ ]  хотелось бы HDR скайбокс

Сделали в #708 ;)

>       * [ ]  с настройкой (mat файл) где можно регулировать "яркость" неба (зависимость [Adaptive tone mapping (dynamic/auto exposure) #193](https://github.com/w23/xash3d-fwgs/issues/193))

Сделали в #708 ;))

>       * [ ]  https://github.com/KhronosGroup/glTF-IBL-Sampler

?
