### ISSUE TITLE
Optimize skybox loading

### ISSUE THREAD

**Issue by w23** [w23/xash3d-fwgs#706]
With the new hi-res skyboxes it became extremely slow. Feels like roughly more than half of map loading time.

What could we do:
- determine whether the map even has SURF_SKY. If it doesn't then skybox can be completely omitted.
- support loading packed KTX2 cubemaps directly
- cache: do not unload then reload the same skybox

**Comment by 0x4E69676874466F78** [comment]
Это надо делать заодно с #579
