### ISSUE TITLE
Add vk_toggle_pbr_textures cvar for traditional render

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#711]
Чтобы на растеризации можно было включить basecolor_map текстуру, чтобы те у кого пока нет лучей могли хотя бы примерно понять как выглядит.

**Comment by w23** [comment]
Рисует, но в неправильном цветовом пространстве (sRGB текстуры семплит как UNORM (linear)). Это можно починить, но с трудом -- надо отдельно сохранять sRGB дескрипторы, сейчас их попросту нет, т.к. семплинг в лучах делается иначе -- через bindless.
