### ISSUE TITLE
Wrong emissive power from !TOXICGRN texture (brush with water texture, but not func_water)

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#72]
Map: [test_brush2](https://github.com/w23/xash3d-fwgs/files/7173669/test_brush2.zip), second room via teleport (inside map)
By qrad lightmap: 
![изображение](https://user-images.githubusercontent.com/4449851/133519642-13147834-a17b-458e-bbb0-c68784dfa032.png)
By rays:
![изображение](https://user-images.githubusercontent.com/4449851/133519700-e0ff1500-2b73-44dd-8afc-5041ed4f6e17.png)
```
TOXICGRN        0  255 0    300
!TOXICGRN       0  255 0    300
GLASSGREEN      0  255 0    300
```
If you set !TOXICGRN to brightness 5-6 times more (1500-1800), it starts to look like roughly correct.

**Comment by 0x4E69676874466F78** [comment]
Bonus (notes for you).
This should be looked at with caution as denoisen can make significant changes (give a lighter texture).

In order to achieve the desired emissive "inside", you must also multiply the brightness by ~4-6 times (it's a compromise).
### qrad (reference)
```
TOXICGRN        0  255 0    300
!TOXICGRN       0  255 0    300
GLASSGREEN      0  255 0    300
```
![изображение](https://user-images.githubusercontent.com/4449851/133595388-f724ebc4-5a2e-4871-b376-059ffd9a9b47.png)

### rays (wrong outside, ~correct inside)
```
TOXICGRN        0  255 0    1800
!TOXICGRN       0  255 0    10800
GLASSGREEN      0  255 0    1800
```
![изображение](https://user-images.githubusercontent.com/4449851/133598096-3124b4ab-20ec-41a4-8af2-2b12a580a67a.png)

### rays (correct outside, wrong inside)
```
TOXICGRN        0  255 0    300
!TOXICGRN       0  255 0    1800
GLASSGREEN      0  255 0    300
```
![изображение](https://user-images.githubusercontent.com/4449851/133596232-6b71e085-c53c-443f-8acb-75b154973d00.png)




But in general, each texture illuminates a little differently in qrad, but this is another time (I will create a separate issue later).

**Comment by w23** [comment]
На свежем билде это выглядит почти правильно, кроме средней ванночки, которая почему-то тёмная. Чем она отличается от остальных?

**Comment by 0x4E69676874466F78** [comment]
@w23 
> На свежем билде это выглядит почти правильно, кроме средней ванночки, которая почему-то тёмная. Чем она отличается от остальных?

Наличием `!`, помнишь я кидал код где текстуры с `!` отдельно обрабатываются? Как понимаю эта логика корнями из квейка где типами материалов не утруждались.

**Comment by 0x4E69676874466F78** [comment]
Забыл написать, относительно входа: func_water с TOXICGRN, просто браш с !TOXICGRN и просто браш с GLASSGREEN.
Типа демонстрация всех типов поверхностей.

**Comment by w23** [comment]
Ааа, я, кажись, догадался. Думаю, что это из-за того, что водянистые поверхности у нас отрисовываются вообще отдельно через динамические источники света, и они не попадают в список светящихся поверхностей (даже если rad правильный).

Это нужно будет сделать вместе с #132

**Comment by 0x4E69676874466F78** [comment]
@w23 а как же func_water? почему он работает нормально?

**Comment by w23** [comment]
Тогда я назад запутался. Можешь пометить, кто из них какой?

**Comment by 0x4E69676874466F78** [comment]
@w23 а ui_infotool тебе на что? 😄  ну и я выше написал что от портала они идут по порядку: func_water с TOXICGRN, просто браш с !TOXICGRN и просто браш с GLASSGREEN.
Но щас сделаю дополнительные варианты на всякий случай и с текстовой с пометкой когда будешь залезать в эти углубления. Может чего ещё "всплывёт".

**Comment by 0x4E69676874466F78** [comment]
Щас залью обнову карт. Из необычного, у func_water с !TOXICGRN на qrad свечение сильнее остальных, видимо из-за двойной поверхности func_water брашей.
В остальном всё то же самое. Поверхность `!` будь у неё func_water или не будь в лучах не светится должным образом.

**Comment by 0x4E69676874466F78** [comment]
https://github.com/w23/xash3d-fwgs/issues/33#issuecomment-962265044

**Comment by 0x4E69676874466F78** [comment]
https://sourcegraph.com/github.com/FWGS/xash3d-fwgs/-/blob/engine/common/mod_bmodel.c?L2319-2320 отсюда начинается слом светимости (я немного промахнулся в прошлый раз, но суть именно в `!`). Неправильно в рендере обрабатывается `SURF_DRAWTURB`.
Конкретнее здесь:
1. https://github.com/w23/xash3d-fwgs/blob/vulkan/ref_vk/vk_brush.c#L385-L390 комментим false один браш чинится.
2. https://github.com/w23/xash3d-fwgs/blob/vulkan/ref_vk/vk_brush.c#L420 комментим это другой браш чинится.
Как хорошо что был добавлен ещё один браш для тестов.
Пуллреквест не делаю так как не знаю мотивацию этих строк, но наверное это было сделано в самом начале толком не разбираясь?

**Comment by w23** [comment]
О, теперь мне понятно, почему так. Это имеет отношение к #132

**Comment by 0x4E69676874466F78** [comment]
Код воды мудрёный, со старым коммитом собраться не удаётся.
Есть подозрение что плохо светит и из-за конфликта граней и возможно из-за кривых нормалей (вот эти чёрные квадраты могут быть из-за нормалей).

**Comment by 0x4E69676874466F78** [comment]
https://github.com/w23/xash3d-fwgs/issues/267#issuecomment-991779962 подозрение на виновника.

**Comment by 0x4E69676874466F78** [comment]
Сила света напрямую зависит от `#define SUBDIVIDE_SIZE` в common_geometry.c
Чем значение меньше, тем меньше будет светить этих поверхности. 
На большом значении SUBDIVIDE_SIZE 256 при большой волне можно увидеть что его как бы переключает туда-сюда почему-то. Есть подозрение что где-то что-то не так идёт. Может не в нормалях, а тангенсах дело? (я в этом не разбираюсь). Не может это ещё быть связано с кривыми нормалями на студиомодел?

**Comment by 0x4E69676874466F78** [comment]
Прикладываю обновлённый [test_brush2.zip](https://github.com/w23/xash3d-fwgs/files/7699922/test_brush2.zip) для тестов.

**Comment by 0x4E69676874466F78** [comment]
Прикладываю видео.

https://user-images.githubusercontent.com/4449851/145730749-258ae97b-c4a1-4b08-902b-7b49002b4773.mp4

На видео включаю vk_rtx_freeze, как видно оно тоже влияет на результат.

**Comment by 0x4E69676874466F78** [comment]
Написал:
```
{
"for" "!TOXICGRN"
"basecolor_map" "colors/white.png"
"normal_map" "debug/debug_circle_normal1.png"
}
```
Нормали не подвахтились.

**Comment by w23** [comment]
> Сила света напрямую зависит от `#define SUBDIVIDE_SIZE` в common_geometry.c Чем значение меньше, тем меньше будет светить этих поверхности. На большом значении SUBDIVIDE_SIZE 512 при большой волне можно увидеть что его как бы переключает туда-сюда почему-то. Есть подозрение что где-то что-то не так идёт.

О. Это мы каждый кадр выбираем случайный треугольник, и считаем вклад только от него. Чем мельче треугольник, тем меньше вклад. Это чушь собачья, надо чинить (есть с ходу несколько идей, как).
Спасибо за находку! Я про это и забыл совсем (наверняка FIXME где-то стоит).

> Может не в нормалях, а тангенсах дело? (я в этом не разбираюсь). Не может это ещё быть связано с кривыми нормалями на студиомодел?

Не, тангенты тут вообще ни при чём. Они используются только для нормалмапов, которые не участвуют в освещении никак.

**Comment by w23** [comment]
> Прикладываю видео.
> Half-Life.2021-12-13.00-41-14.mp4

Лол F. Я думаю light clusters были ошибкой. Надо делать что-то другое на compute шейдерах и полностью динамическое.

> На видео включаю vk_rtx_freeze, как видно оно тоже влияет на результат.

freeze не фризит кластеры емнип.

**Comment by 0x4E69676874466F78** [comment]
> Я думаю light clusters были ошибкой

А что там?
