### ISSUE TITLE
Smooth blending for all particles 

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#722]
Сейчас мягкое смешивание применяется только для некоторых частиц от оружия, но не для взрывов от гранат или мин (оба вида).
![image](https://github.com/w23/xash3d-fwgs/assets/4449851/dbaafbc7-8d08-48f8-9b9b-f28672c00f78)

**Comment by w23** [comment]
This looks the same as for GL renderer.
We only use soft depth effect for glow fx, otherwise it looks a bit weird, e.g. leaking through player weapon geometry.

For explosions/smoke specifically we might eventually switch to proper volumetric clouds

**Comment by 0x4E69676874466F78** [comment]
> For explosions/smoke specifically we might eventually switch to proper volumetric clouds

Дым сравнительно не сложно сделать красивым, а вот красивые взрывы сложная задача, предлагаю в качестве компромисса попробовать хак, где мы клонируем спрайт отдаляем его позади исходного спрайта, у того что перед нами делаем значительно больше дистанцию сглаживания и получается что-то вроде такого:
![image](https://docs.flaxengine.com/manual/particles/tutorials/media/soft-particles.jpg)
