### ISSUE TITLE
pbr skybox for bounce.bsp is wrong if load after c2a5a

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#737]
У карты зашит skyname 2desert, а грузится словно он desert, ~~т.е. где-то откусывается первый знак почему-то.~~
https://github.com/w23/xash3d-fwgs/issues/737#issuecomment-1930374348

**Comment by w23** [comment]
А в логах что пишет?

**Comment by 0x4E69676874466F78** [comment]
> А в логах что пишет?

Ничего. 
Но я обнаружил что ошибка в другом. Если я сразу загружаю после test_light (грузится с сохранения) bounce то там небо ок.
Далее если я загружусь в c2a5a а потом обратно на bounce то небо станет от c2a5a. То есть ошибка в другом.

**Comment by w23** [comment]
Ага, старые скайбоксы не чистятся, если новых нет. Завтра починю.
