### ISSUE TITLE
Integrate known good rad files into repo

### ISSUE THREAD

**Issue by w23** [w23/xash3d-fwgs#76]
Currently the repo contains some odd third party `.rad` files. These are obsolete (lighting computation has been updated since), and would have to be manually copied into `valve/rad` either way.

We now have a better rad files that are closer to original (thanks @0x4E69676874466F78!). They should be integrated into this repo and also into build scripts to be automatically installed.

This is likely to bel a somewhat temporary solution before a better system is devised for more or less proper PBR materials.

**Comment by 0x4E69676874466F78** [comment]
In general, for compatibility, it is better to put rad files in maps folder, so it is more convenient to compare with qrad.
