### ISSUE TITLE
Crash when load map t0a0b, c2a4c, c2a4e

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#77]
> zgdump: Метод VK_RayFrameAddModel, ассерт model->as != VK_NULL_HANDLE

Падает ещё в разных местах на c2a5e

**Comment by w23** [comment]
`Error: Maximum number of kusochki exceeded on model reference` :thinking:

**Comment by w23** [comment]
The above kusochki limit is easy to fix by increasing `MAX_KUSOCHKI` to e.g. `16384`.

c2a5e also fails with
```
[22:43:09] Error: Ran out of model cache slots
Process 3696087 stopped
* thread #1, name = 'xash3d', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
    frame #0: 0x00007fff38272540 libref_vk.so`VK_RayFrameAddModel(model=0x0000000000000000, render_model=0x00007fff3fca7240, transform_row=0x00007fff3fca7170, color=0x00007fff3fbef154, entcolor=(r = '\xff', g = '\xff', b = '\xff')) at vk_ray_model.c:333:3
   330 		}
   331 	
   332 		{
-> 333 			ASSERT(model->as != VK_NULL_HANDLE);
```
which is concerning because current limit is whopping 1024 models that should be more than we'd ever need (note that we'll also need 3x that number for overlapping concurrent frames optimization).

- [ ] what are they?
- [ ] can we coalesce them somehow? e.g. all sprites are combined into one?

**Comment by w23** [comment]
Other actionable items here:
- [ ] Increase limits. We definitely need more kusochki. This is fundamental, no way around it. For models cache, investigate (and likely also increase).
- [ ] Make game survive this, but complain really loudly on screen (e.g. huge red string near crosshair) and in logs
- [ ] Dump more context and stats into the log: models with names, geometry stats, etc.

**Comment by MaxG2D** [comment]
This bug can be replicated fairly consitently also on map c3a1 when shooting through the vines that lead upstairs
![Untitled](https://user-images.githubusercontent.com/88550439/146067836-665de835-5041-43d3-bccb-5dac9a8fe40d.jpg)

**Comment by 0x4E69676874466F78** [comment]
#339

**Comment by 0x4E69676874466F78** [comment]
Больше не падает.
