### ISSUE TITLE
Crash when load map boot_camp

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#85]
Может влиять наличие или отсутствие -vkdebug

**Comment by 0x4E69676874466F78** [comment]
![изображение](https://user-images.githubusercontent.com/4449851/171997769-4098da5b-95f6-4ac7-9d28-e67c11a0ec44.png)

**Comment by w23** [comment]
`Maximum number of kusochki exceeded on model boot_camp.bsp`. Там OVER 9000 (10482) поверхности, а при бюджете в 16384 кусочка, только 8192 доступны.
Придётся либо консолидировать кусочки как-то, либо поднимать их количество.

**Comment by 0x4E69676874466F78** [comment]
Консолидировать это как? А чем существенно плохо поднятие?

**Comment by 0x4E69676874466F78** [comment]
Если на c2a5 начать быстро шмалять по бочкам и взрывать их всех то 
![image](https://user-images.githubusercontent.com/4449851/222098350-8368b9d0-4b13-4d54-8e74-6bb704177b57.png)

**Comment by w23** [comment]
Да ничем особо. Можно и тупо поднять.
